### ISSUE TITLE
No scroll on data entry pages

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#101]
The data entry pages no longer have scroll bars to reach the bottom data fields

**Comment by matmaxgeds** [comment]
This bug appear only when doing the initial data entry - if you return to the page then there is scrolling

**Comment by kndm** [comment]
Screenshot would be helpful @matmaxgeds on this as I can't try to reproduce/spot without the ability to do data entry myself (as the project data shouldn't be touched)

**Comment by matmaxgeds** [comment]
I can't re-create this so closing
