### ISSUE TITLE
Calendar widget maxes out at 2029

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#103]
The calendar is limited to 2019 - but it should be unlimited

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
I now see 2069........is that hardcoded, or a rolling end date?

**Comment by raashidahmad** [comment]
@matmaxgeds It calculates the previous 50 years for past years, and 50 + years for future years by comparing it with current year. This will be updating every year according to current year. If you want it in some other way, please guide me or close if you agree with this strategy.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks - this sounds sensible
