### ISSUE TITLE
Trim text fields

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#108]
Some text fields (especially those that originally came from IATI) have a lot of excess space at the beginning or end - please trim this (ideally in the initial IATI parser), but we also need to do this when users are entering data in the data entry database - some users may press [return] etc when entering descriptions. I don't think we can allow any of [tab], [newline], or [space - at the beginning or end, or more than one space at a time] when the data is saved - although no problem if they want to use them when typing out the description.

**Comment by raashidahmad** [comment]
Space trimmed when entering title and description from start and end.
