### ISSUE TITLE
Source projects visible after merge is made

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#109]
At the moment, when you merge two projects, this appears to happen after the 'add date, title. desc.' screen. But this means that on the next screens, there are no source projects with which to chose data from - the merge needs to take place at the end when clicking 'finish' from the users perspective. If you want to do the merge at the start, I suggest that you do it when clicking the initial 'merge projects' button on the very first screen, not after the title/dates screen - and then keep the source projects in a temporary cache to present to the user while they are deciding which data to use for the merged project.

**Comment by mohamedgele22** [comment]
i just can't see that 'merge projects'tab.

**Comment by matmaxgeds** [comment]
Closing as suspect fixed elsewhere
