### ISSUE TITLE
Show more detail when chosing which IATI projects to select

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#116]
In order to decide which IATI projects to select, users may need to see all the data for an IATI project.  Please change the 'description' button to 'more detail' and showed all the data for the project, not just the description in the popup.

Please also include the IATI activity identifier - with a hyperlink in the following format: http://d-portal.org/q.xml?aid=SE-0-SE-6-5204050701-AWE-72010 - so that I can easily check which IATI XML the parser is picking up and which it isn't.

**Comment by matmaxgeds** [comment]
Update - here is a better link for the raw IATI data: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=NL-KVK-41177206-C-002350

**Comment by matmaxgeds** [comment]
And I also noticed that some of this already exists in the 'view details' link on IATI projects on the project-entry screen - so these two uses can be the same, just improved, no need to develop it separately. Essentially it needs to show all the information that we are parsing from the IATI activity - plus also display a copy of the original XML - but I think this is sensible to serve it ourselves given that we have it - rather than relying on the datastore or d-portal. Note that we should show the header if the XML file that has the generic organisation/file bits as well as the specific activity XML - so basically it should be the activity XML (incl. child activities), plus the header of the file it was drawn from.

**Comment by raashidahmad** [comment]
Please see this ticket already discussed against this feature.
Advanced Search on Data Entry #41
Lets discuss it, and keep only one ticket for this feature.

**Comment by matmaxgeds** [comment]
ok, closing here
