### ISSUE TITLE
IATI files - are we capturing them all?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#117]
Hi Rashid, please can you share a list of which IATI files the AIMS is currently finding and parsing? For example, I was searching for a project from this file: https://www.iatiregistry.org/dataset/unocha-cbpf-somalia-2018 but not being able to find it.

This suggests to me that we are not scanning all IATI data at the activity level for the code "SO" but instead are relying on the less reliable data in the file metadata.

**Comment by matmaxgeds** [comment]
Please also share the API query that you are using - I think it is: http://datastore.iatistandard.org/api/1/access/activity.xml?recipient-country=SO&stream=True - is that correct?

**Comment by raashidahmad** [comment]
@matmaxgeds you are right, that is cent per cent correct. I am sending the attached file which we are using. Please give it a review.

**Comment by raashidahmad** [comment]
@matmaxgeds Use this link please to reach the document we are using currently. 
https://drive.google.com/open?id=1TLhi93r1k87aBOfm2RaGEKzy0tFmesUQ

**Comment by raashidahmad** [comment]
@matmaxgeds I have just loaded the latest document through API, found it through search and i was able to search the project referenced in the thread. For example, see the attached preview. I guess latest IATI file was not available when you tried. We will write a background activity to load the latest IATI on daily basis.
![Capture](https://user-images.githubusercontent.com/2605356/55059854-d6754380-5091-11e9-85cb-ba38c351d338.PNG)

**Comment by matmaxgeds** [comment]
Thanks @Rashid - I can find them too now - sorry for needing to check again
