### ISSUE TITLE
Pagination only allowing 2 rows per page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#12]
In several places, the pagination of tables is only allowing 2 rows per page - this ideally needs adjusting to scale dynamically to the users screen - or as a temporary fix, expanding to perhaps 10 rows

**Comment by raashidahmad** [comment]
Done.

**Comment by matmaxgeds** [comment]
@raashidahmad, I assume this is closed but not pushed. If so, please only close things when you have pushed a new deployment otherwise I can't test them to check. Otherwise, I need to re-open this issue, as the same issue is here: http://104.140.103.166:7001/organizations

**Comment by raashidahmad** [comment]
Yes, the one mentioned in the comment was not done. Fixed.
