### ISSUE TITLE
Parse more IATI data

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#126]
We need to parse more information from IATI

- [ ] Dates
- [ ] Commitments and project budgets (from budget field, and transactions)
- [ ] Disbursements
- [ ] Locations
- [ ] Finance type - for when loan/grant is added
- [ ] ......and lots more

Note that not all data is stored at the activity level - some are set as defaults in the header of the XML file that the activity comes from.

And the parser also needs to extract information from the 'child' activities

**Comment by raashidahmad** [comment]
The proposed data is now being extracted. We may create a ticket in future for a specific situation.
