### ISSUE TITLE
Move 'view details' button

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#128]
This user needs this information when selecting the project, not when selecting funders - please move it from the 'add funders' screen to the 'select source projects' page - I know all this information is not pre-loaded at this stage - I guess this means a separate call

**Comment by matmaxgeds** [comment]
Can also be removed from the 'name/description' page

**Comment by raashidahmad** [comment]
Data entry layout updated. So it does not apply now.
