### ISSUE TITLE
Remove 'edit' from the 'view projects' table - and make name hyperlink

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#13]
The 'view projects' table is visible to all users - therefore there should not be any 'edit' feature - please remove it.

We can also replace the 'view' icon by making the project name a link to the project profile page - this will make more room by removing a column which we can use for something else.

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
The view icon (the blue eye logo) has not yet been removed so reopening until complete

**Comment by kndm** [comment]
View icon and actions column has been removed.
