### ISSUE TITLE
Ability to delete sector types

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#135]
Users need to be able to delete sector types:

1. Please add a 'delete button'
2. Can only happen when all sectors under the sector type are deleted - throw and error if this is not the case - with the text 'Please remove all sectors under this sector type before deleting'
3. Cannot delete default sector - error message 'The default sector type cannot be deleted, please make another sector type the default before deleting'

**Comment by raashidahmad** [comment]
Any sector types created by user can be edited or deleted provided with the condition to delete all the dependent sectors first.
