### ISSUE TITLE
IATI sector type - needs to link to IATI sector vocabulary

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#137]
The AIMS is importing all the sector types available in IATI in the background - this means that they will automatically be added in the 'sector types' list in the AIMS - and so the management users will not chose whether they are an 'IATI sector type' as this will be fixed. Instead, when they are imported from IATI - they default to the Vocabulary name given in IATI (we need to discuss how to figure this out in a sustainable way) - and then the user can adjust the name shown in the UI.

**Comment by matmaxgeds** [comment]
here is the codelists API to get the sector vocab name based on the vocab=3 etc that is in the xml: http://reference.iatistandard.org/203/codelists-guides/codelist-api/ - please setup a fallback to the vocab number if the codelist API breaks or doesn't return anything

**Comment by matmaxgeds** [comment]
and here is the kind of lookup we are doing: http://reference.iatistandard.org/203/codelists/SectorVocabulary/

**Comment by raashidahmad** [comment]
Scheduler is loading sectors on load and updating on daily basis.

**Comment by matmaxgeds** [comment]
Hi - this is great to hear - but I am only seeing the OECD CRS sectors being imported from IATI - there are others (e.g. vocab=10) present in the data that are not yet getting pulled in - so I am leaving it open until we are pulling in the others.

**Comment by raashidahmad** [comment]
This is now working as proposed.

**Comment by matmaxgeds** [comment]
Great - this is a cool thing!
