### ISSUE TITLE
Currency management page - need to list manually entered currencies seperately

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#156]
- [ ] Please can we have two tables - one for the automatically sourced ones, and a separate table for the manually entered currencies

- [ ] Please can we remove the option to delete/edit those currencies automatically imported from the exchange rate api

**Comment by matmaxgeds** [comment]
Hi - I am not seeing these two in the latest deployment - maybe I am doing something wrong

**Comment by raashidahmad** [comment]
Both are shown in different boxes now, however some tweaks are remaining against another ticket
