### ISSUE TITLE
sector mapping on input add sector

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#164]
The goal of the AIMS is to store all projects with a Somali sector - all the other sector types are just there to assist users entering data that comes from another sector type.

So when the sector is imported from IATI, or another AIMS project, we automatically select the sector type that it is coming from.

When it is a manual entry - we allow the user to select the sector type they want to enter.

In both cases, the UI then needs to show what default (in this case Somali) sector the input sector type will be stored as (and allow the user to adjust if they want to).

If there is no mapping, then the user should be asked to select a Somali sector.

The user then confirms the Somali sector that gets stored.

**Comment by raashidahmad** [comment]
Implemented on the project entry UI.

**Comment by matmaxgeds** [comment]
@raashidahmad this looks great - thanks
