### ISSUE TITLE
previously used IATI projects not available

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#167]
At the moment, it is not possible to use an IATI project for a second time - however, the first time, a user might have used just some of the data - and so they might want to use other parts of the data another time - at the moment, a previously used IATI project has it's button set to light green, and it cannot be clicked - instead, if an IATI project has already been used, please change the 'select' button to 'used elsewhere - use again' and allow it to be selected.

**Comment by raashidahmad** [comment]
This has been fixed now
