### ISSUE TITLE
Adjust currency management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#168]
Please:

1. Put the National Currency and Default currency as a separate box - i.e. each with a drop-down (with search) where the user can select the relevant currency for each one
2. Have a separate table for the manually added ones above the table showing all the automatically added ones
3. Label auto added currencies list as 'Currencies imported from exchange rate sources'

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
I don't see these yet in the current UI - did this change not get pushed? Please confirm that changes have been pushed to the testing server before closing the issues - or make a label called 'fixed' if you want to have a way to filter them out but before they have been pushed to the testing server

**Comment by raashidahmad** [comment]
Implemented

**Comment by matmaxgeds** [comment]
Nearly done. The default/national column is confusing. Please split it into two columns with clearer radio buttons (not coloured things) so there should be one column called "Set as Default" and the other called "Set as National"

**Comment by raashidahmad** [comment]
Implemented.
