### ISSUE TITLE
IATI data - active projects only

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#170]
It is probably still sensible to download all IATI data for Somalia, but when loading it in the first data entry screen, I think we can use only the 'active' projects - but that is a bit complex....

I think the easiest/safest way is to drop the following:

1. Projects with activity status (http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/activity-status/) of 4 or 5

AND

2. Projects where the last date (from the activity date field, or from any transaction) is more than 12 months old.

That still means that we will have projects that have not given an end date, and have not updated their activity status - but I think this is better than missing out on projects that we do need because of similar poor data quality.

**Comment by raashidahmad** [comment]
Implemented. I can see it slightly improved the load time,

**Comment by matmaxgeds** [comment]
@raashidahmad this was good progress - but I think we can do more - please exclude in the same way, any IATI project that has not had any transaction in the last 12 months. Hopefully that will finally chop the list down to size

**Comment by raashidahmad** [comment]
Done and presented.
