### ISSUE TITLE
Add full deployment instructions to Readme

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#172]
I moved this here from the other repo issues list as we are no longer using that one

**Comment by raashidahmad** [comment]
Added here: https://docs.google.com/document/d/1JdE6R9q7mtQtAT59T_N-01vnyWqlakyqFM1GJeiM-tc/edit?usp=sharing

**Comment by matmaxgeds** [comment]
@raashidahmad these instructions need to be pasted into the readme, or even better a seperate deployment file that is linked from the readme, so that they are available to anyone who visits the github site, not just those who have a link to the google doc.

Please make a new Deployment.md file and paste this information in - I guess there is an easy way to convert a google doc to a markdown file also.

**Comment by raashidahmad** [comment]
Done.

**Comment by matmaxgeds** [comment]
Please remove the management instructions e.g. Table 5.....this should just the information needed for deployment, not even for backup

**Comment by raashidahmad** [comment]
Updated.
