### ISSUE TITLE
Exchange rates tool - tweaks

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#175]
- [ ] the dropdown needs the exchange rate sources renaming - also these look like they are hardcoded? They should pull from the names given in the exchange rate management page
- [ ] the dropdown needs one option to be 'user supplied' - this allows the user to enter their own exchange rate in the box
- [ ] we need to say that the automatically selected rate from the different sources is based on the date given above and also what the 'nearest date' found in the data (and presented) actually is - so we can include a sentence after the automatically found rate box which says "Based on the date given, the closest matching data from this exchange rate source is from the INSERT DATE"

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
Hi Rashid - I renamed the exchange rates in the management page, but didn't see any change in the UI for the data entry users - maybe you haven't pushed this change?

I also don't see the 'user supplied' - it still says 'manual'

I don't see the text that is showing the date for the nearest rate found....

**Comment by raashidahmad** [comment]
Updated.
