### ISSUE TITLE
Project details not working

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#176]
The 'project detail' popups when using IATI data are not currently working

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
I don't see this yet - the button on IATI projects in the select source projects screen is still just for the 'description' - and even then is not showing it

**Comment by raashidahmad** [comment]
Now fixed.

**Comment by matmaxgeds** [comment]
@raashidahmad  - great that they are working again - I am moving this to a lower priority but when we have time, we need to think about showing more of the data that we parse from IATI here - I presume that the limited set of fields is because you are only using those fields that are already being pulled for the filters on this page? I guess this would mean doing a seperate request each time a user clicked 'view details' to also get e.g. the financial data, or the documents data from IATI

**Comment by matmaxgeds** [comment]
remainder of this covered elsewhere now in view details improvements
