### ISSUE TITLE
Disbursement dates added via widget

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#18]
Currently when adding a disbursement it asks for the year and month in seperate boxes, it would be quicker and more space efficient if this could be done in one step e.g. with a date picker widget - given the desire to hide the day input, you might have luck with the alt-format stuff here: http://api.jqueryui.com/datepicker/#option-altFormat (I am assuming you are using the standard jquery datepicker?

This will also be much easier than having a huge dropdown to pick dates from.

**Comment by matmaxgeds** [comment]
Here is a version that shows a month/year view that works with Angular: https://dalelotts.github.io/angular-bootstrap-datetimepicker/

**Comment by raashidahmad** [comment]
As decided, we have full date picker for dates now.
