### ISSUE TITLE
Adjust date format to UK/EUR style without dropping leading zero's

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#181]
For example, on the projects list, the dates are given as 5/29/2019 - this should be 29/05/2019 instead - i.e. DD/MM/YYYY not MM/DD/YYYY - and note that it is '05' not '5'.

**Comment by matmaxgeds** [comment]
Also, for the places where the date is written out, use "5th Oct 2019" not "5 Oct 19" - i.e. you need the 'th' and similar.

**Comment by matmaxgeds** [comment]
Also note that except for disbursements, we want mm-yyyy, as we do not need the day

**Comment by raashidahmad** [comment]
@matmaxgeds We now have financial years for data entry. In case of projects, last update date. We now have dates in UK style. Closing it.
