### ISSUE TITLE
Business rule - combining organisations - whether to ask users

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#183]
We need to decide whether to ask users when combining two organisations - we should at least be notifying them

**Comment by raashidahmad** [comment]
@matmaxgeds  When organizations are merged, email is sent to all the users of the projects. Is this covers the issue?

**Comment by matmaxgeds** [comment]
@raashidahmad - I think that is ok for now, but please leave this one open and I will shift the label to september

 I am worried that a management user might make a mistake (and it is not a reversible change), please can we send the users an email directing then to a notification where they can approve or reject - if one user from each organisation approves, then it is implemented, if anyone objects, it is not implemented. If no use does anything for two weeks then it is implemented?

**Comment by raashidahmad** [comment]
@matmaxgeds I was doing some paper work on this issue and have been stuck in some complexities because the current API that is written allows more than two organizations to be merged at a time. If the requirement is to allow more than two organizations to be merged, then it would not be feasible to go with Accept and Reject, as associating one request with many organizations and then in return associating may orgs with a user profile is too complex.
If the requirement is to allow only two organizations, then this can be implemented with the possibility that i edit the API or if required, will re-write API.

**Comment by matmaxgeds** [comment]
@raashidahmad - I understand the constraint. 

What happens if the organisations have no users? If that means that it just processes the merge immediately, than let's restrict merging to just two organisations at a time, also almost all the multi-organisation merges will happen for organisations with no registered users, therefore if they process immediately, they can be done one after the other.

Please inform the user doing the merge that an email has been sent to the affected users, and this should say when the merge will be implemented, if there are no users who reject it.

**Comment by raashidahmad** [comment]
@matmaxgeds While writing some APIs for this issue, i realized about a bottleneck in the requirements, please see below:
    a) If requests which are older two weeks, and while system merge the organization automatically, for every such action, a new name is required for the organization. How can the system assign a new name to such cases, please assist.

**Comment by matmaxgeds** [comment]
@raashidahmad - the user doing the merge should have provided the name when setting up the merge (submitted when the click is done) so I hope this is ok?

**Comment by raashidahmad** [comment]
@matmaxgeds Yes that sounds reasonable.

**Comment by raashidahmad** [comment]
This has been implemented this way:
1. If there are no users in the merging organizations, they will be merged straight away.
2. If any of the organizations have users in it, an email will be sent to all the users in that organization, a notification will be produced using AIMS. This notification can also be reached using the dropdown.
3. If any of the user approves the request, the merge will be implemented. If rejected, the merge will be discarded
4. If no action is taken, the scheduler after two weeks will automatically merge the organizations.
5. Email messages can be updated using email messages section
