### ISSUE TITLE
Project permissions / feature for user to add themself to another project

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#184]
Firstly - please can I confirm that users are unable to edit projects where their organisation is not a member?

Secondly - we need to handle what happens when a user needs to add data to projects where they didn't initially enter them. In the situation where their organisation was already added, that is not a problem as they already have the rights, so the problem is just in the situation where their organisation was not added.

In this case - on the data entry initial screen, instead of 'select' - the button should say 'add my organisation to this project, and forward the user to the project editing pages - but without the ability to edit the data, except for adding (or deleting) themselves as a funder (with an amount), or as an implementer. 

This action should then notify (including by email) the users from the other organisations that are present in that project, and request them to approve the user adding their organisation to the project - and when approved, the relevant data is written to the project - and therefore the new user (and their organisation) then has rights to edit the whole project (at which point they should be notified - including by email).

**Comment by raashidahmad** [comment]
Implemented.
