### ISSUE TITLE
Email management - 'Definition' >> 'Trigger'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#191]
Please tweak the text in the email management table

**Comment by matmaxgeds** [comment]
Hi Rashid - it still shows as 'Definition' at the moment - can you link to the PR that implemented this?

**Comment by raashidahmad** [comment]
Hi Matt, you are right, instead of changing the text i placed >> in front of the trimmed text. Will fix it.

**Comment by matmaxgeds** [comment]
Sorry - my use of '>>>' is unclear - I will do something else in future

**Comment by raashidahmad** [comment]
Popup already added to see the full text of the email. Closing as it seems fixed.
