### ISSUE TITLE
Email - add links

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#192]
e.g.:
Add a link to the AIMS login page when new user registered
Add a link to the project in email about new project created
and similar where necessary

**Comment by matmaxgeds** [comment]
Hi, the links need to go in the emails e.g. if your org has been added to a new project, the email can have a link to the project profile page for the project. Let's just do that one for now.

Matt

**Comment by raashidahmad** [comment]
Thanks, Implemented.
