### ISSUE TITLE
No error messages by default

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#194]
On the 'delete account' page the error message 'A password is required' comes up on the initial load of the page - it should only come up if attempting to submit without entering a new password

**Comment by matmaxgeds** [comment]
The same thing happens when you submit - you get two error messages from both fields

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
The same problem exists for the 'forgot password' page......it gives an error message 'enter a valid email address' right from page load, it should only do this after submit, and then it should say "This email address is not registered in the AIMS" if no match is found

**Comment by raashidahmad** [comment]
Fixed
