### ISSUE TITLE
If set start and end year of report to 2019 - no projects

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#196]
This setting should show all projects active at any point in 2019

**Comment by raashidahmad** [comment]
@matmaxgeds This query will be translated as select all the projects that has a starting year 2019 and ending year 2019. If this is supposed to show all the projects i am wondering how can we write this query.

"Show all the projects started in 2018 and ending ind 2019"

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - let me know if this is clearer?

Select project if start date < present date **and** if end date > present date

**Comment by raashidahmad** [comment]
@matmaxgeds  Thanks for the reply. On reports we are only selecting years, for example, starting year and ending year. With dates it is a different thing then.

**Comment by matmaxgeds** [comment]
@raashidahmad - aha, I forgot, I think it would be better with dates in addition to years - but also note that we should be using financial years, not calendar years - so that needs changing too - in which case we can have a multi-select dropdown and the formula would be: If selected FY is FY2018, then show all projects that were active at any point during FY2018 - i.e. 

select if
start date < FY2018 end date (which is 31.12.2019 in this case), 
AND 
end date > start date of FY i.e. 01.01.2018

**Comment by raashidahmad** [comment]
Fixed
