### ISSUE TITLE
Report - exchange rate picker should show resulting rate and date

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#197]
When selecting an exchange rate for the report - selecting an exchange rate source should show the date that the most recent rate is from, and the rate that is then used - it can do this with a dynamic sentence "data shown in SELECTED CURRENCY 3LETTER CODE converted from USD at a rate of 1 USD = XXX 3LETTERCODE"

**Comment by raashidahmad** [comment]
Fixed
