### ISSUE TITLE
A page for changing user password

### ISSUE THREAD

**Issue by somaliaims** [somaliaims/Somali-AIMSUI#2]
1. Must ask about the confirm password field, and at least length 4.

**Comment by matmaxgeds** [comment]
@raashidahmad @kndm please close these if completed

**Comment by raashidahmad** [comment]
@kndm good work overall. I was looking into the UI and found following things.
1. UI theme is little different from other forms in the AIMS. Please make the UI as it is in other areas.
2. It would be great if we keep the form development approach same. e.g. Template Driven

Please see the snapshots below to get the idea.

![loginform](https://user-images.githubusercontent.com/2605356/49780266-9763f200-fd2f-11e8-8c40-8c794717db19.PNG)

![password-reset](https://user-images.githubusercontent.com/2605356/49780273-a480e100-fd2f-11e8-92cd-3726be3e20bd.PNG)

**Comment by kndm** [comment]
I have updated the form styling as well as changed the components approach to be more template driven, please feel free to point at me if there is any specific changes you'd like implemented or a certain way in which you'd like to handle the templating :)

**Comment by raashidahmad** [comment]
Redesigned UI for this component to be compliant with coding strategy and UI look and feel. You may test it under Account Settings under Management.
