### ISSUE TITLE
No need to show lat/long for locations

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#20]
Lat/long values are not human readable, so no need to show these in the interface (when added locations to projects, and then showing project profiles) - we only need to show the location name at this stage.

After March, we will be adjusting the location element to meet the IATI standard elements - see here: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/location/

**Comment by raashidahmad** [comment]
Done
