### ISSUE TITLE
Reports - remove doughnut and radar chart types

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#201]
The doughnut is identical in content to the pie chart

The radar chart doesn't appear to make any sense as we only have one axis?

**Comment by mohamedgele22** [comment]
@matmaxgeds  we should let doughnut chart stay, pie chart should also be there as some people in my office already asking this type of chart.

**Comment by matmaxgeds** [comment]
@mohamedgele22 sure - I thought that the doughnut chart and the pie chart were basically the same thing so it was better to keep it simple and just pick one - but no objection to keeping the doughnut too - and great that you are tracking these!

**Comment by raashidahmad** [comment]
I assume we are keeping all chart types which are currently shown on the list.
