### ISSUE TITLE
Reports - the pie chart has a

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#202]
The background to the pie chart makes no sense! What are the axes doing? Please check a bit more thoroughly before pushing these things.

![Screenshot from 2019-06-10 18-58-43](https://user-images.githubusercontent.com/432153/59212115-d1646280-8bb1-11e9-8cb5-c990cfdc950e.png)

**Comment by raashidahmad** [comment]
Fixed
