### ISSUE TITLE
Excel export - autodownload

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#205]
For me, the excel export downloaded without asking me - is it possible to have it stimulate the system interface to ask me where I want to save it (or even just view it)?

**Comment by raashidahmad** [comment]
@matmaxgeds i would categorize it as the browser behavior. When i click on the report, it asks me where to save? Please view the image attached.

![ExcelAutoDownload](https://user-images.githubusercontent.com/2605356/60526086-11c68480-9d09-11e9-82f8-2754ecb08dee.PNG)
