### ISSUE TITLE
Exchange rates - the 'african bank' is always selecting the 0.91 rate whatever the currency selected

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#209]
it should not provide a rate for a currency that it does not have - and the best way to do this, would be that once the user has entered a currency, to only show the exchange rate options that have that currency available - this means triggering a check each time the currency field is updated - note that this should apply all across the AIMS i.e. funders and disbursements, and envelope

**Comment by raashidahmad** [comment]
Fixed. Currency list is updated according to selected source for exchange rates.
