### ISSUE TITLE
Add IATI management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#21]
Needs to include (also check Technical Requirements for others):

1 - Add links to other non-registry IATI files that need to be parsed
2 - Set country code - allow user to change country code from here:http://reference.iatistandard.org/203/codelists/Country/ - or add other country codes e.g. non compliant cose usage e.g. SOM?

**Comment by raashidahmad** [comment]
@matmaxgeds At the moment, according to our approach to download a file with all the data for a country, we need only a URL. I have designed this page, and you will see already set URL. I am closing this issue, In case, if any changes required, we may re-open this issue.

**Comment by matmaxgeds** [comment]
Thanks Rashid - let's leave this open until all the features are included.

I also assume for this that you have hardcoded 'SO' into the parsers etc? If so, please remember that we need this AIMS to be able to be used in other countries in future, and therefore nothing Somali specific should be hardcoded.

RE a non-registry IATI file - yes, just a link is needed, but perhaps we need a little more text e.g. 'Insert link here to have the AIMS check IATI files which are not available through the main IATI registry.

As one example, this may be the easiest way to import the Interim AIMS data that Gele has.

**Comment by matmaxgeds** [comment]
Just to be clear - the management page currently has a box for a link. Instead it needs:

1. A way to select the country code to use for the datastore query - requires downloading a list of current 2 letter ISO codes from IATI to chose from - see IATI codelist - plus a backup option of manual entry in case this breaks
2. A way to add any non datastore IATI xml files that should also be used (and there may be more than one)

**Comment by raashidahmad** [comment]
Thanks @matmaxgeds . Get a good idea about point 1. Will write a query about second point, when i will start work on it actually.

**Comment by matmaxgeds** [comment]
Here is the codelist for allowing the management users to select a country: http://reference.iatistandard.org/203/codelists/Country/

**Comment by raashidahmad** [comment]
This is now fixed and works this way:
1. A link is added to configuration file if there are no settings by default.
2. The settings page picks up the countries list from IATI file provided using the link above.
3. One can set any country and the AIMS will start picking up the data from that source.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad ,

This is good, but I think we are going to need a few tweaks as things have evolved since this issue was written 8 months ago, unfortunately because of the possibility that the datastore link might change, then we cannot use the country-code dropdown that was planned in May, as it would break if the base for the query changed. Please see attached file for my suggestion.
[IATI settings page.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4089538/IATI.settings.page.xlsx)

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for testing and highlighting the issue. The base URL is set from the configuration. Even if no country is set in these settings, the default country will be picked up from the URL.

**Comment by matmaxgeds** [comment]
@raashidahmad updated excel file attached after the call today
[IATI settings page.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4090287/IATI.settings.page.xlsx)

**Comment by raashidahmad** [comment]
@matmaxgeds I have now added the link for IATI stream, the user can set it using IATI Settings page. Please note, other options given for IATI sectors import are implemented under sector types. From the design point of view that is right and easy place.
