### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#210]
Please can we have the homepage/dashboard split into two sections - 3/4 for the introduction text, and the on the right had side - we can use the icons we had before (or similar)
- Active projects (those projects which are between their start and end date on the current day - clicking on it links to the projects list
- Organisations (the number of organisations) - clicking on it goes to the Envelope data report
- Users (the number of users)

**Comment by matmaxgeds** [comment]
@raashidahmad - please check the issues a bit more when developing features - as I spend time thinking about them, and it could save time doing revisions. However, in this case, your design is better I think, and not good to spend much more time on it now.

1. The Disbursements for need to be in Financial Years, and please confirm that 2019 is not hardcoded?
2. 'User accounts > 'Users'
3. Please remove the 'Register now' button as most users will not need to register and we don't want users registering for now reason - and I think your button is a little too tempting!

**Comment by raashidahmad** [comment]
@matmaxgeds you are right. I did not check this issue and followed a discussion during our meeting to put those icons back.
2019 is not hard coded. Will change other things as suggested

**Comment by raashidahmad** [comment]
Done
