### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#211]
We are going to need a contact form:

1. Help requests - sent to all management users
2. Requests for project information - sent to all users from the organisations involved in that project

In both cases, the email addresses that the form is being sent to should not be visible.

The fields should include:

- Your name
- Email (unless already logged in)
- Subject - append this text to "SomaliAIMS information request: "
- Your Message

**Comment by raashidahmad** [comment]
Done

**Comment by matmaxgeds** [comment]
Hi - please remove the contact form from the menu. It should be triggered (i.e. the user redirected to it) in two cases - 1) if a user requests help on the homepage, and 2) if a user wants to message the organisations behind project - and so depending on why it is triggered, we can adjust the subject line automatically.

The user does not need to see the automatic subject line - which for 1) is "_aimsname_ Help request: " and for 2) is "_aimsname_ Project information request: _projectname_". For the help request, we can then append additional information from the user submitted subject line e.g. if the user enters "help with registration", then the email subject received by management users should say "Help request: help with registration". For the project information request, we do not need an additional user added subject line.

Note that in all cases, the name of the AIMS (in this case 'Somali AIMS') is not hard coded, but should pull from the name set by the management users in the appropriate management page (needs creating).

**Comment by raashidahmad** [comment]
@matmaxgeds Through some other ticket. We have Suggest a change button to contact a project, and contact us form in general both.
