### ISSUE TITLE
Funders/Funding re-organisation/naming

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#212]
- [ ] Rename 'Date' >> 'Funding Date'
- [ ] Rename 'Amount' >> 'Funding amount'
- [ ] Rename 'Value' >> 'Funding value

Re-order the rows:
1. Funder
2. Funding type
3. Funding currency
4. Funding amount
5. Funding date
6. Funding exchange rate source

**Comment by raashidahmad** [comment]
I have re-organized it, however i had a restriction here, actually currency list is updated according to the ex rate source selected. So i have re-organized it this way:

1. Funder
2. Funding type
3. Ex. rate source
4. Funding currency
5. Ex. rate
6. Funding amount
7. Funding date

**Comment by matmaxgeds** [comment]
Hi, sorry for another change - please can we go for (note the sharing of lines - covered in another ticket, if you like you can put them on separate lines for now - but in the order below):

Funder [ ]
Funding date [ ] Funding type [ ]
Funding Amount [ ] Funding currency [ ]
Exchange rate source [ ] Exchange rate [ ]
Funding amount in USD [calculated]

(exchange rate source can be filtered based on the currency chosen - i.e. only show exchange rate sources that have the currency required - plus 'manual' - note another ticket is to rename 'manual' to 'user supplied')

**Comment by raashidahmad** [comment]
Hi Matt,
Okay will the required changes, just a slight change to the order i will propose which is to put the Ex rate source before currency. This will allow us the following:

1. When a source is selected. It will tell us what currencies to show. For example, in case of a African bank, we are sure, we will show only national, and default currencies, similarly, for open source we will show list of currencies.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad I am afraid that because the users will not know what currencies are available on which exchange rate source, and also because the currency is the fixed part, it is better to allow them to pick the currency and then we can filter the sources - I understand (and agree) that we need to find a way to filter the list of currencies down, but we will have to find another way to do it - perhaps via a 'most common' list of currencies that appear at the top, or making the currency selector searchable like for organisations - but that is for a different issue and can probably wait until Sept

**Comment by raashidahmad** [comment]
Fixed as proposed.
