### ISSUE TITLE
Disbursements in reports need to account for date filter

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#218]
In the reports, when the user has filtered by date, this is only showing projects which were active between those dates - and this also needs to apply to any disbursements in the reports - i.e. only show disbursements that took place between those dates - and only show the expected disbursements that are relevant for those dates.

**Comment by raashidahmad** [comment]
Done. The financial data is now filtered as per selected financial years

**Comment by matmaxgeds** [comment]
For this to make sense in the table, and the chart, we need to add the date range to the titles of the table and chart i.e. put "(FY2016-FY2021)" onto the end of the title, and also into the column headings for the actual and planned disbursements. In the example given above, if the user ran the report today, the actual disbursements would say 'Actual Disbursements (FY2016-19)" and the planned disbursements column would say "Planned disbursements (FY2019-21)" - i.e. the current FY is used as the split between the actual and planned disbursements.

**Comment by raashidahmad** [comment]
@matmaxgeds We have no dates and only financial years now in the new data model
