### ISSUE TITLE
Reports - all sectors/all locations by default

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#220]
On the reports, we need to have 'all' sectors/locations selected by default so that if the user doesn't change anything, they see data when they make the report. This should not require all the blue boxes which should only be used if adding some sectors/locations individually.

**Comment by raashidahmad** [comment]
@matmaxgeds i can see it working the way you are proposing. For example, All sectors, All organizations is selected when the report loads initially.

**Comment by raashidahmad** [comment]
@matmaxgeds i am closing this issue, as when dropdown has selected all organizations/sectors. It shows all the sectors/organizations without a filter.
