### ISSUE TITLE
Simplify notifications page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#228]
- [ ] All notifications on one tab - there is a risk users will not look at all tabs each time
- [ ] add a drop-down filter instead to look for just one notification type - make sure that the options are not hard coded - need to draw from the options under the notification API etc
- [ ] Instead of notification full text - just show notification type - plus any key info specific to that notification i.e. as currently....date, new organisation name, project wanting to join etc

There is also another ticket saying that there is no need to have a notification to management users of the registration of a new user, or a new organisation

**Comment by raashidahmad** [comment]
1. Discussed notification in the meetings.
2. Suggested to send notifications to manager/admin users.
3. Introduced drop down as suggested.

**Comment by matmaxgeds** [comment]
Low priority - but due to the dropdown, it is possible to get a notification, reach the page, and then not see the notification if it is filtered out. Probably need the dropdown to be an optional filter.

**Comment by matmaxgeds** [comment]
implemented
