### ISSUE TITLE
Combine the 'rename' and 'merge' organisations tabs

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#229]
We don't need two separate tabs here

- [ ] Use the interface from the 'merge organisations' tab to show and filter the list
- [ ] Remove the 'delete' organisation option - we cannot do this as there will be projects and users associated with it, and we have no business rules to handle this - we just need 'merge'
- [ ] Have two buttons in the top right - one for 'rename', and another for 'merge'
- [ ] If just one organisation is selected, then the button for 'rename' becomes active (shift from dull colour to bright version of colour) and if more than one organisation is selected then 'merge' button goes bright and becomes active

**Comment by matmaxgeds** [comment]
I am also getting an error when merging organisations.....
![Screenshot from 2019-07-01 16-41-16](https://user-images.githubusercontent.com/432153/60445252-22023500-9c1f-11e9-81df-b2b067bb3d13.png)

**Comment by raashidahmad** [comment]
Fixed
