### ISSUE TITLE
Custom fields - add value - has character limit - needs to be shown

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#230]
On the add custom field UI, there is a character limit on the 'enter value' field - this needs to be noted as it is with the 'field title'

**Comment by matmaxgeds** [comment]
Please also adjust the title of 'enter value' to 'Field option' - also adjusting 'add value' to 'add option'

**Comment by raashidahmad** [comment]
Already fixed.
