### ISSUE TITLE
Error pages - 404 and similar

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#231]
We need a proper 404 (and similar) page that says.

"Sorry, we could not find the page that you are looking for. Click <link ahref etc>here</link> to return to the homepage and try the view project or reports menu options.

"Alternatively, the link you followed may require you to log in, you can log in (and register) by clicking <link>here</link>.

Alternatively, you can contact us for help or to report an issue through the email form <link>here</link>"

For example, if a link encoded on one of the reports does not work out this might happen, or

**Comment by matmaxgeds** [comment]
Current redirect when following a link to a page appears to be to the projects list - this should be replaced by the appropriate error page - e.g. if it is following a link that requires the user to be logged in, then I guess that is a 401 page - we don't need them all, but we do need a few basic ones, and then something to catch whatever these miss and just do a redirect to the homepage (not the projects list)

**Comment by raashidahmad** [comment]
404 page added for now

**Comment by matmaxgeds** [comment]
Great, leaving open until we also have the other likely ones:
- [ ] 401
- [ ] 400
- [ ] 403
- [ ] 500
