### ISSUE TITLE
Management page for financial years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#233]
This is a very simple management page - where the managers need to set the start and end month/day for the financial year - which we will then use to general financial years in the UI.

If is the same as calendar years (or within 5 days) then use FY+year i.e. FY2019
or
if it is mid-year, then use FY+first year YYYY / second year YY i.e. FY2019/20

**Comment by raashidahmad** [comment]
@matmaxgeds this has been implemented and works the following way:
If dates are between 25 Dec, year, and 05 Jan, year. This will pickup the year from 25 Dec and will generate it. In all other cases, it will cover the range of years for the provided dates.
