### ISSUE TITLE
UI margins need rethinking

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#237]
At the moment we are wasting a lot of UI space with excessive margins which go multiple layers deep - see screenshots for three different ones all padding the data entry area. These need an overall approach and removing carefully - I think that means deciding which of the <div> elements really needs a margin, and which do not in order for it to work - i.e. I suspect the column ones do not if we are padding everything inside them already.

![Screenshot from 2019-07-03 17-37-05](https://user-images.githubusercontent.com/432153/60724088-cba23880-9f35-11e9-8bb6-0e48993ca0b5.png)
![Screenshot from 2019-07-03 17-39-18](https://user-images.githubusercontent.com/432153/60724091-ce049280-9f35-11e9-806f-d4ba2f7f2ae8.png)
![Screenshot from 2019-07-03 17-40-13](https://user-images.githubusercontent.com/432153/60724094-cf35bf80-9f35-11e9-88d4-2c7e6de7d124.png)

**Comment by raashidahmad** [comment]
@matmaxgeds not applicable, belongs to the Old UI layout for data entry.
