### ISSUE TITLE
Line spacing needs rethinking

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#238]
We are wasting space with line spacing - pictures show a before and after of what can be achieved by tweaking this

![Screenshot from 2019-07-03 17-48-03](https://user-images.githubusercontent.com/432153/60724198-0b692000-9f36-11e9-83e5-a9ffefa5e346.png)
![Screenshot from 2019-07-03 17-48-22](https://user-images.githubusercontent.com/432153/60724200-0b692000-9f36-11e9-830b-a49cd6963636.png)

**Comment by raashidahmad** [comment]
Belongs to old form layout, so closing it.
