### ISSUE TITLE
Form layout improvements

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#241]
We need to save space/clean up the forms - see for example: https://www.createchsol.com/forms-without-tables/ or for example: https://experience.sap.com/fiori-design-web/wp-content/uploads/sites/5/2019/01/17-Form-element_Belize.png

1. Put names to the left of fields instead of above them - right justified
2. Where fields are short e.g. dates, put two on one line

**Comment by raashidahmad** [comment]
We have updated the form to new layout. Closing it to focus on open.

**Comment by matmaxgeds** [comment]
adding to 'not delivering' so if there is time in the future, this can be worked on
