### ISSUE TITLE
Reduce fonts, colours, sizes etc

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#242]
See screenshot - this is confusing, there are about 10 different font variations on this page, in some cases, even multiple ones in one sentence e.g. "Projects by locations list (Currency: United States Dollar)" - I think this can be significantly reduced to just 4 variations and only one size:

- One font/size for the main text i.e. data in tables
- Same font/size in bold for table titles
- Same font (italicised, maybe coloured) for additional information
- Same font/size in white for using on coloured backgrounds e.g. menu, buttons etc

**Comment by matmaxgeds** [comment]
I suggest that this selected size is the rem=1.0 variation

**Comment by raashidahmad** [comment]
Need to review and discuss.

**Comment by matmaxgeds** [comment]
Adding to 'not delivering' - as it not a functional blocker
