### ISSUE TITLE
Report table calculations check

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#244]
Hi Rashid - we need to dedicate some time to understanding what the tables are showing in terms of numbers. I have attached an example project that I entered into the AIMS 'matt disbursements test' and an example table output.
[Test report calculations.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3363492/Test.report.calculations.pdf)
[test report project.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3363496/test.report.project.pdf)

First steps:
1. The project is worth 5 million USD (everything is in USD to keep things simple)
2. The funds are split 50% to Puntland, and 25% each to Somaliland and Jubaland
3. That means that whatever the report shows, the numbers for Somaliland and Jubaland should be identical.....but they are not
4. The project value for Puntland should be 2.5 million USD (50% of the total project value) - but the report shows it to be 1.25 million USD?
5. I guess start by fixing that, and then let's see if that solves the other issues - but the next step will be checking that the actual and planned disbursements make sense - they should have the same splits

**Comment by raashidahmad** [comment]
Fix, please review and if you find any discrepancies, let me know please.
