### ISSUE TITLE
IATI parsing not using 'default currency'?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#245]
There is an IATI project called "Joint Programme On Local Governance And Decentralised Service Delivery, Un-Jplg  (Phase Ii)-Dfid" - and the original data is here: http://d-portal.org/q.xml?aid=41120-2369

If you try to use the transactions from this project, the UI does not give a currency - this is because the currency is not given in the transaction element, but the currency is included in the xml as a default currency in the activity header - in this case it is USD - so the parser needs to check for this and apply it to all transactions where a currency is not given.

**Comment by raashidahmad** [comment]
With new data model and layout, currency is shown for both AIMS and IATI projects, and default currency is extracted from IATI for a project.
