### ISSUE TITLE
Disbursements table on data entry not update if default currency changes

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#248]
It seems like parts of the calculation of this table is skipping the default currency - hence when I changed the default currency (to AOA), the table broke as it said AOA but the rates and amounts did not change
![Screenshot from 2019-07-05 22-06-34](https://user-images.githubusercontent.com/432153/60743514-4ab56200-9f72-11e9-80b3-987ae8ecbb1b.png)

**Comment by matmaxgeds** [comment]
from @raashidahmad: I was working on the ticket #248 and found few complexities with its implementation. Sharing below:

1. We are storing exchange rates against the default currency in the database. For example, in a project I added two funder entries having default currency as USD and funding currency say AED, so the exchange rate 3.47 will be saved in the database.
2. Now, the admin updated the default currency to AOA, and funding currency is AED, the exchange rate will be different for AOA in this case. So for the same funding currency different ex rates will be stored in the database.
3. I can use a formula on the UI to show these currencies in some other currency provided that default currency remains same across all the records.

There are solutions to this feature but in return we will have do the following:
 
1. Change the data model, and always keep default currency, its exchange rate, and exchange rate of funding currency with the records. Similarly, for disbursements.
2. We are also allowing users to use different exchange rate sources, so that would also require to input exchange rates with respect to default currency time to time.
3. We will have to implement complex formulas in all the UI sections where we are showing financials with different default currencies.

I can foresee, there will be more complexities, if we take exchange rates against one default currency, change default currency, and then do calculations for old exchange rates with respect to new default currency. Imagining, if I a user changes default currency 3, 4 times, it will create more edge cases.

**Comment by matmaxgeds** [comment]
from @matmaxgeds:

Sorry for the slow reply, it takes time to think about.

1. This is not a priority to fix for the testing - I have set it back to USD for now and we can work on this in August - I have also adjusted the github issue to Sept
2. Swapping the default currency will be very rare - so we should treat it appropriately
3. The default currency will always be the same for all projects at any one point in time
4. I think the easiest way to handle this is that when the default currency is changed we ask the management user who does the change to pick an exchange rate (using the normal picker) between the old default currency and the new one
5. We then need a service to loop through each financing/disbursement and adjust the exchange rate that is stored to the one that is the original xrate * management xrate, and mark it as user supplied
6. The question for me, is whether we need to ask permission to do this - I think it is probably best as a notification to all users with projects, that the default currency has been changed, and all exchange rates have been updated to the new default currency using the exchange rates of XX between the old and new default currencies supplied by the management user.

Does that sound reasonable - I think that way we don't have to store any new information, and it just tweaks the UI for changing the default currency - plus introduces the script to loop through and make the changes.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for taking time to think about the solution. I think among the possible on my mind, your solution seems more reasonable to me.

**Comment by matmaxgeds** [comment]
Need to check what happens with new disbursements model

**Comment by raashidahmad** [comment]
Now we have different layout and data model. This issue relates to old data entry layout. Closing it.
