### ISSUE TITLE
Add delete project functionality

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#251]
In very rare situations we might need to delete a project - this should be a request from a user involved in a project, to a management user to delete it. This should:

1. Notify all other orgs in that project who can cancel the deletion request
2. Notify management users who can 'delete' or 'cancel request'
3. A management user cannot make a delete request and then act on their own request to do the deletion

**Comment by raashidahmad** [comment]
Added. Presented for review. Closing so it may be noticed.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad please can you confirm that only users from organisations who are members of a project can see the delete button?

**Comment by raashidahmad** [comment]
Hi @matmaxgeds , Correct, i tested it with a new user account, and it worked for me as expected.
