### ISSUE TITLE
Move the 'next' button into the sub-menu part so is always visible

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#254]
The 'next' button during data entry should be in the same part of the page as the 'tabs' for the different data entry pages - this way it will stay in the same place for all the pages, not get lost when scrolling etc

**Comment by raashidahmad** [comment]
This is related to old data entry layout. So closing it.

**Comment by matmaxgeds** [comment]
@raashidahmad I am afraid this needs re-opening. At the moment, there are different save buttons all in different places on each page, and no 'next' button for the user to easily transition to the next page. Please replace all the seperate 'Save' buttons with a single 'next' button on each data entry page. It should be in the top right, in the same place each time. Thanks, and I know that this is a slightly increased risk of data loss without the seperate buttons.

**Comment by raashidahmad** [comment]
@matmaxgeds i understand your point of one button, but there are complexities with this option. A single save button will be inputting data into many tables, creating complex conditions. Also we have inpdenpendent APIs for each section. We can discuss this in detail for the upcoming meeting.

**Comment by raashidahmad** [comment]
Implemented.
