### ISSUE TITLE
Reports need comma's and alignment of amounts etc in the table

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#257]
At the moment, there are lots of places in the AIMS where the numbers are not formatted as numbers e.g. 1233446.35 should be 1,233,446 - only exchange rates need decimal places

Also - numbers should be right justified in their columns so that they can be read more easily i.e. it is easy to see which are the bigger ones as they extend further.

**Comment by matmaxgeds** [comment]
@raashidahmad can this also be done for the numbers (axis labels, on-hover data labels) in the charts? I also downgraded the priority

**Comment by raashidahmad** [comment]
@matmaxgeds numbers formatted on charts.

**Comment by matmaxgeds** [comment]
@raashidahmad please right-justify all numbers so that they line up i.e. the last digit is always in line, that way it is easier to see which number is bigger at a glance

**Comment by raashidahmad** [comment]
Implemented on reports.
