### ISSUE TITLE
Time report

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#267]
Hi @raashidahmad @mohamedgele22 - here is some more detail about how to make the 'over time' report that Gele shared: ![image](https://user-images.githubusercontent.com/432153/60888650-9e1bfe80-a257-11e9-80cc-fc8f0c6ab0c8.png)

Report title "Time series report"
[Time series report.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3383326/Time.series.report.xlsx)

**Comment by matmaxgeds** [comment]
See the excel file for the basics - is like the other ones, just with years rather than sector or locations

**Comment by raashidahmad** [comment]
Done

**Comment by matmaxgeds** [comment]
@raashidahmad - I think I didn't provide enough information - if you look at the current table in the time trend report, it makes no sense. I.e. in 2011, it gives project value, actual disbursements and expected disbursements - but there cannot be any expected disbursements in a past year e.g. 2010, but this is what the report shows.

Please can you:
- [ ] Use the tree-table library so that the top level is a year, and the sub-level are the projects
- [ ] Change the columns so that there are just two data columns (actual disbursements, expected disbursements) - and therefore the chart becomes like the budget report chart.

**Comment by raashidahmad** [comment]
@matmaxgeds  presented for review. Closing it, and may open it again for any fixes.

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad 

- [ ] Remove the project value column
- [ ] Make the tree table like the budget report......where the summary/total when collapsed is not in the text, but is in the normal place in the columns

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
@raashidahmad :)
