### ISSUE TITLE
When adding an organisation in data entry initial page - data doesn't refresh

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#268]
Hi,

I filtered the data entry project selector by organisation, and that worked fine, I got only that organisations projects, I then added a second organisation but nothing happened - it did not trigger an update of the list of available projects....it needs to.

This lack of a trigger seems to be for many of the filters - a quick fix would be an 'update' button in case the user wants to make multiple changes to the filters.

**Comment by raashidahmad** [comment]
Hi @matmaxgeds ,

Please help me understanding this issue.

1. You added organization through data entry to a project.
2. I assume you kept the find projects page open while added the organization through some other screen. Is this correct what i assumed?

Or

1. You are changing the filters through checkboxes and they are not working for you?

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - it is to do with the filters, I was trying to find some projects using the filters, so I added an organisation to the filters and it updated the list of source projects (IATI and AIMS) but I saw that not all the projects I was looking for were there, so then I added a second organisation to the organisation filter, but then the list of source projects did not update, and I couldn't see how to make it update.

**Comment by raashidahmad** [comment]
Thank you @matmaxgeds for the explanation. It means there is an issue with filters. It must update without an update button. I will look into it, sometimes all the listed projects have both the organizations, that is why you do not see an update to the list.
For example, there may be many organizations as funders or implementer under a project. The view detail button may help you. The local version updated for me but i need to test with the live version as there is more data there. Will get back to you once fixed.

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad  - unfortunately I can't test as there are no longer any organisations in the test server....please can you add the organisations that are in use in the projects in the test server? There shouldn't be too many I think.

**Comment by raashidahmad** [comment]
@matmaxgeds please test it as we have organizations now.
