### ISSUE TITLE
Report years selection

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#27]
1) Users need to be able to select multiple years for each report

2) available years need to be based on the projects in the AIMS, not a hard-coded list - please remove all these instances of hard-coded list items in the AIMS

**Comment by raashidahmad** [comment]
@matmaxgeds Can you please help me with visual look and feel? How it will look like, multiple years, such as 2015, 2016? Is that correct?

**Comment by matmaxgeds** [comment]
@raashidahmad correct, a user may want a report covering 2016, 2017 and 2018.
By years, I should have said 'Financial Years' - somewhere in the AIMS settings, we are keeping a variable which records the financial year. In the case of Somalia, The Financial year is January to December, so in this case the dropdown menu should show FY2016, FY 2017, FY2018 etc, and then when the user selects them, the UI will be able to lookup the FY>year/month conversion and see that this means projects from January 2016 to December 2018 should be included.

**Comment by raashidahmad** [comment]
@matmaxgeds Got the idea. Thanks

**Comment by raashidahmad** [comment]
Years on this report, now coming from DB. I will design UI for financial years in future.
