### ISSUE TITLE
Rename 'yearly projects report' to 'Time trend report'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#271]

**Comment by matmaxgeds** [comment]
Please have some consistency......the same report has 3 different names visible on this screen!
1. Project yearly report
2. Projects yearly report
3. Yearly projects report

Please stop hard coding everything and in each case pull the name of the report from the same place.

Please apply this to all the reports, and also in general as good practice.

![Screenshot from 2019-07-16 17-45-26](https://user-images.githubusercontent.com/432153/61309128-ead07e00-a7f1-11e9-8bdf-20ecc70fd634.png)

**Comment by raashidahmad** [comment]
Fixed
