### ISSUE TITLE
Budget report adjustments

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#272]
Hi, see attached excel sheet for a template to adjust the budget report
[Budget report.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3399134/Budget.report.xlsx)

The main UI thing is that everything needs to be laid out in rows so that it is easy to read (the new table style should do this).

For the chart, you can use the same as the 'time trend' one.

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for the work on this

1. Is there any way that we can indicate to the users that if they click on a row they will get the additional detail? I.e. most of the tree table libraries have an indicator that a row can be expanded?
2. Please rename the chart bars.... 'Total Disbursements' >> 'Actual disbursements' and Total Expected Disbursements' >> 'Expected Disbursements'

**Comment by matmaxgeds** [comment]
@raashidahmad  - just need to rename 'Expected disbursements' to 'Planned disbursements' (in both the chart and the table), and then we can close this

**Comment by raashidahmad** [comment]
Done :)
