### ISSUE TITLE
Envelope data entry and report adjustments

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#273]
Placeholder @matmaxgeds

**Comment by matmaxgeds** [comment]
Hi Rashid - here is an updated template for the envelope data entry and report - please only reproduce the light green background parts - the rest is so you can see how I have worked it all out from the basic data. It looks more complex than it is - it is the same formulas as the budget data, just a lot of times.
[Third draft of envelope table.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3414026/Third.draft.of.envelope.table.xlsx)

**Comment by matmaxgeds** [comment]
Hi @raashidahmad here is the much simplified envelope data entry and report mockup:

https://docs.google.com/spreadsheets/d/1Zlw7B-TMwks7inZEae2UvhwW6jzsHZnrOI38kIkGq4o/edit#gid=0

**Comment by raashidahmad** [comment]
Hi @matmaxgeds ,Thank you for the mockup, will come up with the queries, when actually start work.

**Comment by raashidahmad** [comment]
Done
