### ISSUE TITLE
When deleting a sector it is not deleting from the sector list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#274]
Hi, I deleted a sector ("capacity building"), but it has not disappeared from the list of sectors (but all it's old projects have been moved) to the replacement sector.

It is also still appearing in the dropdown menu for reports

**Comment by raashidahmad** [comment]
Hi,
Sorry for any confusion the way it is working right now. May be i misunderstood the requirements earlier. This feature works either to delete a sector straightaway or map affected projects to some other sector. Please see the message on the screen. It works this way.

1. If select another sector for mapping it will not delete.
2. If you do not select another sector for mapping, it will delete straightaway

This means you are proposing it to be deleted in both the cases. Am i correct.

![DeleteSector](https://user-images.githubusercontent.com/2605356/61373636-c4731700-a8b3-11e9-85e5-ee2d27acc864.PNG)

**Comment by matmaxgeds** [comment]
Hi @raashidahmad thanks for figuring out the issue, yes, the selector should delete in both cases, whether the user has assigned a sector to transfer the projects using the one about to be deleted to, or not.

**Comment by matmaxgeds** [comment]
For now, I will just do the action twice each time, once to re-assign the projects and again to delete the sector

**Comment by raashidahmad** [comment]
It is deleting now.
