### ISSUE TITLE
Save openexchangerates key in UI

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#285]
Matt to think about

The management users may easily lose the API key, the email account and the password that they used to setup openexchangerates (especially as the management users may change) - so please store these three in a visible way in the management page for openexchange rates - i.e. have the user enter all three

**Comment by raashidahmad** [comment]
@matmaxgeds Account details are not required, to work with open exchange only key is required. If an Admin is changed, he can register his self on OpenExchange, get a token, and save it in the DB. The API will work.
Closing it for now, we may talk about this further if there are any concerns.
