### ISSUE TITLE
Organisations only refers to user entered organisations

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#288]
This means please remove the IATI organisation names off the 'organisations' management page - unless they get imported (at which point a copy of the organisation name' becomes a user added organisation.

The IATI sourced organisation names are only needed to search the IATI data, and we will separate them out (from the user organisation which are used to search the AIMS projects) into a separate filter on the source data page.

**Comment by raashidahmad** [comment]
1. Management page now only shows organization entered by user or organizations imported from Excel sheet.
2. On project entry shown only user created or imported from Excel are shown as Funder or Implementer.
3. On user registration page all the organizations are shown to be selected by the user (IATI + User entered.)

**Comment by matmaxgeds** [comment]
Please remove the IATI organisations from the registration page as well

**Comment by raashidahmad** [comment]
Done
