### ISSUE TITLE
If adding a project as an implementer, the project can save without your organisation being added

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#289]
If you add a project as an implementer (i.e. without adding yourself as a funder) the project can be saved without you adding your organisation as an implementer - so then you have added a project that you do not have the rights to edit!

Matt to think how to solve!

**Comment by matmaxgeds** [comment]
We need to not save a project unless the user has added their organisation somewhere

**Comment by raashidahmad** [comment]
@matmaxgeds If a user is not registered, he/she cannot add a project. A user always has an organization.

**Comment by matmaxgeds** [comment]
agreed, this is for registered users, who add a project, but without adding their organisation as either a funder or an implementer (by mistake, or on purpose) i.e. adding other organisations as funders or implementers, and so lock themselves out of their own project!

**Comment by matmaxgeds** [comment]
@raashidahmad do you have all your need here to get this one solved? We need a check before save/next on the first data entry screen that that user's organisation is added as either a funder or an implementer.

**Comment by raashidahmad** [comment]
@matmaxgeds Sorry on this, i was looking at the title only and not at the comments. I am clear now about this.

**Comment by raashidahmad** [comment]
Implemented
