### ISSUE TITLE
Sector report - disbursements planned wrong

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#290]
See attached screenshot - there are no date filters, or any sector filters etc - which means that the 'planned disbursements should be: planned disbursements = project value - total actual disbursements - in this case USD 9,000,000.

Maybe we should discuss what is happening here to get the 310,345 figure currently given for planned disbursements.

![Screenshot from 2019-07-21 17-10-55](https://user-images.githubusercontent.com/432153/61593051-d5d16180-abda-11e9-8fb2-a024f9bfce3a.png)

**Comment by raashidahmad** [comment]
@matmaxgeds the formula which i am using is (projectValue - actualDisbursements) / yearsLeft. Is that not a correct formula?

**Comment by matmaxgeds** [comment]
@raashidahmad - I will add a second comment to explain the confusion between us, but for now, please use the simple formula: planned disbursements = total value - actual disbursements so far

**Comment by raashidahmad** [comment]
@matmaxgeds Okay doing that, will let you know once updated.

**Comment by matmaxgeds** [comment]
Longer explanation - the original idea was for the planned disbursements column to respond to the date filter and show the planned disbursements left within the period set by the date filter - therefore the 'months left' part therefore gives the planned disbursements for a single month which you need to multiply the number of remaining months to get the full figure. The number of remaining months would depend upon the dates filtered for.

However, at this stage I am going to apply our 'simpler is better' idea as there are more urgent priorities so we can use the simple formula here and leave the date filter to only apply to which projects are included in the report.

**Comment by raashidahmad** [comment]
Thanks for the explanation Matt.

**Comment by raashidahmad** [comment]
Fixed
