### ISSUE TITLE
management user shows notifications alert but no notifications

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#292]
I refreshed several times but couldn't get either an issue to show or the notification to disappear - it was linked to requesting permissions I think
![Screenshot from 2019-07-21 17-44-32](https://user-images.githubusercontent.com/432153/61593454-fbad3500-abdf-11e9-9cc1-f7bff55e1ef0.png)

**Comment by raashidahmad** [comment]
Can you please check the another option in the dropdown? For example project permission requests? You will find there.

**Comment by matmaxgeds** [comment]
@raashidahmad sorry - I had forgotten about the dropdown - closing

**Comment by raashidahmad** [comment]
@matmaxgeds thanks
