### ISSUE TITLE
Users can add locations that are not available in the locations list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#295]
When adding a location from IATI, it adds the location name directly - but for locations, they need to select one from the official list of locations, and should have no choice to import one of their own at this stage.

**Comment by raashidahmad** [comment]
@matmaxgeds I wonder what to present to user in case if user can only select from AIMS locations list. For example, the data provided by IATI is:

1. location
2. Co-ordinate information
No percentage information is provided. Please suggest.

**Comment by matmaxgeds** [comment]
hi @raashidahmad thanks for these questions - I think the simplest way (because we have to prioritise your time) is to set it up so that we just show the location names that are available in IATI (ignoring the coordinates) and there is no '>>>' import button for the IATI source data, i.e. it just provides a guide to them to know what locations to select from the AIMS dropdown list in case they don't know the project well.

**Comment by raashidahmad** [comment]
Thank you @matmaxgeds for the answer, helpful.

**Comment by raashidahmad** [comment]
Fixed
