### ISSUE TITLE
When there are more than one disbursements from IATI - can only import one

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#297]
See screenshot - it is impossible to import the first disbursement - clicking it's button always gives you the second disbursement
![Screenshot from 2019-07-21 19-37-32](https://user-images.githubusercontent.com/432153/61594699-04593780-abef-11e9-8cbc-33c964dfb95f.png)

**Comment by raashidahmad** [comment]
Has taken this issue on the list to fix for testing.

**Comment by raashidahmad** [comment]
Fixed
