### ISSUE TITLE
Sector mapping data entry adjustments

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#299]
Hi - quite a big tweak needed to the import of sector data, and the mappings

At the moment, when a sector is mapped, and a user imports that sector from IATI, then it is not possible to add a second sector, to adjust the amounts, to delete it and add a different sector, to change the mapping.

We need to make IATI import of data, compatible with manual import at the same time.

This also needs checking for e.g. the financials and the organisations.

**Comment by raashidahmad** [comment]
We now have sector types while inserting a sector under project sectors. This issue has been reported before the data model changes, and UI. Just writing the comments so that we can close it later.

**Comment by matmaxgeds** [comment]
closing as if it reoccurs will raise a new issue
