### ISSUE TITLE
Email settings page.

### ISSUE THREAD

**Issue by somaliaims** [somaliaims/Somali-AIMSUI#3]
The settings must include the following fields:
"Host": "",
"Port": "",
"Username": "",
"Password": "",
"AdminEmail": ""

**Comment by matmaxgeds** [comment]
@raashidahmad this requires MoPIED to run a mailserver - we should also prepare the aims to be able to connect to a mail service e.g. mailgun, sendgrid or similar. Potentially even Gmail. So this page should allow the user to select the email service type e.g. 'mailserver', 'gmail' etc......of course this is also on the list for March

**Comment by raashidahmad** [comment]
@matmaxgeds I have implemented this feature using a test google SMTP account. You may test this feature under SMTP Settings.
