### ISSUE TITLE
Remove all edit options from 'Project Detail' page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#30]
The 'view projects' >> 'project details' page is accessible to all users - therefore there should not be any options to edit projects via this screen - at the moment, even when I am logged out, it still allows me to delete sectors etc.

I suggest that rather than doing user based permissions, the 'view projects' pages have no edit actions at all. This is also because we want to force all project editing to happen through the main data editing interface.

**Comment by raashidahmad** [comment]
Done.
