### ISSUE TITLE
Advanced search on project list doesn't work

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#300]
I can't get the advanced search to have any result on the list and it freezes

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
- [ ] The FY search is not working properly - it should return any projects that are active in the FY range entered by the user - in the example screenshotted, setting the year range as 2011 to 2015 should result in showing two projects (one that starts in 2014, one that starts in 2015) - at the moment, none are shown. As a reminder, setting the date range, should show any project that either starts or finishes between the user set dates.
- [ ] The date filter needs to either be changed to be for financial years
- [ ] The FY search should not require the user to enter both a start and an end date.

**Comment by raashidahmad** [comment]
Now with the new model, we have only starting and ending financial years. Search is working now.

**Comment by matmaxgeds** [comment]
@raashidahmad great, nearly there:

- [ ] Make the advanced search the default, no need to hide it behind the extra button
- [ ] Therefore remove the second project name search box (there are two identical ones visible when advanced search is selected
- [ ] The name search can be like the organisations search i.e. filters existing project names as the user types
- [ ] Add an additional search box to search project descriptions
- [ ] There needs to be a 'reset filters' button
- [ ] like all other sets of filters, there need to be two search dropdowns to make it work, one to set the level (parent, sub-sector etc) and the a second one to select the exact sector

**Comment by raashidahmad** [comment]
Proposed changes implemented.
