### ISSUE TITLE
Chart in budget report are not updating when the currency is changed to SOS

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#302]
The charts are staying in USD

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
@raashidahmad Has this been pushed? I just tested it and I couldn't see the chart update when the reporting currency was changed?

**Comment by raashidahmad** [comment]
@matmaxgeds I just tested it here and i can see it is changing the values while changing the currency to SOS. Please check it here, please refresh your browser, probably ctrl + f5 will work.
http://104.140.103.166/budget-report

Let me know if you encounter any issue.

**Comment by matmaxgeds** [comment]
thanks @raashidahmad - see the screenshots - when I change the report currency, the numbers in the table change but the numbers on the chart axes do not.
![Screenshot from 2019-07-26 21-00-35](https://user-images.githubusercontent.com/432153/61975087-7b743e80-afe8-11e9-8244-4d18e8b72237.png)
![Screenshot from 2019-07-26 21-00-47](https://user-images.githubusercontent.com/432153/61975088-7c0cd500-afe8-11e9-8733-6d3754035970.png)

**Comment by raashidahmad** [comment]
@matmaxgeds thank you for sending me the snapshot, it guided me to understand that the issue is on the other reports not on budget report. I was checking the budget report. Noted, will rectify this issue.
Thanks

**Comment by matmaxgeds** [comment]
@raashidahmad sorry for not making that clear
