### ISSUE TITLE
For reports - where actual disbursements = zero, planned disbursements is also zero?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#304]
If actual disbursements are zero, planned disbursements should equal the project value

**Comment by raashidahmad** [comment]
Fixed. Please review and let me know if i understood this well.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad this is nearly working - see the screenshot - it looks good for all rows except those where there is a project value recorded, but not any disbursements - see Matt test project 3 and JM test 1 - in those rows (just like the other ones) the planned disbursements = project value - actual disbursements......so in those two rows, planned disbursements = project value - 0.......but that part seems not to be working?

![Screenshot from 2019-08-11 12-11-02](https://user-images.githubusercontent.com/432153/62833116-29aaf580-bc31-11e9-9768-6570884e0b3d.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for testing. Can you please test it on the development server using port 7001? I assumed we will not update testing server after launch until decided.

**Comment by matmaxgeds** [comment]
@raashidahmad - aha, sorry, I forgot about the development server on 7001. See screenshot, it is also present there - in particular, see row/project 'war victim rehabilitation' - it has a value of 1,200,000, actual disbursements = '0', and planned disbursements = '0' (but should = 1,200,000) - it seems to only be a problem when the actual disbursements are zero.
![Screenshot from 2019-08-12 04-26-25](https://user-images.githubusercontent.com/432153/62844470-7f2ae500-bcb9-11e9-9484-6c794f0c0db8.png)

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for sharing the screenshot, i will take care of this issue.

**Comment by raashidahmad** [comment]
Fixed
