### ISSUE TITLE
Get excel report encodes port 7000 in request

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#305]
http://104.140.103.36:7000/ExcelFiles/ProjectBudget-636993767272284917.xlsx

This seems like it might not work for people behind firewalls that block port 7000

Please check the whole AIMS for similar things.

**Comment by raashidahmad** [comment]
@matmaxgeds we can only deploy one application on port 80. The back-end is still listening at some other port. The excel is generated by the API and hence you only download Excel from server.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, I understand that - that might be a problem still - I think that  is there any way that we can pass the request via the UI so that the client is not seeing the port 7000?

I am fairly sure on this because I looked into the login issue - and that also has clients making a port 7000 request when they click 'check availability' - and notice that of the 6 people in the testing, it only worked for 1 or 2 people. If we can pass things via that UI, then I think we will have to integrate the two parts of the AIMS as the post issue really is a deal breaker due to lock-downs on the laptops of many of our users.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for providing your feedback. Let me share few more things to make it easy for us to understand.
1. The port is never an issue. As it matters from the source. For example on the testing server i have allowed incoming request on port 7000 from outside, and hence your are seeing you can access. 

2. For the client accessing it does not matter. What matters is that on some networks IP based access is blocked. 

3. I tried with two internet services at my home. One service was allowing access to IP and while the other did not.

4. Solution for this would be to either allow IP based access from the users network or a user may access it from other public service provider, normally we have at our homes. In our case it was world bank internet, i suspect network policies were creating issues.

5. In future i hope so, when we will deploy it somewhere on domain owned by MoP, this issue will be resolved.

In the meantime, i will also look for if for testing server on Azure cloud or Amazon cloud and will look for the prices as well. Normally we do not get an IP based access on clouds instead it is a url.

**Comment by matmaxgeds** [comment]
@raashidahmad  - if I block port 7000 outgoing on my laptop then I cannot login to the aims or register. If I allow port 7000, then I can do those things as normal - so this looks to me like a port issue not an IP issue. I suspect many of our users have a similar port restriction on their laptops - and they could access the homepage so it didn't sound like an IP issue. Because of this, I don't think that the server it is deployed on will make a difference.

![Screenshot from 2019-07-24 16-19-16](https://user-images.githubusercontent.com/432153/61801614-5dafa980-ae2f-11e9-9106-a93e7d8076a6.png)
![Screenshot from 2019-07-24 16-19-41](https://user-images.githubusercontent.com/432153/61801627-61433080-ae2f-11e9-9abf-e3c443668d8b.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for all the work. I totally agree if block incoming port on server or block outgoing on client, in both the cases it will not work. I think this is not about their laptop settings but the network they were connected to, in that case, they were accessing the Internet through a proxy server, which was blocking the outgoing port 7000. To deal with port issue, the possible options i am now seeing are little clumsy but it is a workaround.

1.  What if if keep my back-end on our testing server with port 80, and then keep the UI for testing on the development server using port 80, we will not need any ports to access.

2. For our developments, we will use ports with both back-end and front-end, as it won't matter for our development purpose.

In the meantime, if get some free time, i will try to look for any other possible options.

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad  - I think this is right i.e. the laptops their are supplied with by their organisations probably require the use of a VPN (because they work for international organisations / embassies) which block outgoing port 7000.

The workaround of having just one backend, and one frontend with different IP addresses, but both using port 80) sounds annoying but like it might work. Please let me know when it is implemented as then I will get the people who had problems to test it again to confirm that was the issue.

**Comment by raashidahmad** [comment]
Correct, thanks. @matmaxgeds i will try to implement it tonight. If not for sure it will be by tomorrow's noon.

**Comment by matmaxgeds** [comment]
@raashidahmad - I can't see the excel export button any more (see screenshot) so can't test this?

![Screenshot from 2019-08-11 12-16-47](https://user-images.githubusercontent.com/432153/62833160-f0bf5080-bc31-11e9-9974-e18ac2ecb497.png)

**Comment by matmaxgeds** [comment]
I also now looked at the dev server so I can see the 'get excel' button but this still points to a link with the port 7000 included therefore will not work for many of our users

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for checking this, this is because dev server is pointing to server listening on port 7000. I need to deploy latest version on test, with the fix it will point to server with IP only.

**Comment by matmaxgeds** [comment]
@raashidahmad cool - good to know, I will close it then

**Comment by raashidahmad** [comment]
Thanks
