### ISSUE TITLE
Budget report - cannot have planned disbursements for FYs in the past

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#306]
It is not possible to have planned disbursements for years that are in the past. Please look more carefully at the formulas in this report - and see that for completed FYs that are in the past, the expected disbursements are always zero. Then there is a different formula for the current FY, and then a third formula for future FYs.

When I have made a template, please test the reports i.e. testing that when the template data is entered, the report shows the same result.

[Budget report (v2).xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3416153/Budget.report.v2.xlsx)

**Comment by raashidahmad** [comment]
Fixed
