### ISSUE TITLE
Merging projects only allows merging of title, dates and description

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#307]
But the user will want to merge the data for the funders, the implementers, the sector etc........so the merge process needs to continue, not just stop after the first data entry screen

**Comment by raashidahmad** [comment]
@matmaxgeds Sorry for any misunderstanding on this feature. the merge feature merges funders, implementer, sectors, locations all with the same button click. Please see the project details, it will give you a better idea.

**Comment by raashidahmad** [comment]
@matmaxgeds please see this project on dev server, which i have merged using the merge tool. I did not update it manually.
http://104.140.103.166/view-project/29

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad - please remove the 'one click' option and just push users down the path of continuing to merge all the other fields themselves.

**Comment by raashidahmad** [comment]
@matmaxgeds Okay, will discuss it in today's meeting.

**Comment by raashidahmad** [comment]
Done. Presented for review.
