### ISSUE TITLE
Find a library for tables that handles subtotals/expansion of rows

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#309]
I think this means a 'tree table'. Almost all our report tables would need to be this. Examples include:

https://www.primefaces.org/primeng/#/treetable
http://ui-grid.info/docs/#!/tutorial/Tutorial:%20215%20Tree%20View and http://ui-grid.info/docs/#!/tutorial/Tutorial:%20319%20Complex%20Trees
https://www.npmjs.com/package/ng-treetable
https://www.npmjs.com/package/angular-tree-grid
https://www.jqwidgets.com/angular/angular-treegrid/ - license probably ok, but need to confirm
https://akveo.github.io/nebular/docs/components/tree-grid/overview#nbtreegridcomponent - license unknown

**Comment by raashidahmad** [comment]
Fixed/Introduced on budget report.

**Comment by matmaxgeds** [comment]
@raashidahmad - which library are you using in the end?
