### ISSUE TITLE
Font size on printed reports too small

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#31]
Please make the table/chart font on printed reports several times larger - on my printouts it is tiny

**Comment by raashidahmad** [comment]
Font size updated. Please check it now and reopen if still needs adjustments.

**Comment by matmaxgeds** [comment]
Thanks - the printed text is still too small for me - see scanned version here: https://drive.google.com/file/d/16t25_v5sZdkOQrnjDwjI_VXKwDdgiXcK/view?usp=sharing - please can you make it even bigger? Or do you think the issue is at my end?

**Comment by matmaxgeds** [comment]
Can close this once we are sure we are relying on the pdf export and have removed the print report button

**Comment by matmaxgeds** [comment]
Closing as assuming will be dealt with, or can re-open
