### ISSUE TITLE
For text fields e.g. 'description' add word limits in brackets after the title

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#310]
In this case 100 words i.e. roughly 5 sentences: "(maximum 50 words)"

**Comment by raashidahmad** [comment]
@matmaxgeds formulating maximum length of a text field is little complicated, i would propose it to be in terms of maximum characters. This way we can easily control the length of text fields.

**Comment by matmaxgeds** [comment]
@raashidahmad that sounds sensible - please use 'characters' not 'chars' when adding the limit to the UI

**Comment by raashidahmad** [comment]
Updated.
