### ISSUE TITLE
'information' UI element and management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#311]
We need a way to give users information to help them complete various fields - and then for the management users to maintain that information.

Is it possible/reasonable to have an element that:
1. appears after every data entry field
2. when clicked displays a popup
3. has a management page to manage the text
4. the management page lists each (i) named by the data entry field it is linked to and provides a space for entering guidance
5. the (i) will also be needed for management page data entry fields

For the element we can use the bootstrap (i) as a link icon: https://www.w3schools.com/icons/tryit.asp?filename=trybs_ref_glyph_info-sign i.e. <a href="#"><span class="glyphicon glyphicon-info-sign"></span></a>

The difficult ones will be generating them for the custom fields as then the (i) management page will need to monitor the creation of custom fields - so to avoid this maybe we can think that these do not have them, but we add a new 'guidance' field to the 'create custom field' management page for the manager to enter guidance.

**Comment by matmaxgeds** [comment]
For launch can make do without

**Comment by raashidahmad** [comment]
@matmaxgeds Help feature is implemented for data entry, Management section is completed. Few challenges that i am mentioning below:
1. Help is now shown in front of data entry fields on basic information page, and Financials.
2. The sectors/location page is managed in a very adjusted way, i tried to place the similar icons as in basic information and financials, but it spoiled the UI and make it feel inconvenient for the end user.

Please take a look on and suggest me what do you think how to tackle it on that tab? or we can leave help fields on this tab.

**Comment by matmaxgeds** [comment]
HI @raashidahmad this looks great, a few tweaks below:

- [ ] Please put an icon for each field in the financials data entry page, including for the project currency and project value......as the help text will explain where/how these were set.
- [ ] For the sectors and locations page, I suggest that if we split sectors from locations (each in it's own sub-box), then probably one will go above the other and they will fit better? And this will give more room for the help icons? 
- [ ] I also don't see the help icon on the markers? I also suggest that we go back to a separate data entry page for the markers as it is going to make the page too big given how many there are.
- [ ] For the markers, there seems to be a separate help text system, with the text entered when adding a Marker, that is ok, but if it is not hard, maybe it is better to integrate the markers help with the other help text, or even better, make the markers help text accessible from both interfaces

**Comment by matmaxgeds** [comment]
Sorry, closed by mistake when commenting

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the feedback. Please see my comments below:
a) Will put the help icons for all items mentioned except, we are setting help for only current and planned disbursements. This means same text will appear for the current year and upcoming future years.
b) Agree we can split sectors & locations to vacate some space for help icons.
c) Help for markers is setup when creating a marker, it is available under management for marker, and we can show them in front of every marker.

**Comment by raashidahmad** [comment]
@matmaxgeds this has been implemented.
Note:
1. You can change the help text using help management
2. For marker please set the help using markers section
