### ISSUE TITLE
Insert 'contact' option in project profile reports and projects list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#313]
In the top right and bottom right of the project profile reports, and in the project list, add a 'contact' button for users who are not part of the project to contact the project with questions, to report incorrect data, or to suggest data to add to the project.

**Comment by raashidahmad** [comment]
Done with three types of proposing data edit options

**Comment by matmaxgeds** [comment]
Re-opening on a low priority as this will need a tweak

**Comment by raashidahmad** [comment]
We now have Suggest a change button, works as proposed.
