### ISSUE TITLE
Simplify funding data entry tab

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#317]
1. Rearrange UI to simplify:
2. Remove field for funding date - use the project start date instead for exchange rates
3. Keep ‘funder’, ‘type’, ‘amount’, ‘currency'
4. Remove exchange rate source choice and exchange rate user entry field
5. User sees the default currency amount in the table when added

**Comment by matmaxgeds** [comment]
See here: https://docs.google.com/spreadsheets/d/1oroDS4Wv-KZ3755oK6IKVqoIR-NnPOQllhIEDZjFsn4/edit#gid=1602018085

**Comment by raashidahmad** [comment]
Done
