### ISSUE TITLE
Use annual average exchange rates

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#319]
1. Add an exchange rate option for average annual exchange rates’ - this should calculate the average annual exchange rate based on the data contained in that source so far
2. The average annual rate for each exchange rate source to be available as an option in the exchange rates management page.
3. Annual means ‘for the FY’ not for the calendar year

**Comment by raashidahmad** [comment]
Please guide me little more about this, for what purpose we will use this rate. For example:
1. Will this be calculated for each ex rate request from the UI
2. Do i need to store this into DB, when management user enters it using the management page.
3. If i need to store it into the DB, then i will store it against the financial year into the DB, but will require it to update with every new ex rate entry into exchange rate.

**Comment by matmaxgeds** [comment]
Hi Rashid - just responding based on my notes from our conversation today.

1. I suggest we calculate and store this in the DB independently from the UI requests
2. We will calculate it from the existing exchange rate sources - the order of the sources will be selected by the management user i.e. if sufficient data is not available in the first source for a currency pair to calculate an annual exchange rate, then try the next source - this will function as a fall-back
3. This sounds as expected

**Comment by matmaxgeds** [comment]
Or copied from another issue:

1. Setup auto calculated exchange rate source "annual average exchange rates". A new source, generated by a regular script, that calculate an annual average exchange rate for currency pairs based on the data available in the other sources.
2. Allow management user to select the order in which the other exchange rate sources are used to generate the annual average
3. Remove all the exchange rate choice (including manual entry) boxes/dropdowns from the UI, replacing with the annual average
4. Only allow users to select currencies for which an annual average exchange rate exists for the year in question

**Comment by raashidahmad** [comment]
Happening now, closing it, until proposed to change it
