### ISSUE TITLE
More filters for 'view reports' and 'data entry'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#32]
We would like to standardise the basic set of filters that users use to filter through the lists of projects as much as possible. Please can we initially try for the following set. They should appear on the 'view projects', 'data entry' and 'reports' pages.

- Project name/description (text search)
- Organisations (either funder or implementer)
- Dates (all projects active within date range selected)
- Sector
- Location

**Comment by raashidahmad** [comment]
Implemented. Please test it, reopen it if you find any issue.
