### ISSUE TITLE
Add implementer types

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#325]
1. Add organisation type to data model
2. When registering a new organisation e.g. when registering a new user - ask for organisation type
3. Organisation type from new codelist
4. Management page needed to CRUD this codelist
5. As with sectors/locations - need to specify what option to map to when an option is being deleted
6. When an organisation is created through an import - add the organisation
7. Notify management users that there is an organisation added without an organisation type
8. All the organisation type to be managed from the organisations management page

**Comment by raashidahmad** [comment]
Have implemented organization types.
