### ISSUE TITLE
Sort out notifications information

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#327]
See screenshot - it is unclear what the notification shown is for - please make very simple text for the notification e.g.: "A new organisation (ORG NAME) has been created and needs approval", or "The first user has joined an organisation and needs approving"

However, this applies to all the notifications. We cannot just send the user receiving the notification the same text as is in the email that the user that triggered the notification receives.

![Screenshot from 2019-08-12 06-09-10](https://user-images.githubusercontent.com/432153/62845408-f5364880-bcc7-11e9-9d7c-aa1a1e1259c1.png)

**Comment by raashidahmad** [comment]
@matmaxgeds i will create a google document for it with different notification types and please write the text you want for every notification. This will help me do this task quickly.

**Comment by raashidahmad** [comment]
Please reach the document to suggest message for the provided types. As i learn about more message types, i will add to the document so that you can then add the message

https://docs.google.com/document/d/1KtCzyQE056JRh_R3RQdalGa9PlMQvxz_FzE76w1fPWQ/edit?usp=sharing

**Comment by matmaxgeds** [comment]
new message text done via management page, closing
