### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#333]
See ToR section 2.4

Currently envisaged as a simplified version:

- daily backups
- User set max storage space
- No user input into the frequency of backups etc
- management page to take an additional backup
- same management page to restore a backup
- management page setting to set the space where the logs are stored on the server
- logs to cover all aspects i.e. projects, users, settings etc
- all aspects to be restored together at this stage - to avoid conflicts being created i.e. projects without organisations etc

**Comment by matmaxgeds** [comment]
Confirming here that we are dropping the external/cloud backups feature to save time

**Comment by raashidahmad** [comment]
Implemented with simple version but handy.

**Comment by matmaxgeds** [comment]
@raashidahmad great to see this. Please can I confirm that this also covers users, management settings etc?

Please also move the link to the management menu

**Comment by raashidahmad** [comment]
@matmaxgeds Correct, the current state of the database, any entry in the database related to users, management, or settings will be backed up.

**Comment by matmaxgeds** [comment]
@raashidahmad great, just leaving open until the link is put in the management page menu

**Comment by raashidahmad** [comment]
@matmaxgeds It is moved as suggested.
