### ISSUE TITLE
Report handling of data where field is not filled in

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#341]
There will be a lot of cases where a report e.g. the sector report has some projects where there is no sector added. We want to show all projects when doing a sector report, so how to show those without any sector information?

All reports should add a 'not specified' option to cover projects with no data in that field. Perhaps this is easiest to do via the data input e.g. we don't want to add 'not specified' to the field types as an option, but if no data is input, this is what the UI writes to the db?

We then need a filter on all the reports to either show, or not show the projects that have no information for that field - i.e. for the sector report - not show projects with no sector information, or show projects with no sector information, same for location.

Need to think what to do for the other reports.

**Comment by raashidahmad** [comment]
@matmaxgeds Lets discuss this in the upcoming meeting. There are few things that needs discussion.

**Comment by raashidahmad** [comment]
@matmaxgeds While doing some paper work i found few concerns. Please take a look on and guide me about that.

1. If we are adding a filter on sectors report to show projects that does not have any sectors attached, then the following things will happen.

(a) The server query will be totally different and does not fit into the current api written for sectors report

(b) The result set will be different and will contain any sectors/location (in case it is a location report), hence the view structure will be different, chart will also be different.

(c) I would strongly propose to not show this feature on the current reports, and design another general report, where we can allow the users to see project that do not have sectors or locations.

(d) Please while suggesting this report, bear in mind, that view will remain same for all the filters, for example, the names and number of columns.

**Note:-** In a worst case, If we are going to incorporate no projects filter within the current report and APIs, it will cost us de-stabilization of current reports UI, and API, write us lot of complex code and handle complex situations on UI.

**Comment by matmaxgeds** [comment]
@raashidahmad - maybe a phonecall is easier for this one.

The issue is that if a user wants to see how the projects for 2019 are allocated across sectors or locations, then they are not only interested in the projects that have sectors, but also those projects without them.....I think this just means that it is like if there was a default sector called 'No data' that exists for all projects until a sector is provided, does this make it clearer/simpler. This should fit in the existing UI as it is just like having another sector?

**Comment by raashidahmad** [comment]
@matmaxgeds That makes sense, but my opinion would be not to insert the No Sector into AIMS and generate this at runtime for Sectors/Locations report only, as creating it using DB will create issues for other APIs using sectors and locations. I will work on it and if there are any queries,  will make you a call.

**Comment by matmaxgeds** [comment]
Referencing the almost identical issue #51 which might be useful as explanation - and closing that one

**Comment by matmaxgeds** [comment]
The other reason we need this is so that when management users make changes e.g. to the sector/location codelists, then some projects might lose their data, and so this means that they will not be lost to the reports e.g. see https://github.com/somaliaims/Somali-AIMSUI/issues/250

**Comment by raashidahmad** [comment]
No sector & No location added on Sectors & Locations report

**Comment by matmaxgeds** [comment]
Nearly there on this one.....

- [ ] please can we just standardise the words we are using. This means using "Unattributed" where there is no sector given, just like when there is no location given
- [ ] the implementation on the locations report should not have the extra dropdown for 'no location', this should not be needed as all projects without a location are set on entry to have their location as unattributed, set to 100%, or less if there is another sector which does not fill the full 100%

**Comment by raashidahmad** [comment]
Implemented again as suggested.

**Comment by matmaxgeds** [comment]
Very close now:

1. The "UNATTRIBUTED" sector should not be deletable in the sectors/location lists, but can be re-named

**Comment by raashidahmad** [comment]
Implemented. Please go to sectors and locations list. Search for unattributed, delete is disabled, one can edit the name.
