### ISSUE TITLE
Delete envelope type

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#344]
I am currently getting an error when trying to delete an envelope type and mapping it:  "The property 'EnvelopeTypeId' on entity type 'EFEnvelopeYearlyBreakup' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal. "

**Comment by raashidahmad** [comment]
Thank you @matmaxgeds for the detailed reference of the error. Let me write an issue about this, why it is throwing this error:
1. Actually for envelope, in a particular year with an envelope type, we can have just one entry. For example while deleting Peacekeeping, if we are assigning it to Humanitarian on deletion, and if Humanitarian already has an entry for that year, for example 2019. It will not enter Humanitarian again for 2019 with envelope type value of the deleting Peacekeeping. It will consider a duplicate for this entry.
2. What is possible in this case, is that delete the Peacekeeping type without mapping to another type if that already exists in the database, or assign the value of Peacekeeping to Humanitarian for that particular year.

Please guide me on that.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad thanks for the explanation - ideally:

1. No deleting without mapping
2. Mapping means appending/adding the mapped amount to the existing amount for the fields it is mapped to for that year.

Is that possible?

**Comment by raashidahmad** [comment]
Yes, that is possible. I will then do it this way:

1. Delete the envelope type only against a mapping.
2. Add amount of the deleting type to the existing amount of envelope type mapped.

**Comment by raashidahmad** [comment]
Fixed
