### ISSUE TITLE
Add stacked bar/line chart type

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#349]
See here: https://www.chartjs.org/samples/latest/charts/bar/stacked.html

And also the same for a stacked line chart.

**Comment by raashidahmad** [comment]
@matmaxgeds We have stacked bar for budget report. Where else do we need it?

**Comment by matmaxgeds** [comment]
@raashidahmad good question - I am going to start maintaining a list here: #364 (so will close this issue) but for information, I will also need to give more detail on which aspect should be stacked. In fact it will depend on the work in #267 and also the work to add more tree structures to the tables where possible
