### ISSUE TITLE
Budget report - needs excel export and sectors not projects

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#351]
1. Please enable excel export for the table
2. Please replace 'projects' which are currently the sub-level in the table, with 'sectors' and set it to the national sectors

**Comment by raashidahmad** [comment]
@matmaxgeds need help on this: What i get from the explanation is that:
1. I need to show sectors, with total disbursements in place of project. (For example, currently project is shown in front of plus sign)
2. When a sector is expanded, it must show the breakup of total disbursements, for example, actual and planned.
Is this is what you are suggesting?

**Comment by matmaxgeds** [comment]
@raashidahmad - I have combined this with the answer to issue #364 to make it easier
