### ISSUE TITLE
Financial year management - enter start/end data, autogenerate years, not enter years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#356]
At the moment, the financial year names are manually entered, instead of this, on the FY management page, the management users should set the start and end dates of the FY, and based on that, the system can generate all the required financial years it needs.

If the start/end dates are within 5 days of December the 31st/Jan 1st i.e. between the 26th Dec and 5th Jan (including those dates) then name the FY after the main year i.e. "FY2014", but if the start/end dates are elsewhere in the year, then name the FY "2014/15" based on the calendar years it covers.

**Comment by raashidahmad** [comment]
@matmaxgeds We are storing years as integers, this makes the query to easily filter the range etc. Will this not be better to provide the user with two dropdowns starting year and ending year for a range of years to be created?

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - I think there is a confusion, this is only about the management page, and how the list of FYs is generated. At the moment, the management users have to enter them all. Instead, the management users should set the start/end date of the FY (which is the same every year) and then the system generates the list of FYs for use in the AIMS

**Comment by raashidahmad** [comment]
@matmaxgeds thank you for the answer, noted.

**Comment by raashidahmad** [comment]
This feature is implemented this way. If the start and end dates are between 25 Dec and Jan 05, this will get the major year from 25 Dec and will create it. In other cases, it will create the range of years. Closing it for now.

**Comment by matmaxgeds** [comment]
@raashidahmad this looks great, a few small tweaks:

- [ ] We no longer need to show the list of FYs on the management page, it can be just the tab where the management user enters the start/end dates, as the FYs themselves are not editable by the users
- [ ] You do not need to ask for the date of the end of the FY, as it is always a full year, so it is the day before the start date, just one year later
- [ ] You do not need the year for the start date, it is just the day and the month (so use two dropdowns instead of the datepicker)
- [ ] Please concatenate "FY" to the start of the years, so that it is clear whenever users see them in the UI (e.g. in the charts) that these are FYs, not calendar years
- [ ] The list that is generated needs to be 'unlimited' i.e. we agreed that based on the start date selected by the user, the system would generate entries for the FY table based on 50 years before, and 50 years after the current date - at the moment, it just shows 2003, 2005....up to 2024......but if someone enters a new project, then perhaps 2027 or so will be needed.
- [ ] I entered a start date of 01/07/2018, and an end date of 30/06/2019.....this should have generated FYs called "FY16/17", "FY 17/18", "FY 18/19" etc.....but I didn't see any change?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the detailed reply. This needs some re-structuring of the FY's, will fix this, hopefully by this weekend.

**Comment by raashidahmad** [comment]
@matmaxgeds suggested changes incorporated as suggested with one thing different, that is i have retained the years listing with no action to edit, as it will be consistent with other management pages this way. e.g. After adding an year/range of years it will return back to the listing. Closing it temporarily until you think different.

**Comment by matmaxgeds** [comment]
@raashidahmad - understood on keeping it consistent, in that case, please 

- [ ] rename the tab from "create new" to "change the Financial Year"
- [ ] You do not need to ask for the date of the end of the FY, as it is always a full year, so it is the day before the start date, just one year later - having the option to enter it will only cause mistakes, please remove the dropdowns for the end date
- [ ] You do not need the year for the start date, it is just **the day and the month** (so use two dropdowns instead of the datepicker)
- [ ] Please rename the submission button after the date selection from "Add Financial Years" to "Generate Financial Years"

I also think I haven't managed to be clear about how to determine how to label the financial years. Maybe with examples it is easier. If the user enters:
1. 1st January, then they Financial Years the system should generate are FY2014, FY2015 etc
2. 4th April, then they Financial Years the system should generate are FY2014/15, FY2015/16 etc
i.e. if the user picks a date very close to the calendar year break point, then we name the FYs by the calendar year, but if it is more than 5 days away from the calendar year break point, then we name the FYs with both of the calendar years that will be a part of the financial year, does that make more sense?

**Comment by raashidahmad** [comment]
@matmaxgeds I need some discussion on this, i am unclear about few things about it. For example, you said, we need only month, and day, then how the system will know which year user wants to create. In the already developed UI, Ending month and year are optional, In fact user can select either starting month and year or ending month and year.

**Comment by matmaxgeds** [comment]
Hi.....maybe this explanation helps, otherwise to discuss on Thursday morning. 

If I select the date 01 April, then the Financial Years that the system needs to generate are from 01 April to 31 March.....that is the financial year. So we are just determining the start and end dates within the year (this is why only day/month are needed), and those are applied to each year that we need to generate. So for 2019, the financial year will start on the 1st April 2019, and therefore end on the 31st March 2020, so the Financial Year is labelled "FY 2019/20"

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the explanation, all the details are helpful. I will incorporate the changes but would also like to discuss it in tomorrow's meeting.

**Comment by matmaxgeds** [comment]
As discussed on skype today, the issue is that we do not just need to label each calendar year with a FY label, but that if the FY starts on the 1st July, then a date e.g. 15th Februrary 2018 is in FY 2017/18, but a date later in the same year e.g. in October is in the next FY e.g. FY 2018/19. So what we need is a way for the UI to lookup the FY to store data against when adding projects, and also the reverse e.g. for looking up which projects-data to return for a report which is filtered by a FY range

**Comment by raashidahmad** [comment]
@matmaxgeds continuing with your comments, as discussed please see the document on it using the link pasted here:
https://docs.google.com/document/d/1pnB3k66aS89ykiZKHuraqW7NcWoMIaAHo7S7IuAnW74/edit?usp=sharing
I feel i am starting work on this straight away, as this is a core issue related to all section of AIMS. By analyzing the changes it requires, i hope i will be able to show you something on it by Monday and will try to deploy the latest AIMS on the same day or night, e.g. 6th of January.

**Comment by raashidahmad** [comment]
@matmaxgeds FY is now added by entering the month and day. Other changes are also done for the financial years. To make this task easy i have taken the following steps:
1. Wrote the script to change the labels of entered financial years instead of running the data import script again for projects
2. Wrote the script to change the financial years for already entered projects using the date.
3. In order to know about the start of the financial year, a management page has been designed where manager user can set the starting date for the financial year.

**Comment by matmaxgeds** [comment]
HI @raashidahmad - nso close now, just forgetting the bit where if the start date is the 1st of January, then the format is just FY 2020 etc......as in this case (1st Jan start date) there are not two calendar years that make one FY.

Also please adjust the text to say:

"Manage financial year" >>> "Set start day"
"Add financial year" >>> "Generate Financial years"
"Create New" >> "Adjust start day"

**Comment by raashidahmad** [comment]
Suggested changes implemented on this page.
