### ISSUE TITLE
Excel Report

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#359]
The ToRs include a report that allows users to download all the data as an excel sheet....for situations where the other reports do not meet their needs.

No chart
Normal filters
Table showing a row per project - essentially this should look like the data import file

Probably best to get the page setup and a very basic export with e.g. just the project names, then we can figure out the detail on exactly how to do columns needed, how to do the currencies and exchange rates etc.

We also need to figure out an excel export for the envelope data......but that I think can come after the launch - or maybe it isn't needed depending on the excel export from the envelope report, I can't check properly until I get back to my desk

**Comment by matmaxgeds** [comment]
Questions from @raashidahmad: 
1. At some instance of time there might be some projects which will be finished. Do we need to include those projects in this report? For example, a project ended in 2018.

Answer: We should include all projects that were active at any stage during the date range set by the user in the report filters, it doesn't matter if they have not started yet (in case the user selects a date range that is all in the future) or if they have finished (if the user selects a date range all in the past).

2. The input document which I will import contains the disbursements starting from year 2016 and ending in 2018. What should be the sequence of disbursements by year for this report? For example, a project might start in 2017 and be ending in 2019, while the other may be starting in 2018 and ending in 2022. How shall I select the years of disbursements to be displayed in this report in a form of Excel sheet?

Answers: It should contain all the disbursements for the project that fit within the years selected by the user. For the sequence, I have added a template which should hopefully make this all much easier. [2019 Aid Mapping - 4Nov (for import) v19 Denmark plus.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3852284/2019.Aid.Mapping.-.4Nov.for.import.v19.Denmark.plus.xlsx)

For the importing of disbursements, I have added this as an issue to the data import issue here, as how to import the 'disbursements before 2016 is an important point'. see #391

**Comment by raashidahmad** [comment]
@matmaxgeds Thank you for the answer, i am working on it. Will consult you if there are more queries.

**Comment by raashidahmad** [comment]
This report is now available. Please check it under reports section, then projects report. Closing it so you may notice and test it.

**Comment by matmaxgeds** [comment]
@raashidahmad - this looks great - but it also looks nothing like the template that I sent you?

The problem (and this is why I designed the template differently) is that this format only works with one sector per project (which is what we have in the import data, but not in the AIMS once it is being used). Hence as soon as a project has multiple sectors (and therefore also sector percentages) that the template format you have made will break - unless there is a solution to that too? I suppose you could also list the Somali sectors like the locations, and give the percentages in the cells?

What should then happen where there are multiple resources per project? Perhaps you can just list those as csv format within a single cell i.e. in each case, the resource name | resource link, resource name 2 | resource link 2 etc - or a similar solution. This way each resource name is next to the resource link it represents.

1. Rename it to "Data export"
2. Implement solution for multiple sectors and resources per project as discussed above (if this doesn't work, go back to the format that I gave in the template attached above)
3. Also implement it for the envelope data as discussed above

Please also let me know how you have chosen the exchange rate, as there are different exchange rates for each year of disbursements for the project

Finally, in the example attached, there are no disbursements (all are zero?)
[AIMSProjects-637102262095126197.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3884127/AIMSProjects-637102262095126197.xlsx)

**Comment by raashidahmad** [comment]
@matmaxgeds while thinking about the logic about sectors, i found if we follow the same pattern as for locations, then in that case we will have many more columns for sectors, For example, i found there are about 30+ Parent sectors including both from the new list you sent and the old list in the data initialize. Please let me know will too many number of columns work for sectors?

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - we will only use the somali sectors for outputting data - and all data is stored at the lower level (the sub-sectors) so I think there are about 15-20 of those.

At the moment, I am saying that given you have made it work in the format similar to the data import sheet, then I suggest you continue like that, rather than restarting with my template. That means:
1. Having the 20 sub-sectors spread out like the locations
2. Solving the issue of exporting multiple document links into one cell

**Comment by raashidahmad** [comment]
Hi @matmaxgeds thanks for the reply. Helpful, will do as suggested.

**Comment by raashidahmad** [comment]
Changes implemented.

**Comment by matmaxgeds** [comment]
@raashidahmad - the sectors include both the parent level, and the sub-sector, this doesn't make any sense and ignores the hierarchy between them - you need to just include the sub-sectors which are the level that the data is stored at. Please also move the sectors to just before the locations in terms of column order.

**Comment by raashidahmad** [comment]
@matmaxgeds Suggested changes implemented. Please review.

**Comment by matmaxgeds** [comment]
@raashidahmad - looking great

- [ ] In this case, we don't need an update button as there is nothing to see, the download button can trigger an update based on the years without asking the user, before pushing the xlsx file back, no need for a separate update step first.

I am assuming that once we sort out the ordering of the sectors, this will also apply here

**Comment by raashidahmad** [comment]
Button status set as suggested. If we sort out sectors on the back-end, it will apply everywhere.
