### ISSUE TITLE
Add financial years to UI relacing calendar years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#36]
The UI needs to use financial years, not calendar years everywhere where a user is selecting a year, but not anywhere where a user is selecting a date. For example, in the reports year filter, this should be financial year, not calendar year. So somewhere in the AIMS settings, we need to be keeping a variable which records the financial year. In the case of Somalia, The Financial year is January to December, so in this case the dropdown menu should show FY2016, FY 2017, FY2018 etc, and then when the user selects them, the UI will be able to lookup the FY>year/month conversion and see that this means projects from January 2016 to December 2018 should be included. If the financial year ever changed e.g. to July-June, then the dropdown would show FY18/19, FY19/20 etc.

**Comment by raashidahmad** [comment]
Financial years management page is written.

**Comment by matmaxgeds** [comment]
Thanks for adding the management page - please can we adjust the input method so that the user selects the start date of the new financial year in DD/MM (the end data is automatically set to the previous day) - and then the system can calculate all the financial years automatically without them needing to be added - that way there will be less problems in the future. So we don't need to show the list of all the FYs as they will be infinite both forwards and backwards.

The system will need to label them intelligently i.e. if the start/end dates are within 5 days of December 31st, then the system should label the FYs in terms of whole years i.e. FY 2018. But if the start/end dates are outside this time, then the system should label them as FY18/19 based on the two calendar years that are covered.

**Comment by raashidahmad** [comment]
Financial years now coming from backend and we are not using dates anymore.
