### ISSUE TITLE
Report exchange rates are using 'day rates'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#365]
These should probably use the same 'annual exchange rate'....but need to think about this as which year to use it for, i.e. the appropriate one for each year (a lot of data work), or the most recent year.....but that does funny things to the amounts from different years.......I guess it should use the most recent annual average exchange rate

**Comment by matmaxgeds** [comment]
@raashidahmad please confirm what exchange rates are being used e.g. to show the reports in the National Currency i.e. Somali Shillings?

**Comment by raashidahmad** [comment]
@matmaxgeds the exchange rates are retrieved from annual exchange rates.

**Comment by matmaxgeds** [comment]
Thanks for confirming @raashidahmad
