### ISSUE TITLE
Reports: project filter needs to show options

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#366]
At the moment, unless you exactly know a project name, you cannot filter for it in the reports....so this needs to be a fuzzy search bar which shows the options as you type.

Also the default text should be "search for a specific project" not "enter a project name"

**Comment by matmaxgeds** [comment]
As discussed, just use the same dropdown as for organisations

**Comment by raashidahmad** [comment]
Implemented
