### ISSUE TITLE
Reports: filters need names

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#367]
At the moment, the report filters do not have names (Except for the start/end dates)......so it is unclear what the dropdowns are for. Please add these.

That way the default text will make more sense too.

**Comment by raashidahmad** [comment]
![Report-lables](https://user-images.githubusercontent.com/2605356/67548758-1382e080-f71c-11e9-86fd-bf07a85f6fae.png)

@matmaxgeds Please see the default view of the report. Moreover, it shows the tooltips while hover on a field.
