### ISSUE TITLE
Reports: when printing a report, the report title is needed, plus the date

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#369]
Please insert these into the print view

**Comment by raashidahmad** [comment]
Title inserted
Date inserted at the end of the report

**Comment by matmaxgeds** [comment]
@raashidahmad - I can't verify this at the moment as with so many projects the report production is breaking, please can you share a report with these features so I can see it?

2. We also need to include the link back to the report like with the excel sheets.

**Comment by raashidahmad** [comment]
![Report_Header](https://user-images.githubusercontent.com/2605356/69910990-8e839900-1436-11ea-9e2b-0f4474c974bb.png)
![Report_Footer](https://user-images.githubusercontent.com/2605356/69911012-df938d00-1436-11ea-8544-4b5069ee60d0.png)

Inserted. Please check

**Comment by matmaxgeds** [comment]
I looked for this today and don't see it - am I missing something?

![Screenshot from 2019-12-02 12-49-29](https://user-images.githubusercontent.com/432153/69957119-37e39100-1502-11ea-9e62-cef3a8ab5c82.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Please refresh your browser, ctrl + f5, I can see it or please tell me which browser you are using so that i can test it using that browser.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks - clearing the cache fixed it
