### ISSUE TITLE
Rename SMTP settings

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#37]
Please rename this in the menu bar to 'Email settings'

Please also change the text which says 'IATI settings'.

I presume that in the future, we can have a dropdown which allows the user to select:
1 - gmail
2 - SMTP server
3 - services like mailgun and sendgrid

**Comment by matmaxgeds** [comment]
Please also set this up with the Somali AIMS gmail account to test it works

**Comment by raashidahmad** [comment]
Fixed. We can configure it with any SMTP Service.
