### ISSUE TITLE
Adjust account approved message

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#374]
=== currently ==============================

Dear user,

Click on url below to login now:

http://aims.mop.gov.so/login
AIMS Support Team

=== adjust to ===============================

Dear user,

Your account has been approved. 

Please follow the link to login: http://aims.mop.gov.so/login

If you need further assistance, please submit a help request via the contact form in the AIMS: http://aims.mop.gov.so/contact

AIMS Support Team

**Comment by raashidahmad** [comment]
Can be managed using Email messages using the link, once you are logged in: http://aims.mop.gov.so/email-messages
