### ISSUE TITLE
Adjust merge organisations email

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#377]
Dear user,
Organization merged
Organizations renamed

    Old name: MGEC
    New name: MGEC

AIMS Support Team

==================================

Dear user,

Your organisation has been merged and/or renamed by a management user.

    Your organisation: MGEC
    Organisation combined with: MGEC
    New name for combined organisation: MGEC

Please let us know if this change is not appropriate using the contact feature in the AIMS.

AIMS Support Team

**Comment by raashidahmad** [comment]
@matmaxgeds You can adjust the body and footer message using Email messages menu item under the Management section. The grayed part, for example, "Your organization: " has been updated by the system. Please see the management page for email messages, i have updated the message for merge and rename organization feature. Use this link please: http://aims.mop.gov.so/email-messages once you are logged in.

**Comment by matmaxgeds** [comment]
@raashidahmad this link is not currently working for me, I get redirected to the homepage?

**Comment by raashidahmad** [comment]
@matmaxgeds Please, login with admin account before you try the link above.

**Comment by matmaxgeds** [comment]
@raashidahmad apologies, the redeploment had logged me out and I hadn't noticed now working :)

**Comment by raashidahmad** [comment]
@matmaxgeds No problem, thanks
