### ISSUE TITLE
USA IATI data not available

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#378]
I did a demo for USAID last Friday and couldn't find any USAID IATI data, we need to find some way to work out what happened? 

E.g. I couldn't find any of the projects listed here: http://www.d-portal.org/ctrack.html?country=SO&publisher=US-USAGOV|US-GOV-1&year_min=2018&year=2018&year_max=2019&year=2019#view=active in our IATI data?

We also need therefore to check this for all publishers?

**Comment by raashidahmad** [comment]
![af-amisom](https://user-images.githubusercontent.com/2605356/67633903-a5831880-f8d7-11e9-88fb-c1465509faa4.png)
![Somalia-advisors](https://user-images.githubusercontent.com/2605356/67633910-b2a00780-f8d7-11e9-8281-c95f4e513224.png)

@matmaxgeds I found the first two in the IATI data, both in the IATI returned and AIMS UI. But randomly checking i did not find other projects. Interesting thing is, that it has not been returned by IATI, which concludes:

1. The USAID projects are not returned by IATI, though we are running the exact query recommended by IATI for the whole stream.
2. Is there any means we can confirm that USAID has published the projects to IATI. If they have published we can ask the IATI guys to help us why the desired data has not been returned.

**Comment by matmaxgeds** [comment]
@raashidahmad......I think I have an idea, the missing data is published e.g. see here: https://iatiregistry.org/dataset/usaid-so but is not being returned by our query to the datastore because the recipient-country=SO is only at the transaction level for these activities. I have asked how we can solve this, but until then, moving it to 'post launch' as if it comes up, I can explain it

**Comment by matmaxgeds** [comment]
@raashidahmad closing this as currently no way to solve it on our end - it needs us to change datastore, or the datastore we are using to make an upgrade
