### ISSUE TITLE
Add location filter to Sector report, and sector filter to Location report

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#379]
For both reports, users might want to filter down to a specific sector for the location report, or to a specific location for the sector report. For adding the sector filter to the location report, it will need to be both parts e.g. the sector level choser (parent, sub-sector etc), and the sector filter itself.

**Comment by raashidahmad** [comment]
As discussed i have added location filter for sector report as single selected item at a time. Closing it just to make you notice.

**Comment by matmaxgeds** [comment]
@raashidahmad Pau is requesting that we now add a sectors filter to the location report - that will be two dropdowns, for the parent/sub-sector, and for selecting the actual sector. As before, just allow one sector at a time.

**Comment by raashidahmad** [comment]
@matmaxgeds  It is implemented.
