### ISSUE TITLE
Data entry: When adding funders/implementers, no option available if org not listed

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#380]
When a user is adding a project, it might be funded or implemented by an organisation that is not yet in the AIMS, in which case, there needs to be a way to add it e.g. button underneath for "organisation not listed" which allows them to create a new organisation (by entering the name, and the organisation type). The newly created organisation then gets automatically added as a selection.

**Comment by raashidahmad** [comment]
This is fixed and done with one exception. It is not selected after it has been added. The reason it is not selected after it is added is that, this dropdown component do the pre-defined selection before load only. In this case we will have to reload the page, if we reload, we will loose any unsaved data. Closing it.

**Comment by matmaxgeds** [comment]
@raashidahmad - thanks for the progress, issue understood:

- [ ] The [+] button is not clear enough (although the on-mouseover is a good idea), for now, please update the button to say 'add an organisation which is not listed', as a text link below the dropdown instead of the button.

**Comment by raashidahmad** [comment]
Changes made as proposed.
