### ISSUE TITLE
Data Entry: IATI data needs it's own organisations filter/dropdown

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#383]
At the moment, the IATI data is being filtered by the dropdown for the AIMS organisations, this will not work as the organisation names are not the same between the IATI data and the AIMS data.

Please make a seperate filter/dropdown for the IATI data, it should list the names of all the IATI organisations, and be a searchable, multi-select.

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
@raashidahmad this makes a big difference, thanks :)

Is there any way we can put it above the IATI column rather than on the right hand side?

Moved to after launch as not priority

**Comment by raashidahmad** [comment]
Done with first point. Second point, there are issues with this option, as on the same row other buttons are shown and hidden, we do not have enough space. If we occupy another row, the text goes down, which does not give a decent look. Closing it for now.

**Comment by matmaxgeds** [comment]
sorry to re-open, but doing it as not priority, I just don't want to forget about it
