### ISSUE TITLE
Data entry: rename actual/planned for current year to 'to date' and 'remaining'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#385]
I think that users might be confused by 'planned' for the current year, so please rename actual/planned for current year to 'to date' and 'remaining'

**Comment by raashidahmad** [comment]
@matmaxgeds i have accomplished the same with some tip in front of the relevant text boxes. As i saw we are using the planned and actual in so many places including report.

**Comment by matmaxgeds** [comment]
I don't think I am able to test until we have a test server again - is that correct?

Thanks RE the tips - we were going to use the (i) symbols, is that what you have done?

**Comment by raashidahmad** [comment]
![Help_Text_Disbursements](https://user-images.githubusercontent.com/2605356/69171771-63d43f00-0b1e-11ea-855a-da3bdfafdfd5.png)

@matmaxgeds Please see a snapshot of it here. Also, We have not launched the AIMS officially, you can test it and enter projects. I can delete it and we may import the data again from document if needed. I will try to setup the test server this weekend. Is it urgent to setup the server in any other case? Please let me know.

**Comment by raashidahmad** [comment]
Plus i could put (i) icons here but the user needs an extra click or hover. Tips are easy to reach.

**Comment by matmaxgeds** [comment]
@raashidahmad I think your yellow tips are better :) Please tweak them to:

2019 Actual = "Disbursements to date in 2019"
2019 Planned = "Disbursements planned for the remainder of 2019
we do not need the tip for 2020 etc

If I can edit projects for now, then no test survey needed urgently - thanks for clarifying.

**Comment by raashidahmad** [comment]
This is fixed. We do not have such scenario with the current import as we only have Actual disbursements for 2019 and text is updated as suggested. Closing it for now, as i tested with custom data on my local.
