### ISSUE TITLE
Suggest a change - not need "suggestion for" option

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#389]
Please remove the dropdown which gives the different types of suggestions. I think it is just easier to let the user describe what they want in the free text field

**Comment by raashidahmad** [comment]
@matmaxgeds Need more explanation on this, which section it is referring to?

**Comment by matmaxgeds** [comment]
@raashidahmad sorry, when a user clicks 'suggest a change' they are taken to the contact form, but I don't think they need the dropdown to indicate the type of suggestion they are going to make - also as it will often be a mix of multiple e.g. some edits, some new info. Which means it is easier to just remove it

**Comment by raashidahmad** [comment]
Fixed
