### ISSUE TITLE
Remove 'name' field from user registration

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#39]
Please remove this field - we only need email and password.

If we need to contact a user, we will contact the organisation and give the email account - that will be enough. We are not using 'name' anywhere in the AIMS, especially as it will not be unique.

**Comment by kndm** [comment]
@raashidahmad @matmaxgeds 
This has been solved on the front-end, however we require to make the appropriate changes to the API so that it is not required anymore.

**Comment by kndm** [comment]
@raashidahmad @matmaxgeds 
This has been solved on the front-end, however we require to make the appropriate changes to the API so that it is not required anymore.
