### ISSUE TITLE
AIMS Animated Videos

### ISSUE THREAD

**Issue by mohamedgele22** [somaliaims/Somali-AIMSUI#390]
Dear Rashid,

Kindly embed these videos on the AIMS Home Page.

Videos are uploaded here:  https://www.youtube.com/channel/UCy6dk1HcaaUvIIAj6ZG2YVg?view_as=subscriber

**Comment by raashidahmad** [comment]
Dear Gele,

You can see it using the recent deployment for AIMS.

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad - this had made them really small on my screen. I suggest we remove the sections on 'user accounts', and 'partner organisations' to make space for the welcome text to move up, and them to go underneath on the left hand side.

Also on the homepage:

- [ ] The disbursements is still missing thousands seperators
- [ ] Please rename it to "2019 disbursements"
- [ ] I am worried that it shows 2604 registered organisations, did they all come from the imported data? We should not be including IATI organisations here.
- [ ] Reduce the 'recent projects' list to just 5 projects

**Comment by raashidahmad** [comment]
Fixed.
