### ISSUE TITLE
PDF files are too large

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#395]
I guess this is to do with the resolution of the images, but the ones I am downloading are 30-40mb for 2 or 3 pages, that is much too large.
![Screenshot from 2019-11-15 22-51-08](https://user-images.githubusercontent.com/432153/68978232-76870500-07fa-11ea-84ed-5aaa99cea7da.png)

**Comment by raashidahmad** [comment]
@matmaxgeds we are now showing reports in hierarchical tree manner, trying to reduce its size by default. Please review the sizes and close it if you agree. I will keep researching if i could find a decent solution.

**Comment by matmaxgeds** [comment]
@raashidahmad Pau was today unable to download a pdf report, I suspect also linked to the size. I ran a pdf sector report today, and it was 14mb - so that is still too large. I guess there is no way to make pdfs without taking an image of the whole screen as this seems to be causing the issues?

**Comment by raashidahmad** [comment]
@matmaxgeds you are right, in the coming weeks, i will take some time out and do some research if there are any free libraries for javascript that can do the job for us.

**Comment by matmaxgeds** [comment]
@raashidahmad that sounds smart - pdfmake and jspdf are both client side and free I think

**Comment by raashidahmad** [comment]
@matmaxgeds thanks, i am doing some research and will come up with something soon.

**Comment by raashidahmad** [comment]
@matmaxgeds Possible optimizations have been implemented.
