### ISSUE TITLE
Crashes on Firefox

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#398]
Hi @raashidahmad, I am having an issue where loading, or switching to a tab with the AIMS is crashing Firefox, I guess this is at my end, but just letting you know in case we hear about it again. For now I will carry on but using Chrome

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the notice. Can you please write some steps where it is happening, i can then see the particular section of the codes.
