### ISSUE TITLE
Now we have 'download pdf' no longer need 'print report'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#399]
As people can print from the pdf instead, and so we have less to error check / maintain.

So once pdf is full working, please remove the print report button.

Also print report is not working on chrome for me, the popup to print disappears immediately before it has a chance to load an trigger the printer

**Comment by raashidahmad** [comment]
@matmaxgeds I would suggest not to remove it. We may discuss its potential benefits.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, removing things is not priority anyway so closing it here. We can reconsider when pdf reports work on all monitor sizes
