### ISSUE TITLE
Dockerise the UI

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#4]
Please dockerise this (I presume with the official node alpine image: https://hub.docker.com/_/node/)  - we should then have one docker compose file, the specifies both the containers e.g. following: https://docs.docker.com/compose/gettingstarted/#step-3-define-services-in-a-compose-file

**Comment by matmaxgeds** [comment]
@raashidahmad please put the images on the Somali-AIMS docker page/repo, not on your personal one

**Comment by raashidahmad** [comment]
@matmaxgeds That's correct, will create account for aims.developer18 on docker hub. As we do not have any other official account. Is that okay?

**Comment by matmaxgeds** [comment]
@raashidahmad we do already have an account - I emailed you the details

**Comment by raashidahmad** [comment]
@matmaxgeds this is updated. Please use link to see the full documentation:
https://docs.google.com/document/d/1JdE6R9q7mtQtAT59T_N-01vnyWqlakyqFM1GJeiM-tc/edit?usp=sharing
