### ISSUE TITLE
Reports: when selecting items in filters and clicking update, filter options not kept visible

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#402]
When I filter a report (not by organisation, but by one of the standard dropdowns e.g. date) and click update, everything works, except the dropdown does not show me the date I selected, even though the data is filtered, which makes it very hard to see what filters I have used. Please can the selections on the dropdowns persist after clicking update

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for indicating the issue. Can you please help more about this issue, where it is happening. I am trying to find with which option it is happening on what report.

**Comment by raashidahmad** [comment]
@matmaxgeds Need your help on it, i am trying to find out what section you are referring to. If you find it fixed. Please close so that i can pay attention to others. Thanks

**Comment by raashidahmad** [comment]
Closing it so that i can focus on the others left. We may work on it, if it is happening in some section.
