### ISSUE TITLE
Project with zero value?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#403]
This project has a value of zero....this shouldn't be possible? http://aims.mop.gov.so/view-project/2906 - partly the problem is that on the excel sheet I sent (this one is the bottom row) it was entered without any disbursements in the dates requested, but that should mean that the project value is distributed across the dates that are available for the project.

This also means that we need to check how the other projects are being imported e.g. do the disbursements always total up to the project value, they need to?

**Comment by raashidahmad** [comment]
@matmaxgeds the logic has been updated as proposed. Please check the same project with new import here: http://aims.mop.gov.so/view-project/3593
Please close it if you find it okay.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, sorry that in this case, the import data quality was low. However I am still confused. A project value of 8,400,000 is shown, with a start date of FY2017, and an end date of FY2017, and disbursements for 2016-2020 but they are all zero. 

The project dates suggest to me that there should not even be any disbursement rows for 2016, 2018, 2019, 2020....and the one for 2017 should say 8,400,000 - does this logic make sense, i.e. the disbusement rows available are determined by the start/end dates, and the value of the disbursements is determined by the project value (and vice versa)?
[Project zero disbursements.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3873576/Project.zero.disbursements.pdf)

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the notice, the first issue of disbursements outside of start and end dates does not make any sense. Will rectify it.
The second issue of amount 0 for disbursements is that the Excel sheet does not have information about disbursements and are blank. That's why they are zero.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for all these script tweaks - to come straight to the point, where the project value is greater than the disbursements recorded in the different years, the script should add disbursements in the following order until the disbursements add up to the project value:
1. To years where the project is active where there is a 'null' in the import data
2. If there are no 'null' years, where all years have a '0' for disbursements, these can be treated as null
3. Where there are no 'null' years left to fill, but some disbursements, add the remaining disbursements required to meet the project value to the '0' years.

Hopefully that will cover all situations.

**Comment by matmaxgeds** [comment]
See #412 as second example of this - can close at the same time when done

**Comment by raashidahmad** [comment]
@matmaxgeds Need some discussion on it, as i need some help on it.

**Comment by matmaxgeds** [comment]
@raashidahmad - let's have a discussion on it, I can be available tomorrow afternoon if that is ok for you

**Comment by raashidahmad** [comment]
@matmaxgeds Works for me. Sure, lets talk.

**Comment by raashidahmad** [comment]
@matmaxgeds as discussed on the call have made these fixes:

1. If project value is 0, sum up the disbursements and set it the project value.
2. If project value is less than the sum of disbursements, adjust the project value.

Closing it for now. We may re-open if any adjustments are required.

**Comment by matmaxgeds** [comment]
@raashidahmad - that sounds good. What about the last two case - If the project value is more than the sum of the disbursements?

1. Find the start/end years, and distribute the remaining project value (i.e. project value - existing disbursements) equally to all years when the project was active that have null disbursements and b) if there are no years with null disbursements, then use the years with 0 disbursements to equally distribute the spare project value.

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the guide. I have not covered these cases just with the assumptions:
1. If the imported data is in compliant with the Excel sheet.
2. That we cannot change the disbursements values. 

Do you think the data still needs some tweaks and i should incorporate the scenarios given above? (I am presuming some efforts on it)

**Comment by matmaxgeds** [comment]
NOTE: this may be easier for me to do manually in the excel sheet, but I don't know which version of the sheet you are using for importing now (maybe you have made some changes to it yourself?) - if you prefer me to fix these in the sheet, then please attach the relevant sheet to this issue.

@raashidahmad this is good progress, it seems like there is one last case, that as you point out, requires breaking your rule 2 above (changing the disbursement values). Taking as an example this project: http://aims.mop.gov.so/view-project/687.

1. The project runs for 5 years, from 2017 to 2021
2. There are no disbursements
3. This means that we take the project value, and apply it evenly across all the years, i.e. 8,400,000/5 = 1,680,000 disbursement recorded for each year - and in the case of 2019, in the actual disbursements section, not the planned one, as that will cause problems later

If there were some disbursements, e.g. a disbursement for 2018 was recorded for 1,000,000. Then there are 4 empty years, and we should split the remaining (8,400,000-1,000,000 = 7,400,000) across the 4 empty years i.e. put 1,850,000 in each of the empty disbursement years

If there are no empty years (each year has a disbursement recorded), but the total value is still less than the disbursements, then split the remaining value (i.e. total value - total of existing disbursements) by adding it equally to all future years, i.e. in this case, 2020 and 2021.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for presenting all the analysis and solution to the situation. Let me present you both the situations and you decide what is better in this case:
1. If i make these changes through script, it will require 1 full day, as for the script i will make changes and after that it takes about an hour to insert the data. If it fails, then i will have to make the changes and run the script for insert again.
2. If it takes less time entering the values manual, e.g. an hour or two, i would prefer entering it manual otherwise we will go for the option 1

I am attaching the sheet here for your reference. Please note i have extracted the list of projects from the sheet named as v19-Denmark-plus. I extracted the projects into a separate sheets because with multiple sheets it was creating issues during import.

[Projects.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3951645/Projects.xlsx)

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for the info - let me do it manually tomorrow and send the sheet back to you.

**Comment by raashidahmad** [comment]
@matmaxgeds thank you, well noted.

**Comment by matmaxgeds** [comment]
@raashidahmad - attached is a tweaked project sheet. I have added new columns for 2021, 2022, 2023 and 2024, and removed the disbursement check one. That means on import, the script only has to look at the figure in the 'disb to 2016' column, and share the amount equally over any years where the project is active from (including) 2016 and any earlier.

I have also done some more cleaning up of the dates and the sectors as I saw a few errors had slipped though.
[Projects (matt tweaks).xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3957059/Projects.matt.tweaks.xlsx)

**Comment by matmaxgeds** [comment]
Also - please can you confirm that the 2019 data is going into the box marked "actual"?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for sending the updated sheet. I will take a look on and will get back to you in case of any query. About 2019 disbursements, that is correct.

**Comment by raashidahmad** [comment]
@matmaxgeds The sheet you sent is now imported. Distribution of disbursements issue was tackled in the sheet. Please check it, closing it for now, and we may open if any changes are required.
