### ISSUE TITLE
Logged in as 'UNDP' but UNDP organisation not available?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#404]
Hi Rashid, when I am logged in as the admin user, it has as an organisation 'UNDP' but when I try to put UNDP in the organisation filter, it is not available? Do you know what is happening here?

**Comment by raashidahmad** [comment]
Correct. It type is set as automatic entry not by user. I have changed its type. Please check it under organizations list now. If confirmed, please close it, so that i can look at others then. Thanks

**Comment by raashidahmad** [comment]
Fixed.
