### ISSUE TITLE
WIth 687 projects, the pdf reports are too long (sometimes fail)

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#405]
Please make all of the report tables into tree tables (see further detail in issue #364), and have them unexpanded by default - we can see if this is then small enough to make pdf reports from.

Otherwise, we will have to think of paginating the tables again after perhaps 50 rows, and saying that for people who want more, they have to use the excel export as the pdf report will only print the first page of the table

**Comment by raashidahmad** [comment]
Suggested changes incorporated. Please check and lets see how you feel about it now. Closing it so that you notice it.
