### ISSUE TITLE
Org types import issues

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#406]
I am not understanding where the current list of org types is from. In the import sheet (Re-attached here) there is a much shorter list. At the moment there are org types e.g. 'default', 'government' 'regional NGO' that were not on the list I supplied - or did I make a mistake somewhere?
[2019 Aid Mapping - 4Nov (for import) v19 Denmark plus.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/3870779/2019.Aid.Mapping.-.4Nov.for.import.v19.Denmark.plus.xlsx)

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the notice. I saw the code and found that i have initialized a list of Somali sectors there, i believe somewhere before we agreed to initialize the database with these sectors. But now we have another list of Excel sheets. I will discard the data initialization script for sector types.

**Comment by matmaxgeds** [comment]
Great, thanks.... pleae can you let me know what else is being initialised
so I can review them all as I guesd there are others.

**Comment by raashidahmad** [comment]
@matmaxgeds  Please see the list below:

Pillar 1: Inclusive Politics
	Inclusive Politics

Pillar 2: Security
	Security

Pillar 3: Rule of Law
	Rule of Law

Pillar 4: Effective, Efficient Institutions
	Civil Service Reform / Public Administration
	Planning, M&E and Statistics
	Public Financial Management
	State and Local Governance

Pillar 5: Economic Growth
	Agriculture - Irrigated and rain-fed crops
	Employment and skills development
	Livestock
	Private Sector Development

Pillar 6: Infrastructure
	Energy and ICT
	Other infrastructure
	Transport
	Water and Sanitation (Urban)

Pillar 7: Social & Human Development
	Education
	Health
	Nutrition

Pillar 8: Resilience
	Disaster Risk Reduction
	Environment & Natural Resources Management
	Food Security
	Migration, Displacement, Refugees and Durable Solutions
	Social Protection & Safety Nets

Pillar 9: Gender & Human Rights
	Gender & Human Rights

Other

**Comment by matmaxgeds** [comment]
Hi @raashidahmad this looks great for the sector (Assuming that the first one in each group is the top level and the ones below are imported as the sub-sectors?) Are there any other fields that you are pre-loading or is that it? How about locations, or sector types (where there is one called 'default'!)?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks. For locations i am importing them from Excel sheet and creating them in the DB. For the one 'Default', means we do not have any sector type for this one while importing it from IATI and hence we made it Default so that later we can change it if required. I guess we can use "Other" in this case and can remove the default.

**Comment by matmaxgeds** [comment]
@raashidahmad - as far as I am aware, there is no automatic location import from IATI as we don't have a mapping between the locations in IATI (as there are not location codelists) and the somali locations that you are importing from the excel sheet. This means that for the location IATI data, we are just listing it for the users, but there is no button to transfer the selected ones across into the AIMS, the user can just read what IATI is suggesting, and then makes their own selection from the dropdown. This should mean that there is no need for 'default' as we also have 'UNATTRIBUTED' available for the user to select in that case.

**Comment by raashidahmad** [comment]
@matmaxgeds Sorry for confusion on this. I have not explained that well. We are importing location names from the Excel sheet that we are using for data import.
I have used the IATI word  for "Sector types"

**Comment by matmaxgeds** [comment]
@raashidahmad I think this is best discussed as a call but it is not priority until we have finished the 2019 data entry and reports issues - until then, please just remove the sector type 'default'.

**Comment by raashidahmad** [comment]
Closing it just to make you notice and review. We can discuss it further if any changes are required.

**Comment by matmaxgeds** [comment]
@raashidahmad re-opening as we got off topic (which was originally org_types import) - currently, the org types list includes some that you are initialising includes several that are not in the final list (which I have copied below) - please either adjust the list of organisation types yourself, or make a management page so that I can adjust them in the UI. This needs to include transferring organisations using a deleted org type to a replacement org type.

This also makes me worry about how you have allocated the org types to the different orgs - the orgs tab of the import sheet set that up, did you use it?


Org types - this is taken from the Import sheet tab called 'orgs'
--
Donor Government
Somali-based Fund
IFI/Multilateral
UN Agency
International NGO
National NGO
Federal Government
State Government
Local Government
Other Government
International Private Sector
National Private Sector
Academic, Training and Research
Other
Unknown

**Comment by raashidahmad** [comment]
@matmaxgeds Please check it now under Organization types under management. Please note they are coming from the following sources:

1. From the Excel sheet import
2. From envelope
3. Under data import from Funder/Implementer

Closing just to make you notice, we may discuss if there are any concerns.
