### ISSUE TITLE
Project date import issue

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#407]
When making a time report, I am seeing that there are a lot of projects that have been imported with a year of "1". This shouldn't be the case.
![Screenshot from 2019-11-20 19-24-17](https://user-images.githubusercontent.com/432153/69266396-60e35800-0bcb-11ea-90a6-6abce74d9abf.png)

**Comment by raashidahmad** [comment]
Fixed, please check it now.

**Comment by matmaxgeds** [comment]
Hi,

Now I am getting a lot of projects with a start date of 2005, and a lot with 2009 - any idea what is happening here?

[Time Trend report - 2005 zero financials.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3883991/Time.Trend.report.-.2005.zero.financials.pdf)

**Comment by raashidahmad** [comment]
Hi @matmaxgeds,

Thanks for the notice, i saw the excel document and found that dates have different formats, Somewhere, dd/mm/yyyy, while at some places it is mm/dd/yyyy. I assumed date in single format and it mapped the dates incorrectly. I am still trying to figure out what is happening but will require some time, May be tomorrow i will come up with some clue, as there is lot of data and debugging requires some time.

**Comment by matmaxgeds** [comment]
@raashidahmad Oh, then this is something I also missed. I had done a lot of formatting to try and clean up the dates, but if you can't solve this, maybe I can do it in the excel sheet, just let me know and I will try again

**Comment by raashidahmad** [comment]
@matmaxgeds I will debug this issue today and let you know if that was required. Thanks

**Comment by raashidahmad** [comment]
Please check it now. They year 2005, and 2009 have now only one projects, i checked the projects and they have the right financial year. It gives me a clue for fixed.
