### ISSUE TITLE
Envelope import has some issues

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#408]
There are envelopes of zero for 2003-2013, and for 2023.....

1. The envelope data only covers the period 2018 to 2020 - so there should be no other data - where has this all come from?
2. Please make the chart not show orgs where the total envelope is zero for all the years shown

![Screenshot from 2019-11-20 19-26-24](https://user-images.githubusercontent.com/432153/69266956-77d67a00-0bcc-11ea-9f91-378fa4cdc3e8.png)
![Screenshot from 2019-11-20 19-27-23](https://user-images.githubusercontent.com/432153/69266959-7907a700-0bcc-11ea-998f-35afb5165d19.png)

**Comment by raashidahmad** [comment]
@matmaxgeds In that case we will remove the start and ending year option for filter. By default if you look at the envelope data, it picks up the data from 2018 to 2020. In the snapshot above a user has selected years to be displayed on the report, where no envelope value found for the years provided.

**Comment by raashidahmad** [comment]
@matmaxgeds Please suggest me your opinion, so that i can follow up on this issue then.

**Comment by matmaxgeds** [comment]
@raashidahmad - I think I understand better now, the years option of based on the years for which we have project data? In which case, perhaps we can 

1. limit the year selection to years for which **envelope** data is available
2. Not show rows for organisations which have no reported envelope data in the period selected

Does that work?

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks. The point number 1 is possible. For point number 2, we actually showing data for multiple years in one row, not showing rows for 0 values will not be a solution. I would suggest to limit the years to available data only for now (Means implementing point number 1). The second option will create other situations, and i would like to keep it simple.

**Comment by matmaxgeds** [comment]
@raashidahmad agreed, let's start with point 1, and then see if we still have enough of a problem to create issues. FOr point 2 - I had imagined that we could sum the envelope across the multiple years, and if the total across years was zero, then not include the whole row, but if one year out of e.g. 3 did have envelope data, then we could include it. Perhaps the issue is also that for the envelope data, we are recording 'null' as 'zero'?

**Comment by raashidahmad** [comment]
@matmaxgeds okay i understood it now. Will try to implement both.

**Comment by raashidahmad** [comment]
Fixed
