### ISSUE TITLE
Project list link broken, wasted space on project profiles, change button remove

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#409]
Hi Rashid - 
1. The project list link appears to be broken in the top menu?

2. we are wasting a lot of space on the project profiles with each section having a box with a title, and then a table with a title e.g. funders, implementers etc. Please look at where some of these can be combined.
![2019-11-21_09-59](https://user-images.githubusercontent.com/432153/69322754-ba886880-0c45-11ea-923b-7731df5fe511.png)

3. Also, the 'suggest a change' button **at the bottom** is in the titlebar for 'documents' - please remove it as this is confusing that it might apply to documents.

**Comment by raashidahmad** [comment]
Suggested changes are implemented. Space optimized, Display updated, Button removed
