### ISSUE TITLE
Advanced Search on Data Entry

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#41]
This issue is to discuss adding more advanced search features to the data entry screen.

Rashid has given an important information that "I am fetching only small amount of data from projects both from AIMS and IATI on the very first screen of the data entry. When user types something into the textbox, the data is filtered as with typing the keys. Advanced filter is not feasible for this screen as this requires all the data to be fetched from AIMS and IATI, such as sectors, locations, disbursements, funders, implementers etc. Fetching huge data all at once into the cache is not wise and will not let us develop UI, which is practical. Please see the projects and report pages to see the proposed advanced search for projects." Next step is for Matt to think about this and discuss at MIA

**Comment by raashidahmad** [comment]
This is now updated and fixed with different ideas input at different times.
