### ISSUE TITLE
All spare location % set to 'unattributed'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#410]
When users are entering location data, and remaining percentage (and 100% if no location is specified) needs to be set to 'unattributed' so that the total location percentage always adds up to 100%

**Comment by raashidahmad** [comment]
This issue has been fixed this way:
1. When location/s is/are inserted, the rest of the percentage is assigned to Unattributed. That means 100% is occupied.
2. The UI has a check which do not allow more than 100%, so in this case user can delete unattributed and add another location or edit a location and the unattributed will itself again if required.
