### ISSUE TITLE
Data import - another project where the dates do not match the disbursement years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#412]
Just adding as an example in case useful to test later [Project with 1 year many year disb.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3874575/Project.with.1.year.many.year.disb.pdf)

**Comment by raashidahmad** [comment]
@matmaxgeds Fixed this issue. I will write up some questions on few other aspects. This issue has been resolved this way:
1. Data import stores the project value from Excel document.
2. If import finds project value as zero, it sums up the disbursements and make it the project value.

Second issue is also addressed and now there are no disbursements out of start and end year.
