### ISSUE TITLE
Sorting sectors for reports

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#413]
Hi @raashidahmad - we need to tweak something about how the sectors show in the reports (and this will also solve the issue of too many sectors to make a nice chart):

- [ ] The sectors are hierarchical, therefore if 'parent sectors' are selected in the first sector dropdown, then in the second sector dropdown, it should only show the parent sectors. But at the moment, it shows all sectors - please fix this

- [ ] When I select just the parent sectors in the second sector dropdown then I data from just one parent sector, this means that the reports are not smart enough to use the heirarchy at the moment, please make it so that if parent sectors are selected, then each parent sector shows the data from the sub-sectors underneath it
![Screenshot from 2019-11-25 14-07-48](https://user-images.githubusercontent.com/432153/69543037-0102fd80-0f8d-11ea-9ceb-16ebb2f6793b.png)

**Comment by raashidahmad** [comment]
@matmaxgeds while looking into this issue, i found few facts about data which is happening. 
1. Before, we had a list of sectors with Parent Child hirarchy, i have initialized the sector data with that list.
2. Then while importing the projects from Excel sheet that we have different names for the same sector in the projects import sheet and a sheet you provided somewhere as a list of sectors. For example, We are inserting "Pillar 1. Rule of Law" in the data initializing code, and then in the projects import document it is written as "Pillar 1. Rule of Law - Rule of Law"
3. Is it possible for you to provide me a list of sectors which is consistent with the sector names used in the import data for projects. It will be great help for me.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - I think just a small thing to sort out will solve this:

1. We still have the parent child hierarchy
2. You are initializing both levels, the parent sectors e.g. "Pillar 1: Rule of Law", and also the sub-sectors e.g. "Rule of Law" 
3. The entries in the import sheet e.g. "Pillar 1: Rule of Law - Rule of Law" is a combination of a Parent code "Pillar 1: Rule of Law" and the required sub-sector (because all data is stored at the lowest sector level) which is "Rule of Law".
4. So for the import script, when you find "Pillar 1: Rule of Law - Rule of Law", then you can import it as "Rule of Law" i.e. just the child code.

Does this make sense, i.e. you have the right list for initialising, but the codes in the excel sheet are a combination of the parent and the child sector, so when importing, just take the child sector.

**Comment by raashidahmad** [comment]
Hi @matmaxgeds yes that makes sense, thanks. Let me study it carefully and then try to insert it carefully using script. I will get back to you on it.

**Comment by raashidahmad** [comment]
Fixed. Please review.

**Comment by matmaxgeds** [comment]
@raashidahmad look good :)
