### ISSUE TITLE
One sector not importing quite right -    Economic Growth: Fisheries

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#415]
There is one sector that is not importing quite right, or was this a later adjustment?

![Screenshot from 2019-11-25 15-36-57](https://user-images.githubusercontent.com/432153/69549379-7b397f00-0f99-11ea-878b-d758d53a1a80.png)

**Comment by raashidahmad** [comment]
It is now fixed.

**Comment by matmaxgeds** [comment]
Thanks - but I can still see it this morning?

**Comment by raashidahmad** [comment]
@matmaxgeds Please guide me what is fix in this issue, i misunderstood this task and thought this sector is not imported and now i thought it is imported.

**Comment by matmaxgeds** [comment]
@raashidahmad sure:

"Economic Growth: Fisheries" is not either a parent sector, or a sub-sector. The Parent sector is "Pillar 4: Economic Growth" and the sub-sector is "Fisheries" - can you see how this one is somehow different from all the other sectors that are visible on the sector report? Maybe there is a problem in the import sheet?

**Comment by raashidahmad** [comment]
Okay thanks for the explanation. Got it now.

**Comment by raashidahmad** [comment]
Fixed.

**Comment by raashidahmad** [comment]
@matmaxgeds Some facts about this issue:
For this project: http://aims.mop.gov.so/view-project/562
Using Excel sheet this project is on number: 563, having sector titled as "Economic Growth: Fisheries".
I am looking for other things.

**Comment by raashidahmad** [comment]
@matmaxgeds I have updated their parent sectors through Administration section, and it seems working correct now. Please check it now. Closing it just to make you notice.
