### ISSUE TITLE
2019 Disbursements says 3,300,000 - that is way to much, must be an error somewhere

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#416]
Hi, please check how this field is calculated as it is way too high, I would guess it should be between 1 and 2 billion, so this is almost double.

**Comment by raashidahmad** [comment]
@matmaxgeds I have adjusted the calculations now, and it is now giving this figure 1,317,324,724. Closing this ticket for now.
