### ISSUE TITLE
UNDP not available on project list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#419]
Hi @raashidahmad Rashid,

Albert went to the projects list, and looked for UNDP in the organisations dropdown, but it wasn't there (I confirmed this) please can you confirm what is happening here?

1. There are other orgs from the implementers list there
2. What other orgs might we be missing, and why?

**Comment by matmaxgeds** [comment]
update: fixed for UNDP,  "while initializing the data it was set as source type, while it must be user type"

**Comment by matmaxgeds** [comment]
update: this is linked to having originally used IATI data as a source of test data (before we had the aid mapping data) to populate the AIMS, which means that the org names were from IATI, but the projects were from the Aid Mapping - hence not finding the orgs when searching aid mapping projects.

Solution - 
1. import the organisations (and types) from the aid mapping sheet
2. have a seperate list of IATI orgs extracted from the IATI data, just to use for the IATI search dropdown (and so does not need org_types for IATI sourced orgs)

**Comment by raashidahmad** [comment]
@matmaxgeds agree with the above as discussed. It will be in the next build.

**Comment by raashidahmad** [comment]
@matmaxgeds with new data initialization this has been fixed. All the organizations are now shown as IATI organizations are kept in a separate table. Please check other organizations you were looking for. Closing it and we may open it if there are any concerns.

**Comment by matmaxgeds** [comment]
@raashidahmad please inform Pau that this is now working

**Comment by raashidahmad** [comment]
@matmaxgeds okay, thanks. I had communicated this with Pau two days ago on skype.
