### ISSUE TITLE
Use of tab to search too complex

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#42]
In several places, users need to 'tab' to search e.g. when searching IATI projects by name - this is too complex, we need to find another way - either searching as the user types, or a search button.

**Comment by kndm** [comment]
Can't seem to reproduce this, could you guide me to an URL and procedure in which this can be easily seen?

As of right now I tried the view project and it is working as the user types.

**Comment by kndm** [comment]
@matmaxgeds Pinging here again for reviewing

**Comment by matmaxgeds** [comment]
can no longer reproduce, the 'live search' feature seems to have removed it
