### ISSUE TITLE
Homepage: 2019 disbursements - actual, or total? and adapt to FY

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#421]
- Is this widget showing actual disbursements, or total 2019 disbursements?
- Please make it take the 'year' from the current FY
- please make sure that it will show "FY2020 disbursements" when the FY changes?

**Comment by raashidahmad** [comment]
@matmaxgeds this widget is showing total disbursements both actual + planned, but i realized it must be actual disbursements only, is that correct?
The widget will adapt itself to new financial year automatically.

**Comment by matmaxgeds** [comment]
@raashidahmad, great that it will adjust to the new FY. I think making it actual disbursements only is a good idea, then we can rename it: "INSERT FY disbursements to date"

**Comment by raashidahmad** [comment]
Fixed.
