### ISSUE TITLE
Do not show "sub-sub sectors" if there are none

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#423]
This is for the dropdowns - or perhaps easiest to just delete this classification/category all together given that we are not using it

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
This also needs to apply to the projects list (http://aims.mop.gov.so/projects)......and anywhere else that the sectors dropdown is used

**Comment by raashidahmad** [comment]
This is now implemented as suggested.

**Comment by matmaxgeds** [comment]
@raashidahmad this implementation doesn't really work, now the dropdown menu item shows 'no sectors' this is confusing, it would be better if the entry was not there at all. I was suggesting deleting the whole sub-sub sector classification in the data structure if that is easier?

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for testing the features. Actually, No Sectors means that we want to see the projects that have no sectors, this is actually a sub report under sectors. I tried to adjust the no sector projects report on the same report, that is why.

**Comment by matmaxgeds** [comment]
Aha, so this is not the same issue as: https://github.com/somaliaims/Somali-AIMSUI/issues/341 - I was hoping that we do not need a separate 'no sectors' thing, as they are just like all the normal projects, except that they have 100% for 'unattributed'?

**Comment by raashidahmad** [comment]
I see, this is totally a different report. In fact, it has a different API as the query and logic was different for no sector or no location projects.

**Comment by matmaxgeds** [comment]
1. 'Unattributed' is just like any other sector
2. On data entry, any unused percentage is coded to 'Unattributed'
3. This means it is just shown on the same report
4. 'Not available' >> 'Unattributed'

**Comment by raashidahmad** [comment]
Implemented
