### ISSUE TITLE
Sort columns in report tables

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#424]
At the moment the report tables seem to be in random order? Maybe this will be fixed by the sector ordering field - but until then, please make it aplhabetical

**Comment by raashidahmad** [comment]
@matmaxgeds The reports are now ordered as below:

1. Sectors report:- By sector name, then under sector by project names. Some projects starting with numbers in their name, so the numbers appears top in the sort.
2. Locations report: By location name, and under that projects are sorted alphabetically, it must be noted that some projects contains double quotes in their names, so they are appearing on the top.
3. Time trend report: By years, then underneath by project names
4. By project names, some projects contains double quotes or hyphens, after sort they appear on the top, rest ordered.

Note:- We may update the names of the projects by editing a project through data entry.

**Comment by matmaxgeds** [comment]
@raashidahmad looks good, I had hoped this would also sort the chart columns by alphabetical, or will that need to wait for it to be implemented in the database?

**Comment by raashidahmad** [comment]
Implemented.
