### ISSUE TITLE
Link to a report does not work if sub-sectors selected

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#425]
This link (from the bottom of a pdf report) should return a report showing 3 sub-sectors, but it returns a parent sectors report: http://aims.mop.gov.so/sectors-report?load=true&sectors=19,26,15

**Comment by raashidahmad** [comment]
Fixed. Ids changed after new data import. Please use the link below to verify:
http://aims.mop.gov.so/sectors-report/?load=true&sectors=32,19,34
