### ISSUE TITLE
Organisation type - default?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#427]
We still seem to have organisations coming in under 'default', please can we figure out how these are coming in? See http://aims.mop.gov.so/delete-organization-type/1 these names look likes ones I have typed, but for the 2019 aid mapping import, it is my mistake if I have missed some organisation types (and therefore they are being recorded as default)? Or is it some other issue?

**Comment by matmaxgeds** [comment]
There are also two organisations here: http://aims.mop.gov.so/delete-organization-type/16 which is strange - perhaps these (and the 'default' orgs) are ones where they are in the project import data, but which I somehow didn't include in the 'orgs' import sheet?

**Comment by raashidahmad** [comment]
@matmaxgeds you are guessing it correctly:
1. Default type is added by default if the organization does not have a type.
2. We import the organization types from import sheet, we then map any organizations to these already inserted. If an organization is found which is not mentioned in the import sheet, then new organization is created in the database and default is added its type.

**Comment by matmaxgeds** [comment]
Thanks, closing this as it can be deal with by management users once the AIMS is live
