### ISSUE TITLE
data entry IATI and AIMS projects lists - not need the project start/end dates

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#430]
We can reduce the rows that each entry on the two lists takes by removing the start and end dates - these are no longer needed now that users can a) filter by dates and b) use view detail to see the dates

**Comment by raashidahmad** [comment]
Done...

**Comment by matmaxgeds** [comment]
@raashidahmad great, this now makes it clear that we do not need the "Project title:" part either as that is the only field left, and it is self explanatory. Please remove that too, leaving just the actual project title text.

**Comment by raashidahmad** [comment]
Done
