### ISSUE TITLE
data entry view detail needs to show a bit more detail

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#431]
Please show:

- start/end dates
- project value

On both the IATI and the AIMS 'view detail' screens

**Comment by raashidahmad** [comment]
Done
Note:
1. For IATI where project value or any of the dates is not available it is shown as N/a

**Comment by matmaxgeds** [comment]
@raashidahmad  - thanks, good call on the "N/A"

A tiny adjustment to the text where it says "No member locations to show" or "No member sectors to show".....please remove the word "member" in both cases.

**Comment by raashidahmad** [comment]
Fixed
