### ISSUE TITLE
Error on registering a new user and org

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#434]
![Screenshot from 2019-12-19 10-55-38](https://user-images.githubusercontent.com/432153/71163849-3201e580-224e-11ea-9bc6-dc7d4657d296.png)

**Comment by raashidahmad** [comment]
I am trying reproduce it - Once understood the issue, it will be fixed.

**Comment by raashidahmad** [comment]
Closing it, as i did not face it, we may re-open if found during testing.
