### ISSUE TITLE
'Stacked bar' is not passed to the report link

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#435]
I made a report which uses the stacked bar type, which I wanted to share, but the link only goes to the normal bar chart http://aims.mop.gov.so/locations-report?load=true&locations=3,6&syear=2019&eyear=2020, the link should also note that it is a stacked bar chart

**Comment by raashidahmad** [comment]
@matmaxgeds the chart types only belong to visuals and are handled by the client or UI, we do not request api server to provide us with the chart information etc, links are being created by server using the passed data. Logically thinking i would suggest not to put chart types in the link, but let me hear your opinion.

**Comment by matmaxgeds** [comment]
noted, moving to 'not delivering as would take too long'

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the update. Unfortunately, i did notice your comment lately, It has been implemented, you are right, it took about 2.5 days. As link generation belongs to server, it will be generated only pressing View or Update report. Closing it to make it open for tests.
