### ISSUE TITLE
Notifications: Project added to organization

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#438]
Please can we also be clearer on what this email is for:a) a new project is added to your organisation, or b) new organisations are added to a project from your organisation?

We need separate emails for both a) and b) and then they can be clearer what they are about.

**Comment by raashidahmad** [comment]
@matmaxgeds "Project added to organization" is an email message text that we can change using email messages list. This is totally editable message so closing it for now.

**Comment by matmaxgeds** [comment]
Thanks, I know I can edit it, but here is the message I get:

"Dear user,
New project added to organanization
New organization/s added to the project: A new test project
Added organization/s
    UNDP,CARE,Creatives Associates
If you need further assistance, please submit a help request via the contact form in the AIMS
AIMS Support Team"

It says both:
a) New project added to organanization.....this is when there is a new project added
and
b) New organization/s added to the project.......this is when an existing project has new organisations added

So it is confusing.....maybe it needs to be split into two messages, one for each scenario?

**Comment by raashidahmad** [comment]
It is now fixed by applying proposed change for UI on Email messages page. Please see the message having subject "Organization added to project", You may update the subject and message now, the system will only produce facts:
For example in this case:
Project title: ----
Organization/s
1. ---
2. ---
