### ISSUE TITLE
Data entry - just one 'next' button

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#44]
At the moment that is a second 'next' button as a tab - please remove it as we want to train users to look in the same place each time for the 'next' button

**Comment by kndm** [comment]
@matmaxgeds I can't seem to find this 'next' button, could you please screenshot it? I tried looking through the source for the data entry component but there really isn't anything for it.

**Comment by matmaxgeds** [comment]
![screenshot from 2019-02-21 09-32-24](https://user-images.githubusercontent.com/432153/53154703-a848a380-35bb-11e9-9483-da25a231ccb5.png) see in the top left the extra tab

**Comment by kndm** [comment]
Issue has been resolved.
