### ISSUE TITLE
2020 changeover

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#440]
Now that we are in 2020, the homepage text on the far right for the disbursements changed to 2020, that is good but:

- [ ] This should be the FY, not the calendar year, so it should show "FY 2020"
- [ ] The disbursements amount stayed the same, I would have expected it to change as well

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for reporting the bug. I am sharing some facts about this:
1. Our rental server is located somewhere in USA. The year was not changed by that time, so it was picking up disbursements for 2019 from there.
2. To display the current year on the Home page it is picking it up from the user system. 
3. We are talking about FY by tomorrow, as there are some questions related to this.

**Comment by matmaxgeds** [comment]
Updating during our skype:

1. It would be good it both the title, and the data used the same source for changing over
2. Change this to show the current FY
3. FY fixes in #356 will then fix the rest of the issues

**Comment by raashidahmad** [comment]
FY and disbursements both are taken from the server now.
1. FY changes when settings for the financial year start are matched. e.g. in this case 1st of the April

**Comment by matmaxgeds** [comment]
@raashidahmad thanks....this seems like a smart solution
