### ISSUE TITLE
Disbursements entry - button to spread equally

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#443]
On the financial data entry screen, please can we have a button to spread the remaining disbursements equally over future years, i.e. look at the project value, subtract the disbursements amounts entered for the previous and current year (actual and planned) and then divide the remaining amount by the number of future years, and enter it equally for the user?

**Comment by matmaxgeds** [comment]
@raashidahmad 
- Button name: "Split remaining disbursements equally in empty cells"
- Logic: take project value, subtract existing entered disbursements, spread remaining project value equally over any empty cells, ignoring the 'actual' cell, and using the 'planned cell' for the FY that has two entry boxes.
- Location: at the bottom of the text boxes

**Comment by raashidahmad** [comment]
@matmaxgeds I have done it slightly different.
1. For example, if all the boxes are empty, actual + planned, it will split the amount equally across all the years.
2. In case, if there are some already filled, it will equally split the value into the vacant boxes or years.
Closing it, we may re-open if there are suggestions.

**Comment by matmaxgeds** [comment]
That sounds good.

@raashidahmad Please confirm that it still ignores the 'actual' box for the current year, and just uses the 'planned' box?

Sorry to re-open just to ask the question, please close when answering

**Comment by raashidahmad** [comment]
@matmaxgeds confirm, in the new deployment made just now, changes made and tested.
