### ISSUE TITLE
Data entry....."save", and new button, "go to next"

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#444]
When the user tries to save data on first real data entry screen, this works, but then nothing happens, so the user also needs to also have 'next screen' button (which also saves before moving). This should apply to all the also on the financials screen, and all the other data entry screens

**Comment by matmaxgeds** [comment]
@raashidahmad - confirming no triggers, just user input, and just put it next to the save button, or on the bottom right for the sectors/locations screen

**Comment by raashidahmad** [comment]
Implemented
