### ISSUE TITLE
Sector, locations, Markers page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#447]
Hi,

Still some cleanup needed here - sorry for the poor annotation.

I assume if I was using an IATI/AIMS source project, then it would have come up with the icons to add sectors and locations from the source material?

![Screenshot from 2020-01-07 22-54-11](https://user-images.githubusercontent.com/432153/71929107-35c3c080-3199-11ea-8f90-d5c8b4fe87cb.png)

**Comment by matmaxgeds** [comment]
FYI, the suggestion is still that Markers should get their own page to make more space for you.

**Comment by raashidahmad** [comment]
@matmaxgeds Suggested changes made, and deployed to prod server only.

**Comment by matmaxgeds** [comment]
@raashidahmad great, a big improvement.

Please can we move the 'next' button out of the locations box and put it below as it does not relate to locations, but rather to the whole page

**Comment by raashidahmad** [comment]
Adjusted
