### ISSUE TITLE
'next' bottom is always in bottom right, never in the box of another field

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#448]
Hi, we really need to standardise the 'next' buttons.

- On the basic info page, it is in the box for 'resources', above resources, below descriptions
- On the financials page it is in the disbursements box
- On the sectors and locations page, it is in the locations box
- On the markers page, this is the closest to being good UI, it is in the bottom right, at the end of the data entry, not in any other box

Please in all cases, put the 'next' button, bottom right, not in the box of another field

**Comment by raashidahmad** [comment]
Adjusted
