### ISSUE TITLE
Bug - when editing disbursements - get error when remove and replace same value

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#449]
Hi @raashidahmad on prod, I went to a project, and removed a disbursement, then entered the same amount, and got the error message shown....but if I removed and added the same amount, why is there an error?
![Screenshot from 2020-01-08 23-50-58](https://user-images.githubusercontent.com/432153/72019208-8f93bb80-3269-11ea-84d8-398196c14ee6.png)

**Comment by raashidahmad** [comment]
Fixed
