### ISSUE TITLE
data entry - hitting [enter] to search selects 'next' but not wanted

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#45]
For data entry, if you type in the data entry bar and then hit [enter] it moves you to the next page, even though you hadn't yet selected the projects you wanted - hitting [enter] is common and so shouldn't have this effect.

Please replace the 'next' button by the search bar with a 'search' icon button. The search bar can be made shorter, and a new 'next' button can be inserted. The process should only proceed when a user actively clicks next

**Comment by kndm** [comment]
@matmaxgeds Just wanted to point out that the search is currently being done on the spot, meaning that clicking for a search button is counter-intuitive in the sense that the search will usually have finished by the time they finish typing the search term.

Do you reckon we still need a search icon?

**Comment by kndm** [comment]
@matmaxgeds A small preview, the functionality of pressing enter and instantly going to the "next" button is gone, just need confirmation on the search button and whether this size is good enough or not.

**Comment by matmaxgeds** [comment]
Please keep the search button for now - I think no button may confuse some people - where do I see the preview?

**Comment by kndm** [comment]
![image](https://user-images.githubusercontent.com/6158743/53301267-07e0d080-3894-11e9-92a1-51527c3c67bd.png)

**Comment by matmaxgeds** [comment]
1. Please put the 'next' button back to its normal position aligned right
2. Please put the search button back
3. Please change the search bar text to 'enter keywords to search existing
and source projects'

**Comment by kndm** [comment]
Understood and to be seen in upcoming commit.
