### ISSUE TITLE
Bug - seem to have lost the 2020 Actual and 2020 planned

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#450]
Only one field is shown......the current FY does not have both actual and planned?

Also, we need to help icons for each FY in the disbursements, not just one of them.
![Screenshot from 2020-01-08 23-54-50](https://user-images.githubusercontent.com/432153/72019475-1052b780-326a-11ea-9d0f-6a8493d6c385.png)

**Comment by raashidahmad** [comment]
@matmaxgeds I am working on Financial year change effect on projects already entered. A complex algorithm has been written, Spent about 4 days on that Algorithm, still testing and fixes continued. Going to discuss that in today's meeting.

**Comment by matmaxgeds** [comment]
@raashidahmad - this is a complicated one (for the algorithm) that I had not seen - when we change the FY, we need to re-allocate the disbursements that are already entered. I suggest that this should work by dividing the amount that is entered by 12, and allocating each 1/12th to a month, then as the months get rearranged to other FYs, then the disbursements can be moved with. Does that make sense?

**Comment by matmaxgeds** [comment]
@raashidahmad - please add your complex situations here, and I will try to do each one as an excel sheet

**Comment by raashidahmad** [comment]
@matmaxgeds Keeping it open until you review the latest build.

**Comment by matmaxgeds** [comment]
@raashidahmad adding the FY conversion example here:
[FY conversions.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4090432/FY.conversions.xlsx)

Grateful to hear if this solves your needs for a general solution.

I think it should be run on all projects, not just active ones.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for providing the example. I started writing an algorithm for the example provided in the Excel sheet. While testing the steps with another example,  i got stuck and need help on that. Please use the link below to reach the Excel document and understand the issue.
https://docs.google.com/spreadsheets/d/1yw-tw7lX3EAc6zIO5eGxJZzywR5RS2Xh7FTtNVpjS9o/edit?usp=sharing

**Comment by matmaxgeds** [comment]
Thanks for the sheet Rashid, I added in answers where the question marks were

**Comment by raashidahmad** [comment]
Thanks for the suggestions and spending time on the sheet, however i implemented the adjustments comparatively using simple Algorithm and changed the algorithm before i get new changes in the sheet. Presented for review in the current build.
