### ISSUE TITLE
Adjust the sector mapping UI?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#451]
Hi @raashidahmad  - unfortunately the sector mapping UI is a bit too complex.
Please can we try the following layout instead - let me know if this would be hard to implement.

FYI - will add the template this evening

**Comment by raashidahmad** [comment]
@matmaxgeds Please provide with the layout, we can then discuss if that layout requires more or less changes in the back-end and front-end both.

**Comment by matmaxgeds** [comment]
Sorry, this had slipped my mind - please see attached. I am trying to make as few changes as possible to the current one. [Sector mapping UI.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4136364/Sector.mapping.UI.xlsx)

Please can we also separate the 'sector mappings' onto it's own management page with it's own entry in the menu?

**Comment by raashidahmad** [comment]
@matmaxgeds the proposed layout suggests that every IATI sector has only one mapped sector in Somali sectors. Please confirm so that i can change the data model, and rewrite APIs.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for checking, confirming - trying to keep it as simple as possible. If the users don't agree with the mapped sector, they can manually select another national sector.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the confirmation.

**Comment by raashidahmad** [comment]
@matmaxgeds Suggested changes implemented.
