### ISSUE TITLE
time trend report - sector and location filters

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#452]
- [ ] The sector filter for the time trend report does not allow selecting the sector level, the first dropdown for the level is needed, just one sector at a time
- [ ] Please can we have a location filter as well, just one location at a time

**Comment by raashidahmad** [comment]
Sector and locations filter added now on the Time trend report.

**Comment by matmaxgeds** [comment]
@raashidahmad this works great, thanks
