### ISSUE TITLE
Sector report not using locations filter percentages

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#459]
See for example project 871, because we added the sector filter to the location report, and the location filter to the sector report later, it is using these for filtering the projects, but the percentages are not being applied to the data.

**Comment by raashidahmad** [comment]
I am just copy pasting the text i sent on the email about this:
"4.	Reports are now loaded on the page load. About a point, where it was asked to take the location percentage on sectors report, and sector percentage on location report, we were missing a point and I have the view about this below:
a.	If we select a location on sectors report, that means take the projects for the selected location and show the values by sector percentage, if we apply both the percentages here, I do not think so, that is what user is expecting, and the same point is for locations report.
b.	Note:- While looking at the reports API, I found a formula was applying twice, and hence it was not showing the expected values. Please check it now and I believe it will be now as expected."

Closing this as per my understanding, we may discuss it in the meeting.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad 

1. Using this project as an example: http://aims.mop.gov.so/view-project/58 - because there is only one sector, so we are just testing here if it is applying the location % on a sector report.
2. And this report: http://aims.mop.gov.so/sectors-report/?load=true&projects=58&syear=2019&locationId=4&ctype=1
3. Below is a screenshot:
4. First issue is as discussed, but please can you apply both percentages to all three values i.e. the project value, the planned disbursements, and the actual disbursements - I do think this is what the user is expecting. i.e. the project value should be 33% of 3,622,798
5. Something else is strange here, it shows '0' for actual disbursements, but the project profile shows that there was a disbursement of $1,021,398 in FY 2019, so I would expect something in the actual disbursements?

Thanks for sorting out these last few issues.

![Screenshot from 2020-01-30 20-27-24](https://user-images.githubusercontent.com/432153/73478575-fdca2a80-439e-11ea-9df2-e7a74debc0a1.png)

**Comment by raashidahmad** [comment]
@matmaxgeds While trying to understand what is happening with this request, i amend the formula for dates or FYs and presenting here:
1. If only Starting financial year is selected and ending financial year is not selected, in this case, it means that pick up all the projects that have starting financial equal to selected.

2. If only Ending financial year is selected, that means select all the projects whose end date matches with the selected Ending financial year.

3. If both Starting and Ending financial years are selected, that means select all the projects whose starting financial years are greater than or equal to the starting and ending year less than or equal to the ending selected.

Please share your view, is that correct? If this is correct the above query will have a different result, and it will select all the projects that have starting year equal to 2019.

**Comment by matmaxgeds** [comment]
@raashidahmad - maybe this way is clearer:

- the start/end year on the reports does not refer to the start/end year for the projects, it refers to the start/end year for the report, so if a project has a start year of 2015 and an end year of 2019 and the report is set to cover from 2016 to 2018, then it should be included in the report (at least the part or the project from 2016 to 2018), as the project is active during the period of the report.

But this does mean that we need a way to split the project value first because of the dates, and secondly because of the locations/sector.....I will leave a separate ticket for that

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the explanation, please see few questions related to this:
1. What if only starting year or ending year is provided. How shall the report behave.
2. On sectors report if location is selected, then this means:
     a) For every project first select the project value equal the percent of location. Then take that  percent and take out the percent for the sector. In this case, if starting or/and ending year is provided, how to get the actual and planned disbursements. I need to apply the location percentage and then sector percentage on that disbursement value. Is that correct?

Sorry for too many questions, trying to confirm, as later on changes will require more time and efforts

**Comment by matmaxgeds** [comment]
@raashidahmad good questions,

1. If no start date, take everything back to the beginning, of no end date, all the way to the end/last project
2. Correct, apply exactly the same double percentage process to all three values e.g. value, actual disbursements, and planned disbursements

**Comment by raashidahmad** [comment]
@matmaxgeds noted, thanks.

**Comment by raashidahmad** [comment]
Suggestions implemented. Presented for review.

**Comment by matmaxgeds** [comment]
@raashidahmad leaving closed here as remainin bug is described in https://github.com/somaliaims/Somali-AIMSUI/issues/468
