### ISSUE TITLE
Locations and sector reports - show empty fields

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#460]
Not sure if this was a previous ticket or not, but from Gele's user testing, it is clear that it would be useful to always show the empty fields on sector and location reports.

**Comment by raashidahmad** [comment]
@matmaxgeds need help this, empty means Unattributed or is this something else?

**Comment by matmaxgeds** [comment]
Empty means that there are no projects assigned to that field - does that help?

**Comment by raashidahmad** [comment]
@matmaxgeds Does that mean do i need to revert No location, and No Sector option?

**Comment by matmaxgeds** [comment]
@raashidahmad no, just that if there are projects, but none for the location Hiirshabelle, that we still show Hiirshabelle on the charts/table, just with no amounts - does that make sense?

**Comment by raashidahmad** [comment]
@matmaxgeds now understood, thanks, will do a follow up and revert in case if there is any issue to discuss.

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, this is really helpful
