### ISSUE TITLE
Very short list of organisations in reports

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#461]
The organisations dropdown in the reports (I tried a sector report) is looking very small (about 15 orgs) please check that it is pulling from the right place?

**Comment by raashidahmad** [comment]
@matmaxgeds on this report somewhere in the previous ticket the request was that to show only those organizations on the reports that have envelope data. Is that a correct idea or do you want any changes to it?

**Comment by matmaxgeds** [comment]
@raashidahmad this only applied to the envelope report, for the other reports, we should show the whole list. Sorry if this was unclear

**Comment by raashidahmad** [comment]
@matmaxgeds noted this, will fix in the upcoming build.

**Comment by raashidahmad** [comment]
Done
