### ISSUE TITLE
Project list - renames

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#463]
rename "-- All projects --" to "-- Select/Search project titles --"
But keep the same default of "all projects" for the filter if it is not changed by the user.

Please also rename "Keywords from description" to "Search project descriptions"

**Comment by raashidahmad** [comment]
@matmaxgeds When no item is selected we will show --All projects--, when any item is selected, we cannot show any text, instead selected items are shown. What i have done to incorporate the suggestion above is that, when you open the projects drop down, You will see the text "Select/Search project titles", this is where you write the text.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, that is reasonable
