### ISSUE TITLE
Email messages management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#465]
http://aims.mop.gov.so/email-messages

1. I am not sure I understand what is the difference between the message and the footer message. Please remind me why we need both? And why is the footer a required field?
2. I don't see where to view the text that is produced by the system - if I can't see that, it is very hard to write the message to come with it?
2b. I think it might be better to reduce the system generated text to just the facts e.g. "Project name: XXX" or "Organisations: XX, XX, XX" - let's discuss.
3. Is the message about adding orgs from IATI still needed, as we are not adding IATI orgs directly into the AIMS any more?
4. Please separate off the 'email users' function into it's own management page as it is hidden at the moment.

**Comment by raashidahmad** [comment]
Following changes are made:
1. On the edit message page, under the view following things are now shown:
     a) Header text line that will go above the facts produced by the system.
     b) The line below is facts and will be generated by the system
     c) The footer line, optional, may go below the facts.
2. Message for IATI organization notifications is now removed
3. Email user separated as a standalone menu item

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad is there any way that we can get an idea of the data that the AIMS will insert e.g. using 'EXAMPLE PROJECT' etc....otherwise it is very hard to write the text without knowing what the system will put in the middle? E.g. instead of the phrase "Text produced by the system will go here"

**Comment by raashidahmad** [comment]
@matmaxgeds To make it easy to understand the UI, i have updated the text on this page, and sorry for not explaining it well. I agreed to your idea of limiting the system to only generate facts. So system will only generate facts and not any text other than the following:
1. Dear user, in the header
2. Footer line, if not set, default footer line will be shown.
3. AIMS Support (Signature)

Please note that user registration, and password reset produces some text and links, and do not change it from the Email message UI. I have used the provided text. See below the UI.

![Email_Message](https://user-images.githubusercontent.com/2605356/73768698-4ae13e80-479b-11ea-8d22-88d8504bb63e.png)
