### ISSUE TITLE
Exchange rates management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#466]
This is too complex: http://104.140.103.36:81/manage-exchange-rate-usage - I think I know what this is meant to do, I am am not sure how the setting work - can I get an explanation of the three fields?

Can we either give it it's own entry on the management menu, or put the tabs with the rest (not as some sort of sub-menu), as users will get stuck in the UI?

**Comment by raashidahmad** [comment]
@matmaxgeds We are no more using this feature. We agreed to use the annual exchange rates only, using the openexchange rates api without user intervention, and allowing the user to enter it manually when required.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, so lets remove the un-needed pages then

**Comment by raashidahmad** [comment]
@matmaxgeds noted. Will do the required and fix in the upcoming build.

**Comment by raashidahmad** [comment]
Done
