### ISSUE TITLE
Bug: projects list error

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#467]
Hi @raashidahmad maybe this is liked to the port change - I am getting an error when viewing the projects list - see pic

![Screenshot from 2020-01-30 11-46-38](https://user-images.githubusercontent.com/432153/73451365-1ff88400-4370-11ea-86c3-68c9fa77c253.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Not sure, but i can see the list of projects, i will keep testing if i could debug any issue.

**Comment by raashidahmad** [comment]
@matmaxgeds i could not find any issue during the testing, one possible issue can be when you press click and a connection failure occur. For now closing it, if we face it again, we may open it, but please with steps to reproduce if possible.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for checking, I also can't get it to come back :)
