### ISSUE TITLE
Bug: date filter not operating?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#468]
This report has a start year of FY2019 http://aims.mop.gov.so/sectors-report/?load=true&syear=2019&locationId=4&ctype=1 but a project with an end year of FY2018 is showing up? Or am I missing something?

**Comment by raashidahmad** [comment]
Fixed, randomly tested and found correct.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad I am providing some more information - see the two PDFs, one shows a report that I ran, the other shows one of the projects that is appearing in the report (shows projects for Galmadug from FY2019 onwards)

In the report, the highlighted project is shown with zero value in the report, but when I look at the project profile, it has a value of 1 million for FY 2019, of which 33% is for Galmadug, and also small planned expenditure for 2020 which has 33% for Galmadug, but neither of these are appearing?

[2019 Galmadug sector report.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/4171121/2019.Galmadug.sector.report.pdf)
[2019 Galmadug sector report - example project.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/4171122/2019.Galmadug.sector.report.-.example.project.pdf)

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for sending examples, helpful. This has been fixed. Please check and close if works.

**Comment by matmaxgeds** [comment]
@raashidahmad I ran this report: http://aims.mop.gov.so/locations-report/?load=true&locations=3&sectorId=11&ctype=1 which includes this project: http://aims.mop.gov.so/view-project/11 - but in the report, the project value is given as 33 million, but in the profile it is just 6 million, please can you have a look at the maths, as I suspect something is wrong somewhere?

Because we are having so much trouble with these, I am thinking about dropping the project value fields from all the reports - how does that sound to you?

**Comment by raashidahmad** [comment]
@matmaxgeds the suggestion sounds okay to me, just to be informed as a requirement somewhere in similar ticket we were looking for splitting the project value by date filter, we do not have any other way, but get this value from disbursements.
But to overcome all this complexity, i agree to remove the project value from all the reports, will follow up.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, let me double check all the reports this morning and confirm the removal.

**Comment by raashidahmad** [comment]
@matmaxgeds okay sure, in wait, until you confirm.

**Comment by matmaxgeds** [comment]
@raashidahmad confirming, as it is only on the sector and location reports anyway.

**Comment by raashidahmad** [comment]
Suggested changes implemented.
