### ISSUE TITLE
Adjust project value based on the date, sector, location

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#469]
We should also apply the sector/location percentages to the project value in reports. Also the date, so use the dates of a report, to initially set the project value to the actual/planned disbursements that are valid for the report dates, and after that apply the %'s from the sector/location.

**Comment by raashidahmad** [comment]
@matmaxgeds The complexity here is we enter the project value as a single entry and not against financial years. We can show the disbursements using date filters, but cannot split the project value by date filters.

**Comment by matmaxgeds** [comment]
@raashidahmad - good point. Luckily the disbursements add up the the project value and they have dates so hopefully we can do it that way?

**Comment by raashidahmad** [comment]
@matmaxgeds Noted, it gives me clue that i need to sum up the disbursements instead of taking the project value as a single numeric entry.

**Comment by raashidahmad** [comment]
@matmaxgeds suggested formula has been applied to Sectors, and Locations reports. Time trend reports has sectors filter, where user can select multiple sectors, it is not possible to apply multiple sectors percentages, so percentage formula for sectors, and location is not applied their to keep the options it consistent.
