### ISSUE TITLE
Remove 'save project' button

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#47]
on first data entry screen - 'save project' is visible in the bottom right - this is not needed, as the page should autosave each field.

Instead there should be a 'next' button in the standard position (we are trying to train the users'. It would also be best if the 'next button' is also always visible i.e. does not scroll with the data entry form so that it is always visible

**Comment by raashidahmad** [comment]
Next button placed on all tabs. As we do not have very long pages, in most cases, the page does not get length for scroll. Closing this, if you do not agree with current fix, please re-open.

**Comment by matmaxgeds** [comment]
Good solution - thanks
