### ISSUE TITLE
Management users - management page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#470]
We need a management page where any management user can add (from the list of normal users) or remove other management users (not themselves) from a list.

To keep it as simple as possible, just email requesting a yes/no to all users affected, with action taken in the case where there is no response. 

We will not worry about the complexities of bad actors trying to take over the database. If this happens, then the users can restore a backup.

**Comment by raashidahmad** [comment]
@matmaxgeds a few questions related to this task:
1. A management user will create request to promote/demote a user account to management user.
2. Request will be sent to whom? who can then approve or reject? To other management user or the user who is going to be promoted/demoted to him/her?

**Comment by matmaxgeds** [comment]
@raashidahmad trying to keep this as simple as possible as it could easily get very complex so just making it work now, if time later, can improve.

1. Any management user can promote/demote
2. Last remaining management user cannot demote themselves.

If we had more time later:
2. If promote, request sent to all other (cannot vote on own things) management users, and to the single concerned user, needs one other management user and the concerned user to vote to agree. and if no votes, nothing happens. If only one other management user, is just waiting for the user to be promoted to approve.
3. If demote, same request to all other management users, needs one other management user to approve, (not send to the requesting user), and if no 'no' votes, it implements within a week.

**Comment by raashidahmad** [comment]
@matmaxgeds you are right, agree, will implement it in the simplest form that management user can promote or demote, later can be improved.

**Comment by raashidahmad** [comment]
A simple version of this feature is implemented as suggested.

**Comment by matmaxgeds** [comment]
@raashidahmad looks good, thanks
