### ISSUE TITLE
Excel Data export years need to be FYs not calendar years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#471]
To do the excel data export, it says starting year and ending year, these just say 2019, 2020 etc, so are they calendar years of financial years?

If they are Financial Years, then I would expect FY 2019, FY 2020 etc in the dropdown? If they are calendar years, please change the dropdown to work on FYs.

**Comment by raashidahmad** [comment]
Fixed.
