### ISSUE TITLE
Add filters for 'Markers' to the reports

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#472]
@raashidahmad please can we do this by adding two dropdowns, one to select the marker to filter, and the second to select the choice for the options relevant to that marker?

Maybe start with the location report?

@mohamedgele22 I think this is what you are wanting?

**Comment by raashidahmad** [comment]
Implemented.

**Comment by matmaxgeds** [comment]
That looks and works great @raashidahmad - in the queue is therefore to apply this to all the other reports (not the data export), and the projects list. But not priority over the other remaining issues.

**Comment by raashidahmad** [comment]
@matmaxgeds as already sent email on related to this issue. I am closing this issue, and we may create new issue for Budget report, if any changes are suggested later on.

**Comment by matmaxgeds** [comment]
@raashidahmad - this looks great, thanks
