### ISSUE TITLE
Bug - hardcoded link when approving users

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#475]
@raashidahmad I got this error when I approved a new user - looks like something is hardcoded?

Please do a check of the whole codebase for this!

![Screenshot from 2020-02-08 18-54-13](https://user-images.githubusercontent.com/432153/74089145-d7934180-4aa6-11ea-88b2-e221f7f114b5.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Did you try it again? One possible situation i can think of is that you keep open this page under a tab and from another tab, if someone logs out, you will lose the login token. But i am testing it and trying to produce this error. If you get it again, please assist me how did you produce it while testing.

**Comment by matmaxgeds** [comment]
@raashidahmad I can recreate it (I guess also how it originally happened) if I log in, go to the notiications page (which is fine) and it comes if I then refresh the page (e.g. to check if more notifications have come), that seems to log me out.

**Comment by raashidahmad** [comment]
@matmaxgeds I have tested it again and it worked fine. Please follow these steps and test again, it must work:
1. If you are logged in, please logout, and register a new user to your organization
2. Now login to your account again, go to notifications, you will find the one. Approve it and wait for few seconds, the application will refresh itself, to get the updated notifications, no need to refresh the application manually.

Closing it and we can open anytime if you find any issue with that.

**Comment by matmaxgeds** [comment]
@raashidahmad so the issue seems to be that if a user manually refreshes the page e.g. by pressing F5, then it seems to log them out - is there any way we can prevent this happening?

**Comment by matmaxgeds** [comment]
presuming some other issue has solved this so closing here
