### ISSUE TITLE
data entry: the locations dropdown should only apply to the AIMS orgs list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#478]
We do not have locations for the IATI activities list, so the location dropdown should not affect it, please make the locations dropdown only affect the AIMS projects list.

I think I asked before, but the best thing would be for the location, sector and org dropdowns to be above the list they apply to, with the ones that apply to both (text search and date) to stay across the top like now.

**Comment by raashidahmad** [comment]
Suggested changes fixed in another relevant issue.
