### ISSUE TITLE
data entry: the sector dropdown on the first page needs splitting into three

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#479]
Above the AIMS projects list, it should only have the Somali AIMS sector type, above the IATI projects list, it needs to have both the sector type dropdown (just showing IATI sourced sector types), and then a second one for chosing the actual sector.

**Comment by raashidahmad** [comment]
@matmaxgeds it would be helpful if you can provide me with some layout, i am little confused how to arrange data entries.

**Comment by raashidahmad** [comment]
For assistance, please see the current layout, so that any suggestions may fit in the current layout.

![Data_Entry](https://user-images.githubusercontent.com/2605356/74508376-bdcb8180-4f20-11ea-88bb-30d6b2fc92be.png)

**Comment by matmaxgeds** [comment]
Does this help? AIMS sector only needs the National Sectors
![Splitting sector dropdown](https://user-images.githubusercontent.com/432153/74527350-19e8d280-4f2e-11ea-8464-25c4b4a526ee.png)

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for depicting the idea, it is helpful.

**Comment by raashidahmad** [comment]
UI changes implemented.

**Comment by matmaxgeds** [comment]
@raashidahmad great - please just rename the "--Sector Level--" to "-- AIMS Sector level" and the one below to "-- All AIMS sectors --" so that it is clear which list they refer to.

**Comment by raashidahmad** [comment]
Done
