### ISSUE TITLE
data entry: source data entry is only accessed via the project name field

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#480]
At the moment, until the user clicks to 'save data' the source data button is only appearing next to the project name field, so if a user does manual data entry for the project name, they will not think to use source data entry for any other field.

1. please can you work out how to make the source data buttons appear from the start? 
2. Please put separate source data buttons (and pages) for the dates, for the currency, for the project value, for the financing type3. Please also make the IATI source data buttons a unique colour - as at the moment it is the same colour as the 'Add resource' button
4. And at the moment, the start date and end data '>>' are not working to transfer the dates into the boxes.

![Screenshot from 2020-02-08 22-43-01](https://user-images.githubusercontent.com/432153/74091826-25b73d80-4ac5-11ea-81b2-ae9b58a8e891.png)
![Screenshot from 2020-02-08 22-46-00](https://user-images.githubusercontent.com/432153/74091827-27810100-4ac5-11ea-9d17-c9309ddec424.png)

**Comment by raashidahmad** [comment]
@matmaxgeds to keep the UI simple, 
1. Source data buttons are shown in front of all the data entry fields, except funding type. 
2. When title button is pressed, only title text field and description is shown. 
3. Similarly, only relevant button is visible from the source, for example, when title is selected, only title text field is shown, and source button for title is available only.
Please see the attached snapshot for idea:

![Data_entry_source](https://user-images.githubusercontent.com/2605356/74680889-cc958b00-51e3-11ea-9f25-40f0b6a4687c.png)
