### ISSUE TITLE
sector/location entry: 'next button' should also active 'save sector/location'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#483]
Clicking the 'next' button on this page should automatically trigger the save sector and save location buttons, otherwise users might click next and not realise that their selections were not saved

**Comment by raashidahmad** [comment]
@matmaxgeds In order to avoid complexities (Calling both sectors/locations on a next button have some complexities ) it has done this way:
1. User is prompted if there is any unsaved data when clicked on next

**Comment by matmaxgeds** [comment]
@raashidahmad this sounds sensible given the complications
