### ISSUE TITLE
data entry: split remaining amount equally does not work with decimals

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#484]
This button needs to work with whole numbers, in the screenshot I used the button, and it created an amount that did not work i.e. 8000001, so the equal split needs to have the final year adjusted up/down by 1 to make sure that it works with round numbers

![Screenshot from 2020-02-08 22-56-54](https://user-images.githubusercontent.com/432153/74092035-ad9e4700-4ac7-11ea-979d-03499854ec7a.png)

**Comment by raashidahmad** [comment]
Adjustments made.
