### ISSUE TITLE
Filtering projects by disbursements

### ISSUE THREAD

**Issue by mohamedgele22** [somaliaims/Somali-AIMSUI#486]
Please I want to filter projects in the projects list by disbursements, for example, A. Projects with amount: 0-10 million  B. Projects with amount 10-50 M   C. Projects with amount 50+ M.

**Comment by raashidahmad** [comment]
@mohamedgele22 noted, Please see some queries below?
Questions
1. Is this filter is about disbursements in specific year or project value as a total? For example, filter projects having value greater or equal 5 million
2. It is supposed that the values will be filtered by default currency (In this case USD)
2. We have year/s filter as well, so i guess project value will not work here properly

@matmaxgeds Please share your views and guide me in terms of UI and formula for this feature.

**Comment by mohamedgele22** [comment]
1. yes. filter projects, for example, projects have value of 5 million, then it will be in the filter selection "0-10 Million"
2. yes, filter it in the default currency USD
3. @matmaxgeds, please have a look

**Comment by matmaxgeds** [comment]
@raashidahmad @mohamedgele22 

I agree that it is easiest to do this on Project Value, which is not related to the annual disbursements, and therefore should not be affected by the date filters. 

Rashid - I think this is similar to why we are now removing the Project Value from the tables in the sector/location reports as we are realising that it is a different thing to the disbursements i.e. not affected by the years - and so was confusing there, and it was my mistake to start suggesting we should adjust the project value by the years on the reports - they should only affect the disbursements. I hope we are now on a good/easier path with this.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the answers, i agree and will implement it. 
@mohamedgele22 sorry i had to post this question earlier, confirming again, you want this filter on projects list which you can reach using "View projects" menu item.

**Comment by mohamedgele22** [comment]
@raashidahmad  @matmaxgeds  thanks

**Comment by raashidahmad** [comment]
@mohamedgele22 @matmaxgeds this has been implemented.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks - this way has made a new table though, and constrains the choice - any chance we could just have a 'larger than' and 'smaller than' boxes, that way it can do anything the user wants?

**Comment by raashidahmad** [comment]
@matmaxgeds on this please see few thoughts:
1. Currently the filters allow you from 1-10, 20-30 million and so on
2. The only option i can think about is that less than 1 million in this case

Please guide me on this.

**Comment by matmaxgeds** [comment]
@raashidahmad sure, I was thinking of likely questions e.g. if you want:
1. Just those less than 20,000
2. 1 millions to 30 million etc

**Comment by raashidahmad** [comment]
@matmaxgeds Implemented

**Comment by raashidahmad** [comment]
Implemented with text boxes as suggested.
