### ISSUE TITLE
View details popup is too large and 'close' button not visible

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#49]
The 'close' button on the view details screen is not visible at all times - it needs to be - perhaps put one top right as well as bottom right.

The screen is also very wasteful of space and can be compressed

**Comment by kndm** [comment]
@matmaxgeds If possible do provide a screenshot as I need to locate and/or verify that we're looking at the same thing on the site.

**Comment by matmaxgeds** [comment]
![screenshot from 2019-02-21 09-35-07](https://user-images.githubusercontent.com/432153/53154897-15f4cf80-35bc-11e9-99ee-6a5f9f5a1623.png)

I got to this screen by going to 'data entry', selecting a project, clicking 'next' and then on the page where you enter the title, dates, description etc, clicking 'view details' on one of the selected source projects

**Comment by kndm** [comment]
I have repositioned the close button and made the modal smaller, it currently looks as the following screenshot, unless you've got any more feedback that needs to go on this change for the beta, then I will proceed to close this issue and create a PR @matmaxgeds 

![image](https://user-images.githubusercontent.com/6158743/53162580-a7416180-360f-11e9-981b-6e456c93c4d7.png)

**Comment by matmaxgeds** [comment]
Hi - thanks - the updated text is good, please also leave the same button at the bottom so that if I scroll down, then one is also available. RE the smaller modal - ok, I more more hoping to make it smaller in terms of not needing to scroll - there is no problem if it uses the full page width - so suggest restoring that. Please also check that it works for different screen sizes - down to 1024 width.

**Comment by kndm** [comment]
@matmaxgeds Will make said changes, also the button is always staying in a fixed position so even while scrolling down it remains at the top (visible in the same area and clickable at all times no matter how far down it has been scrolled)

**Comment by matmaxgeds** [comment]
Great, even better
