### ISSUE TITLE
Projects list page table tweaks

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#501]
Sarah has requested an excel download for the projects list page? I am parking this, as I will suggest that she can use one of the existing reports. 

However she is also hoping we can adjust the fields show on the projects list, please can we remove the start/end dates, and "updated on", and add the current FY planned disbursements?

Please remove the 'In' from the 'In USD' in the column title.

Please confirm that if the national currency is changed, this field title will also change to reflect the new currency?

**Comment by raashidahmad** [comment]
@matmaxgeds suggested changes are incorporated in the latest build.
Re currency: Yes USD will change if the default currency is changed.

**Comment by matmaxgeds** [comment]
@raashidahmad, sorry for not being clear, can it say "FY 2020 Planned Disbursements" e.g. pick up the current FY from a variable?

**Comment by raashidahmad** [comment]
It is fixed.
