### ISSUE TITLE
Project profiles - add the 'updated on'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#502]
Please can you move the 'updated on' field that was in the table on the project list and display it to the right of the project title in the project profiles?

**Comment by raashidahmad** [comment]
Done

**Comment by matmaxgeds** [comment]
@raashidahmad another sorry for not being clear - please can you make this it's own category like there is for start date, or end date etc, e.g. "Project last updates: INSERT DATE"......and put it in the space that is top right on the form.

**Comment by raashidahmad** [comment]
Suggestions implemented.
