### ISSUE TITLE
URGENT: Excel download for reports has ' before all numbers

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#504]
Hi @raashidahmad I now tested this on a windows laptop with excel (the most common user system) and the ' before all number columns means that you cannot sum or add etc any cells. Please find a way to make this export without that, and note that it is the case on all the excel downloads that we have

**Comment by raashidahmad** [comment]
@matmaxgeds Sent you a link on email with some details. On windows system, i checked it with MS Excel 2007, and it worked well. Trying to test it with other possible options.

**Comment by matmaxgeds** [comment]
@raashidahmad confirming this fix now how your priority following the email from Pau that it doesn't work in his excel either?

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for sharing the results, i am doing R & D and trying to understand the issue, also trying to produce on my end. I will come up with results soon.

**Comment by raashidahmad** [comment]
@matmaxgeds I could not find something specific to the thousand formatting issue we are facing. I have generated a file with new code but i could not see any thousand formatting with the tools i am using, for example, XPS, or online version for MS Excel, though when i see cell formatting, it shows thousand formatting checked. Can you please check the file i am uploading here?

[AIMSProjects-637217799274867230 (1).xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4439069/AIMSProjects-637217799274867230.1.xlsx)

The free open source library i am using is: https://github.com/tonyqus/npoi

**Comment by matmaxgeds** [comment]
@raashidahmad see screenshot, it is not a problem with the thousands formatting but with 'number stored as text'....the leading ' for each numberical value means that excel treats it as text, and therefore the sum of those cells is zero.
![Screenshot from 2020-04-06 17-10-14](https://user-images.githubusercontent.com/432153/78574030-b55d3c00-7829-11ea-8ffb-9b295fe71db1.png)

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the clue, helpful, looking into it.

**Comment by raashidahmad** [comment]
@matmaxgeds Necessary fixes made. Tested with LibreOffice. Thanks for the snapshot, helped me to understand the issue.

**Comment by matmaxgeds** [comment]
@raashidahmad now working for me, thanks a lot!
