### ISSUE TITLE
Add the org requesting deletion of a project to the deletion request

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#505]
As discussed on email - please can the AIMS provide the users in the message (facts provided by the system) the name of the organisation who requested the deletion.

**Comment by raashidahmad** [comment]
User email and organization name is provided who initiated the delete request. If it is okay and we do not need any changes, please close the issue.

**Comment by matmaxgeds** [comment]
Perfect, thanks
