### ISSUE TITLE
New organisations added from IATI message?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#506]
Please can you confirm who receives the following message, and what we expect them to do with the information?

http://aims.mop.gov.so/manage-email-message/10

**Comment by raashidahmad** [comment]
This is the message which manager users will receive when the IATI import will add new organizations from IATI. No action required in response to this, it is just an informational message.

**Comment by matmaxgeds** [comment]
Thanks, please remove this message as there is no response required

**Comment by raashidahmad** [comment]
@matmaxgeds remove this message from management section or there should be no notification at all from AIMS when new organizations are added to database?

**Comment by matmaxgeds** [comment]
@raashidahmad yes please, for new **IATI** organisations added to the **IATI organisations list** there does not need to be a message. There should still be a notification for the AIMS organisation list.

**Comment by raashidahmad** [comment]
@matmaxgeds Ok

**Comment by raashidahmad** [comment]
Done.
