### ISSUE TITLE
Add row on reports for 'no sector'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#51]
Not all projects have sectors, add a line in the reports for projects with no sector, also add a menu item in the sector selection dropdown for 'no sector' to include only projects without a sector.

**Comment by matmaxgeds** [comment]
The same things will be for all reports - i.e. for locations reports, we need a row for 'no location'

**Comment by raashidahmad** [comment]
@matmaxgeds Sectors report is prepared to group all projects under a sector. If there is no sector selected, we cannot prepare this report. We will have to create some other report in that case.

**Comment by matmaxgeds** [comment]
@raashidahmad let's discuss, I guess this is linked to how you are using the reports API? I.e. if there is no sector/location given then you cannot make a query for nothing? Given how many projects are going to be missing this data (currently all have sectors but only 33% have locations) then we need to be able to show in the reports (tables and charts) which ones are missing so that although it might show that 70% are to one location, that is only 20% when you take into account all the projects without locations.

Perhaps you can do a general query for all projects, and then subtract the projects that are returned when querying for each sector, and apply a code of 'none available' to those without data?

**Comment by matmaxgeds** [comment]
Closing as duplicated by #341
