### ISSUE TITLE
Sector mappings

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#511]
Not urgent, but for the OECD DAC sectors, please order them by the number, not just by the words after the number

**Comment by raashidahmad** [comment]
@matmaxgeds ordered by numbers, but unfortunately, the numbers are having data type string as some of the IATI codes are like 1.a etc. So the system takes the numbers as string and sort them, so you will not see them sorted as pure numbers.

**Comment by matmaxgeds** [comment]
This is sufficient, closing
