### ISSUE TITLE
Data entry - starting/ending years

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#512]
On the first data entry page, there are boxes for starting years, and ending years. Unfortunately these are not helpful in the current format. We need to be able to use them to find projects active between two dates, but how they are now, you have to be able to guess the exact start date of the project you are after:

1. Title the first box "active from" and the second box "active until"
2.
3. The boxes set a range of dates, and the list should show all projects that are active at any time during that date range.

**Comment by raashidahmad** [comment]
@matmaxgeds is it possible that we use the starting and ending financial year the same way as we are doing it on reporting pages, this way the interfaces and APIs will be consistent. What do you think?

**Comment by matmaxgeds** [comment]
@raashidahmad this sounds like a good solution for now

**Comment by raashidahmad** [comment]
@matmaxgeds Sorry that i did not wait for your reply, i have already made changes for dates, testing and finalizing it. If dates did not work well for users, will revert it to years later in phase 2.

**Comment by raashidahmad** [comment]
Fixed.
