### ISSUE TITLE
Bug on merge

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#516]
I got an error when merging, perhaps it is because I was the one who requested the merge? In which case I should not receive
![Screenshot from 2020-04-09 12-23-53](https://user-images.githubusercontent.com/432153/78885614-351f1c80-7a5d-11ea-8908-4e7109b66573.png)
 the notification?

**Comment by raashidahmad** [comment]
@matmaxgeds, please try few merges, i fixed and tested few edge cases.
