### ISSUE TITLE
Notification icon but no notification?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#517]
See screenshot - I refreshed, logged out and in, and refreshed the cache, it still appeared.
![Screenshot from 2020-04-10 10-01-02](https://user-images.githubusercontent.com/432153/78974459-542bb600-7b12-11ea-93b8-d060c477074d.png)

**Comment by raashidahmad** [comment]
@matmaxgeds It is fixed and tested with some scenarios, if you find any scenario, please let me know.
