### ISSUE TITLE
Why separate notifications for "approve request" and "delete project"?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#519]
Maybe I am forgetting but why do we need these to be separate?

**Comment by raashidahmad** [comment]
@matmaxgeds This is actually a two step process that we discussed somewhere.
1. The one who is interested to delete a project makes a request for deletion.
2. The request is forwarded to organizations involved as funders or Implementer. If a request is approved it is forwarded to Manager users for deletion. If rejected, requested is deleted and email is sent to the one who initiated
3. Manager user only sees approved request for deletion or any request that is 7 days old.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, I had forgotten the two steps in stage 2
