### ISSUE TITLE
What happens to envelope data when merging organisation

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#520]
@raashidahmad please let me know?

**Comment by raashidahmad** [comment]
@matmaxgeds No action is taken at the moment, which means it will be pointing to wrong organizations after merge, I did not think about this before.

**Comment by raashidahmad** [comment]
@matmaxgeds Please do not use merge feature until I deploy the fix on it.

**Comment by raashidahmad** [comment]
@matmaxgeds there is an edge case for envelope what if both the organizations that we are merging have also envelopes, what to do with the amounts for envelope?

**Comment by matmaxgeds** [comment]
Can we have a checkbox when merging for "add envelope data" which just sums the data from all organisations involved, if not selected, in each case (year/type) take the largest figure available?

**Comment by raashidahmad** [comment]
@matmaxgeds few more questions on it:
1. What currency to pick up while it goes for sum, as in this case there can be different currencies and then different exchange rates for them
2. In the case if it is not sum, the idea is to take the larger amount and its respective currency.

**Comment by matmaxgeds** [comment]
@raashidahmad - I think we have to make this easier - can we have a checkbox to indicate which organisation to take the envelope data from? That way there is no logic needed, or messing around with currencies etc?

**Comment by raashidahmad** [comment]
@matmaxgeds sounds a good solution. Thanks

**Comment by raashidahmad** [comment]
Fixed. Tested with local data, working. Good if taken backup before trying it with the real data.
