### ISSUE TITLE
Markers dropdown on reports/projects list - allow multiple options

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#522]
E.g. for the new COVID marker, users might want to select both "relevant" and "targetted" so please can this be a multi-select dropdown like e.g. sector or organisation?

**Comment by raashidahmad** [comment]
@matmaxgeds this means we have a single marker selected at a time, and we wanted to search it by multiple values? 
We do not have markers at projects listing at the minute, can we please keep projects module for phase 2, as that includes API, Excel, and UI?

**Comment by matmaxgeds** [comment]
@raashidahmad - yes, a single marker with multiple options e.g. for the COVID marker - most users will want to select both "relevant" and "targeted" at the same time.

Understood, will also push to keep adjustments to the projects module for phase 2.

**Comment by matmaxgeds** [comment]
If you feel something is for "Phase 2" then feel free to use the label in github so that I can see what you are thinking.

**Comment by raashidahmad** [comment]
Thanks Matt

**Comment by raashidahmad** [comment]
Implemented on reports. Please create a separate issue for projects (as we do not have markers on projects) for Phase 2 as discussed in the comments above.
