### ISSUE TITLE
Homepage projects list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#526]
Does this just show new projects, or also updated projects?

**Comment by raashidahmad** [comment]
This list shows the projects recently updated, when a new project is created, the date it is created is its date it is updated.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks - to confirm, if just the sector was changed for a project, it would then appear at the top of the list?

**Comment by raashidahmad** [comment]
@matmaxgeds I saw the code, and for locations, sectors, and markers the date updated is updated while for others not, i am re-opening this issue to fix.

**Comment by raashidahmad** [comment]
Fixed
