### ISSUE TITLE
Report filtered by marker - no data when show stacked chart

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#528]
Hi @raashidahmad ,

I tried this report: http://aims.mop.gov.so/sectors-report/?load=true&sectors=15,19,12,25&ctype=1&mid=10&mvalue=Relevant and selected stacked bar .....but then the chart was blank (but there was data in the table)?

**Comment by raashidahmad** [comment]
Fixed
