### ISSUE TITLE
Report link does not encode the sector level, or the chart option

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#529]
Hi,

I think we had this before, but the report link does not encode the sector level e.g. if it is showing parent or sub-sectors, or the chart options. I can see how the chart options are harder, but they can make a big difference to the report e.g. if it is actual or planned disbursements can make the difference between seeing an empty chart or a full one.

Matt

**Comment by raashidahmad** [comment]
Fixed
