### ISSUE TITLE
No negative planned disbursements

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#53]
There should not be negative planned disbursements - on the data entry forms, do not allow adding more value of disbursements than the value of the project. Add a notification saying 'You cannot add more disbursements than the project total value. Please increase the project funding amount before adding more disbursements.'

**Comment by raashidahmad** [comment]
@matmaxgeds we need to check this on new projects and entries. As this has been restricted from the UI now. The formula used for planned disbursements is: 

PlannedDisbursements = projectCost - totalDisbursements / remainingMonths

We may close this issue upon correct results or may further try to figure out any error with calculations.

**Comment by matmaxgeds** [comment]
A small adjustment:

PlannedDisbursements = projectCost - totalDisbursements

The '/ remainingMonths' is needed when we need to show how many of the planned disbursements are due in each of the remaining years - in which case we need to calculate how many months are left, then calculate how many disbursements are left in each month, then calculate how many months are left in each of the upcoming years etc
