### ISSUE TITLE
Donor Clearance Letter

### ISSUE THREAD

**Issue by mohamedgele22** [somaliaims/Somali-AIMSUI#530]
As discussed, we need to add fields, then donors will give their contributions using the reference numbers given by MoPIED.

**Comment by matmaxgeds** [comment]
This will need the following:
1. Text entry field - perhaps MoPIED could fill this out
2. A setting for 'not required'
3. A decision on whether the field is mandatory

Options for the location include:
1. A new field - guess in basic information
2. Using a Marker?

Need to think:
1. Is this needed in reports? If so, How?

**Comment by matmaxgeds** [comment]
Will be solved using existing markers system
