### ISSUE TITLE
Add 'organisation' filter to the excel download - and indicate USD

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#532]
1. Please add a filter for a single AIMS organization
2. Please edit the column titles to say "(USD)" after each financial column title, where USD is the result of a call to DefaultCurrency

**Comment by raashidahmad** [comment]
@matmaxgeds Please tell me where to add organization filter? and what will be its behavior?

**Comment by matmaxgeds** [comment]
@raashidahmad - to this page please: http://aims.mop.gov.so/data-export, it will limit the projects exported to just those from the organisation selected

**Comment by raashidahmad** [comment]
Thanks. @matmaxgeds Can you please help me out, what is urgent and what we can do later? For later i would like to mark them as Phase 2, or another way to think about this would be to make any bug fix as Phase 1, any new feature as Phase 2. We can take urgent as exceptions. This task would require:
1. Updating API for organization filter
2. Updating excel generation
3. Adding organization filter on UI

**Comment by raashidahmad** [comment]
I will include USD in the Excel sheet and taking as urgent requirement.

**Comment by raashidahmad** [comment]
USD implemented in Excel reports

**Comment by matmaxgeds** [comment]
Remains:

- [ ] Adding organization filter on UI

**Comment by matmaxgeds** [comment]
@raashidahmad USD export is not available yet as far as I can see.

Also, there is the problem again where numerical data is exported as text (which we fixed before) but it prevents users from adding cells together in columns. If opened in openoffice, the fields show '1.00 - with the  " ' " showing that it is a number stored as text

**Comment by raashidahmad** [comment]
Fixed and Implemented.

**Comment by matmaxgeds** [comment]
Looks good :)
