### ISSUE TITLE
Move contact email for projects from Rashid to aims.developer

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#534]
The initial projects entered from the 2019 Aid Mapping were assigned to Rashid's email address on entry. This means the contact project does not work:

- [ ] re-assign all projects to aims.developer18@gmail.com - do this immediately

then after a chance for users to register
- [ ] remove aims.developer18@gmail.com from all projects where the organizations have registered users

**Comment by raashidahmad** [comment]
Fixed. Any new user which is approved now onward, will replace the owner of the project from aims.developer to the user of a project from funders or implementers if they are first to register from.
