### ISSUE TITLE
REmove user aims.developer18@gmail.com from the AIMS

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#535]
This is not a real user - we need to remove them from the AIMS, this means deleting the user, and removing the user from all projects.

For projects where no registered user is found, the emails should go to the management users

**Comment by raashidahmad** [comment]
@matmaxgeds we resolved it in issue #534 where any user from the funders or implementers of the project while approved finds that the default user is owner of the project, will replace it with the actual user. While reading the description of this ticket i am trying to understand what to do in this ticket:
1. When do i need to send emails? As the user was inserted at projects imports as created by was mandatory field.
2. I think what you are suggesting would be possible to design a management page and find out what projects belong to the default user or any other user, and then manager account can replace its creator from the funders or implementers list? (If you suggest the same, it would be a Phase 2 task then)

**Comment by matmaxgeds** [comment]
@raashidahmad thanks - I see the issue, and am not suggesting any management pages etc.

Let's leave the aims.developer18 user in then - the management users will just need to be aware to also regularly check that account for messages - it is just the result of us pre-loading the data, not a design issue, so closing here
