### ISSUE TITLE
"no organisation" to solve user signup/rejection issue

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#537]
- We want as many users as possible
- But we don't want hundreds of junk organisations, or the chance of junk data in the envelopes
- This means that emailing all users reaches the maximum number of users
- rejecting users is bad publicity
- rejections maybe wrong, and there might not be enough time for research/contacting
- rejects can be hard to deal with logically, and involves building new features
Suggested way forward:

- [ ] New organisation called "No organisation" which does not appear in any organisation dropdowns, and also does not have any add/edit data ability either for projects or envelope data (ideally the whole menu is missing - but don't just do this visual shortcut)
- [ ] New button "Approve without organisation" - which approves the registration, but sets the user to "no organisation"
- [ ] Need a new email message for users approved with no organisation - where we can explain what has happened and their options
- [ ] If a user disagrees with this (e.g. if they join an organisation later, or want to update the information they originally gave to a new organisation, they login and use the account management to use the new 'change organisation' feature - see issue #538

**Comment by raashidahmad** [comment]
@matmaxgeds Please think about another situation as well, The user will register with an organization, that we would not like to be listed in AIMS Organizations.

**Comment by raashidahmad** [comment]
@matmaxgeds both 537 and 538 are connected issues, and if we try to solve one, we will have to solve another as well. It will take about a week to implement. It might take more days if we discover more scenarios later and do fixes. Please suggest me, if it is urgent, let me start work on it, if it is not, i will label it as Phase 2.

**Comment by matmaxgeds** [comment]
@raashidahmad - thanks, I have to do something else today, but will rethink these tomorrow taking into account your comments - for example, maybe we could scrap the change organisation button as it could be done by asking the user to delete their account and then re-register. I also have to get a feel for the politics of this.

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks, no problem, please take your time.

**Comment by matmaxgeds** [comment]
@raashidahmad  - in this case, when the management user clicks "register as unaffiliated", if the organisation that they wanted to join has no existing projects, please delete the organisation from the list - but if the organisation has existing projects, please do not delete it.

**Comment by matmaxgeds** [comment]
Completed
