### ISSUE TITLE
Disbursements with a single date

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#54]
Disbursements should not have a start and end date - just a single date - that is the date that the disbursement happened on

**Comment by raashidahmad** [comment]
Fixed. @matmaxgeds  please test, if the change is what you intended for? Re-open if you asking for something else.

**Comment by matmaxgeds** [comment]
@raashidahmad yes, this is the right idea. Unfortunately I was not clear enough, disbursements are the one date type where we do need to day of disbursement in addition to the month and the year, so please can you just add the standard datepicker.

**Comment by raashidahmad** [comment]
Fixed.
