### ISSUE TITLE
New IATI datastore

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#544]
Hi @raashidahmad - for Phase 2, but I am worried that the IATI datastore we use at the moment will get shut down at some point. We should think about being ready to switch to the new IATI datastrore: https://iatidatastore.iatistandard.org/documentation/introduction

This basically just means adjustments to the parser and working out the new query - but all the rest should be the same. It might be that we can do a more advanced query though that looks for 'Somalia' in both the activities and the transactions to determine which IATI activities to return.

We might have an option on the IATI management page to enter a query and specify which datastore it is for so that the AIMS can chose which one is used.

It would be good to get a rough time estimate on this?

**Comment by raashidahmad** [comment]
@matmaxgeds I have taken a quick look and saw that we will not need a local parser. But it also seems that there are differences in the names they return while the one we used. For example, we parsed the xml and mapped them to model classes we created. I will study it in detail and will share my thoughts.

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad please don't prioritise the research to much at this stage as I still need to get more info as it is still in beta

**Comment by matmaxgeds** [comment]
https://iati.cloud/search/activity?q=recipient_country_code:(SO)%20OR%20transaction_recipient_country_code:(SO)&wt=xslt&tr=activity-xml.xsl&rows=10000 will get the xml but it doesn't return the numver of cases, and queries for more rows can break it - so far just the json return the available rows: https://iati.cloud/search/activity?q=recipient_country_code:(SO)%20OR%20transaction_recipient_country_code:(SO)&wt=json&rows=10

**Comment by raashidahmad** [comment]
@matmaxgeds yes it is working the way you shared. Okay, i will hold it until you get more information on it.

**Comment by matmaxgeds** [comment]
Discussion continued on #582
