### ISSUE TITLE
Stop multiple merge requests for an organisation

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#548]
Matt, I performed the following steps:
To understand the problem change my organization to Sweden, and logged in as Sweden.
Read the error message and realized that the problems was
There were multiple requests for the same merge
The merge api deletes the request after merge
So it deleted the one, and the other one complained that it contains a reference to the one that you applied for deletion.
Did the fix and it worked.

We need to prevent this from happening I guess by 'greying out' organisations that already have a merge request in place so that they cannot be selected for a second one.

What happens if the first one is not actioned - does it expire?

**Comment by raashidahmad** [comment]
Fixed
