### ISSUE TITLE
Finished button

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#55]
After the last data entry tab has been completed, user can click 'Finished', Finished, show project' (shows the whole project popup) or 'Finished, add/edit another' (returns to add/edit project screen).

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
The request was for three options - sorry this wasn't clear

1. 'show project' (shows project detail popup)
2. 'Finished' (returns user to homepage)
3. 'Finished, add/edit another' (returns user to data entry screen)
