### ISSUE TITLE
Remove Ghost organisations

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#550]
Previously, organisations could join projects without having a visible role, this is removed, but we need to assign roles (funder, implementer) to all the existing cases

@raashidahmad to produce a list for Matt to indicate the roles to manually assign

**Comment by matmaxgeds** [comment]
Hi Rashid - I have added a new column (it is still a csv, but github do not accept that file type) giving the funder to set these orgs to for each project

[Ghost_Users - with roles.txt](https://github.com/somaliaims/Somali-AIMSUI/files/4815508/Ghost_Users.-.with.roles.txt)

**Comment by raashidahmad** [comment]
Thanks @matmaxgeds, I will look into it, will device the logic how to update, and will come up with my queries if required.

**Comment by raashidahmad** [comment]
API written. Executed the excel document. Fixed.
