### ISSUE TITLE
Sub-sectors not aggregating on location reports

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#555]
Sarah - Hi guys - just wanted to flag I think there's an issue with the sectors appearing on the location reports. See here for example:  https://aims.mop.gov.so/locations-report/?load=true&sectorId=560&ctype=1

Matt - seems to work when a sub-sector is selected, but not a parent sector. Also works without any sectors.

**Comment by raashidahmad** [comment]
Fixed
