### ISSUE TITLE
AIMS certificate issue - not working in internet explorer

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#557]
Users using internet explorer get an authentication message that they need to cancel to proceed, in my case I do not get the message, but the UI cannot connect to the backend.

![image](https://user-images.githubusercontent.com/432153/82232832-6bd73500-992f-11ea-9a13-536cbf1e3e46.png)
![image](https://user-images.githubusercontent.com/432153/82233381-3848da80-9930-11ea-95ef-09ea78c4a974.png)

This suggests that we need to move to the long term solution, and I think that is adding another docker image with NGINX running a reverse proxy e.g. https://gist.github.com/soheilhy/8b94347ff8336d971ad0 and https://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite

**Comment by raashidahmad** [comment]
Certificates configured with the best configurations. Old IE versions are not supported as per Lets encrypt documentation.
