### ISSUE TITLE
Projects list always resets filters

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#558]
If search for a project on the projects list using filters, then view project in the tab it makes, when I return to the list, all the filters are reset.

I think a shortcut to fixing this might be to use a popup like in other places.

**Comment by raashidahmad** [comment]
@matmaxgeds why not to open the project detail in a new tab?

**Comment by matmaxgeds** [comment]
@a new tab is also fine, the problem is that switching to the new tab always resets all the filters, so if you can stop that a new tab is fine. I thought that a popup might be easier for you as popups elsewhere in the AIMS do not cause filters to reset

**Comment by raashidahmad** [comment]
@matmaxgeds Okay will try to do it through popup. Will let you know if there was any other challenge with popup.

**Comment by raashidahmad** [comment]
@matmaxgeds i have recently upload new deployment for UI where i open projects using a new tab. It does not reset filters. It this seems fine to you, please close this issue.

**Comment by matmaxgeds** [comment]
@raashidahmad when I am sent to the new tab, it is not just opening the project view tab, it opens the whole AIMS again with the project view selected - and then in that tab, when you go to the tab within the AIMS which says project list, you have lost all your filters again - so this is not a very clean solution as the user needs to realise that they should shut down a tab showing the whole AIMS.....hence why a popup would be neater in this case - I assumed this would be easy as you have already written code that makes popups for project details pages in several other places

**Comment by raashidahmad** [comment]
@matmaxgeds I see understood your point now. It will be some efforts, but i will do it through a popup in the coming deployment.

**Comment by matmaxgeds** [comment]
@raashidahmad I have recoded this to phase 2 so it will count against those days

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks.

**Comment by raashidahmad** [comment]
Done.
