### ISSUE TITLE
Delete Test organisation

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#559]
There is an organisation called Test organisation that needs deleting, but there are user accounts associated so cannot remove

**Comment by raashidahmad** [comment]
@matmaxgeds please suggest what to do with this organization? The possible options are:
1. Rename this organization to some meaningful name
2. Delete this organization, and assign the associated users to some other organization.

**Comment by matmaxgeds** [comment]
@raashidahmad can you share a list of the users?

**Comment by raashidahmad** [comment]
@matmaxgeds upon creating users list I realized that actually I created this organization for testing. There was one associated account with this, which was mine having email Id: rashid.ahmad@live.com. I have deleted that account, i then deleted the Test organization.
