### ISSUE TITLE
Business logic for editing and merging projects

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#56]
Currently you can only use an AIMS project as a source project, making a new project each time, you cannot edit/update it or merge it, this needs fixing by giving more options on the data entry screen. We can do this by adjusting the what is written on the 'next' button on the first data entry page. They will be bulky and ruin the UI for the moment but once they are working, we can figure out how to clear it up.

1. No projects selected: 'Proceed with manual data entry only' - in this case, remove the left hand column.

2. Single/multiple IATI projects, no AIMS projects selected: 'Proceed with IATI projects only' - as currently

3. No/Single/multiple IATI projects, one AIMS project: 'Proceed, updating existing AIMS project', and a second option, 'proceed, making a new AIMS project' - if 'edit' is selected, Pre-load all the fields with the AIMS project information - and also show all tabs at the top. Do not show the selected AIMS project in the source projects tab as it is being edited at the time in the right hand column. This will be the most common use case for the data entry screen where users want to update an AIMS project with the latest financial data from IATI. Instead of making a new project, as the user progresses, the AIMS should edit the existing project. If '

3. No/Single/Multiple IATI projects, multiple AIMS projects: 'Proceed, merging existing AIMS projects' see above, or 'Proceed, making a new AIMS project'. If 'proceed, merging' is selected it would be good if we can load the source AIMS projects into a temporary area so that we can delete the originals and make the data available to the user in the left hand column (with a special tag 'merging'). Delete the original projects being merged immediately.

**Comment by raashidahmad** [comment]
This logic has been implemented. Fixed.
The projects are merged in the very first stage and offers user to either finish or edit the project. The edit project is then the new merged project.
