### ISSUE TITLE
Error message before have had a chance to enter disbursements

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#565]
When entering a project, and proceeding to the financials page, an error message comes before the user has even had a chance to do anything, the error should only come if the user tries to click next, or to leave the page

**Comment by raashidahmad** [comment]
This has been fixed. This only shows error when already created project is loaded for editing.

**Comment by matmaxgeds** [comment]
@raashidahmad hopefully also if you click 'next' with incorrect disbursements also?

**Comment by raashidahmad** [comment]
@matmaxgeds yes tested locally.
