### ISSUE TITLE
Restore a backup from HD failure

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#568]
Matt: I am trying to simulate what the situation would be if in a year, there was a hard drive failure on the AIMS, and MoPIED had to start with a fresh server, a new deployment, and then import their most recent offline backup.
Rashid: What I understood about the scenario you presented is that, for example, if the hard drive crashed or for any other reason you are transferring the database from one server to another. In that case we can offer the user with a feature to upload a backup file to the server for a database backed up on another system. In fact.
    With the current system, it backs up the data using the current instance of the database, and stores it on the hard drive without bothering the user. A user can then restore a backed up instance.
    In the new feature, user will be able to upload a backup taken previously on using instance of the database.

**Comment by raashidahmad** [comment]
@matmaxgeds this task Includes the following:
1. Upload a backup file. File uploading module
2. File validation module for the backup file with valid extension for the backup.
3. Do you think we should restrict the user not upload a file which is very huge?
4. I am also wondering, we are thinking about a situation when there is not database, if there is not database connected, the AIMS will not run, So we need a separate section in the AIMS that should be loaded if there is no database. I will have to research how can i catch this exception smoothly and redirect the user.
4. It may take 4-5 days to come up with some working solution. I can start work on it.

**Comment by matmaxgeds** [comment]
hi @raashidahmad thanks for thinking about this:

1. We might be able to skip this (as I suspect it will be difficult/cause a lot of issues) by assuming that the user has access to the server, therefore they can place the file directly in the relevant folder where the backups are stored, and have the AIMS re-scan the backups folder ever time the page is loaded and display the available backups-
2. Errr, if possible I would also skip this - if it does not work (the backup fails) we can assume it is invalid and the user should try again, or with another file?
3. I think the suggestion in 1 would solve this - I agree that it would be a big issue
4. I am not understanding how there can be a situation where there is no database but maybe this is beyond my understanding. When the user deploys a new AIMS, the blank database is created - therefore there will always be a database already?
5. OK, this was in the ToR so I think we have to deliver it as part of Phase 1

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for sharing your thoughts.
1. You nailed the issue, that is correct, when you run AIMS, It will create an empty database, so we will not have this situation.
2. Currently the AIMS has the feature that if the user puts the file in the respective folder, it will pick it up. 
3. I will write the upload file module, where user would be able to upload the files as required with all the simplicity suggested.

**Comment by raashidahmad** [comment]
@matmaxgeds As per mutual understanding we assume:
1. User has access to the directory where AIMS is deployed.
2. User can copy the backup file there. Refresh the backups page, and backup will be available to restore.
