### ISSUE TITLE
Confirm security status of AIMS APIs

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#570]
How are the APIs secured, could anyone write to them?

**Comment by raashidahmad** [comment]
APIs are secured using JWT token. So one cannot post the data that does not have this token. This token is issued by APIs server after user authentication. 
Please note that token authentication is applied to every individual API. For example, all the get data APIs are open, such as projects list, project detail, report APIs. While example for restricted APIs are creating or updating a project, creating a category.

**Comment by raashidahmad** [comment]
@matmaxgeds closing it to track other issues. If we found any improvement for it in future. We will create another issue.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for confirming
