### ISSUE TITLE
Envelope data entry

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#571]
Please can we confirm that the Envelope data entry page rolled over on January the 1st? I suspect it did not, as it used to show 2019 as the first year before, and so if it had rolled over, then it would now show 2020 as the first year.

At the same time, Sarah points out that we need to keep 2019 visible, so it should show (always) n-1, n, and n+1.

**Comment by raashidahmad** [comment]
@matmaxgeds please see the details below:
1. We imported the data by 27th of January. So no rollover occurred through background service.
2. The logic it has to show (Previous, Current, Future) financial years.

So the findings show that we have made it previously as it should be. Closing the issue. We can re-open if there is anything to rectify.
