### ISSUE TITLE
Move 'join a project' to the projects list like 'suggest a change'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#576]
It just clutters up the data entry interface and does not allow any data entry when clicked so it bad UI deign suggestion from me. It can go onto the project profiles in the top right

**Comment by raashidahmad** [comment]
@matmaxgeds This means that we need to allow a user to use any project as a source project. For example, a user that belongs an organization named as Sweden can use projects from UNDP?

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - thanks - I see you already did this, you can also remove the 'request a change' button from the profile on the data entry page, as that is also just a link to an email form, not a part of the data entry, and users can already access it through the 'suggest a change' page on the project list profiles - please close for review when done
