### ISSUE TITLE
Restore the "suggest a change" button to all users

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#577]
Once the admin user moderated messaging system is setup, we can restore this button to all users

**Comment by raashidahmad** [comment]
@matmaxgeds Is this feature ready to Implement for Phase 2?

**Comment by matmaxgeds** [comment]
Operation logic:
- A user uses the 'suggest a change' button to email a project, or the contact form to send a help request.
- If it is a registered user, the AIMS does not display the email address field
- The AIMS stores this message and the other fields
- The AIMS checks if this message came from a registered user by comparing the email addresses
- If it does, then the AIMS sends it to the destination
- If it did not come from a registered user, the AIMS sends a notification email to the management users to approve/delete the message
- If no management user approves the message within 2 weeks, the sender receives an email saying that no management user was available to approve the message
- If the management user deletes the message, then the message is deleted, and no email is sent
. If the management user approves the message, it is forwarded to the recipients

Needed
- Logic
- Notification email for management users
- Email for message not approved within 2 weeks
- restore the suggest a change' and contact project features

**Comment by raashidahmad** [comment]
@matmaxgeds there is a question for the given point below:
Point:
If no management user approves the message within 2 weeks, the sender receives an email saying that no management user was available to approve the message

Question:
What if email is sent to the user first. The scheduler will check it the next night or the next new day, it will keep sending the message. How to tackle this situation? Please suggest me.

**Comment by matmaxgeds** [comment]
ok, good point - let's adjust it to make it possible - if no management user approves it within 2 weeks, we can send the person who sent a message an email (please add it to the emails page) which says "We are sorry, we were unable to handle your request at this time. We suggest that you contact the relevant organizations outside of the AIMS", and then we delete their message from the system so that it will not be triggered again. Maybe we also increase the time to 3 weeks!
