### ISSUE TITLE
'Exchange rate of currency to 1 USD' not 'ExchangeRate'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#58]
Please check on all pages that use exchange rates

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
Sorry - it needs to be the whole sentence in quotes i.e. 'Exchange rate of currency to 1 USD' not '1 USD'

**Comment by raashidahmad** [comment]
Fixed
