### ISSUE TITLE
How long does it take before a request to join a project is sent to a management user

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#588]
Hi @raashidahmad what happens if an organisation does not answer the email to join a project, does it redirect the request to management users?

**Comment by raashidahmad** [comment]
@matmaxgeds This will be set as 7 days for a management user. At the moment, I have left it as posted, management user can see and approve. Once Pau is done with all the projects he wishes to Include UNDP as funder/Implementer. I will set it to 7 days.

**Comment by matmaxgeds** [comment]
closing, followon in #601
