### ISSUE TITLE
If deleting an existing sector, user then also has to delete 'unattibuted'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#591]
When a user edits a project, and deletes the existing sector so that they can add different sector, the gap is immediately filled by unattributed, before the user has a chance to add their own sector, and then then have to delete unattibuted in order to proceed.

Can we not calculate unattributed only when 'save sectors' is pressed, not in the middle of deleting sectors?

**Comment by raashidahmad** [comment]
@matmaxgeds Actually this is how we are telling the system to keep adjusting percentages automatically, and allow the manual adjustments of percentages. When are deleting a sector, the system automatically adjusts the remaining percentage. When we are deleting the Unattributed itself, we are telling the system, do not adjust percentages automatically, i want to adjust it myself.

**Comment by matmaxgeds** [comment]
@raashidahmad noted, if we keep getting complaints then we might come back to it
