### ISSUE TITLE
Calculating total Issue on financials tab, data entry.

### ISSUE THREAD

**Issue by raashidahmad** [somaliaims/Somali-AIMSUI#595]
In some cases, the total value exceeds the total value of the project.

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
@raashidahmad please write one line on what the problem was and what fixed it

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for indicating Insufficient Information about the problem. I have updated the description for this ticket. The calculation was using ceiling function for totaling the decimal values, so this has been now fixed.
