### ISSUE TITLE
Locations to be narrowed down from state to city/district or village

### ISSUE THREAD

**Issue by mohamedgele22** [somaliaims/Somali-AIMSUI#606]
The need to have the exact address where the project is taking is very crucial in terms of monitoring and evaluation. 
fields could be:
South West State
Afgoye city
Basra Village

I will provide the location names and villages.

**Comment by matmaxgeds** [comment]
Hi @mohamedgele22 thanks for adding this.

1. Can we do a quick test to see how many projects can provide this data?
2. Maybe the easiest way to start is to have a text field for additional location information

If we are adding it fully:
1. This means adding two more levels to the locations, and therefore two more locations lists, or maybe one list, and one text field, and will we allow people to add missing locations like they add missing organisations (if so we need an approval process)?
2. The key is that Basra village can only be added if you have already selected Afgoye city, and that can only be selected if the user selects South West State first
2. We will have to adjust all places where there are location filters to have one dropdown to select the level of the location filter, and a second one to select the option
4.  Adjust the location reports to decide which level to show

**Comment by matmaxgeds** [comment]
see #610 for the continuation of this issue
