### ISSUE TITLE
AIMS Data accessibility

### ISSUE THREAD

**Issue by mohamedgele22** [somaliaims/Somali-AIMSUI#607]
Currently, the data is accessible to the public, but the government wants it to be between the international partners and the government.

**Comment by matmaxgeds** [comment]
1. It would be good to understand the idea here a bit more so we can design it the best way e.g. does this mean all data should not be visible to the public, or just some?
2. I guess this will need a discussion with the international partners as they may be concerned that this has removed the transparency benefits of the AIMS - they may be less willing to enter data in that case.
3. This means that every user will need a separate login even to view a report, so each staff member from each international organization who wants to view a report will need their own login?
4. This means that members of the public will not be able to contact projects to get further information?
