### ISSUE TITLE
Sector selection box on data entry field needs text search

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#61]
If there are 100 sectors, users will want to search based on some entered text to filter the list so update the widget

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
Not visible yet?

**Comment by raashidahmad** [comment]
@matmaxgeds we now have sector types in the new model, under which we have at most 25-30 sectors, please review.

**Comment by matmaxgeds** [comment]
@raashidahmad I just tried entering a project, when entering the sector, I selected OECD DAC sectors (of which there are a lot more than 25-30)....but there was no 'search' facility, please can we have one e.g. like the organisation selection dropdown, but single select not multi-select

**Comment by raashidahmad** [comment]
Fixed
