### ISSUE TITLE
Financial data rounding errors

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#626]
When entering (or updating) disbursements, too many users are getting errors e.g. due to rounding, logic errors, we need to make this part mroe user friendly:

1. Prevent entering of decimal places
2. Not throw an error if the disbursements are not 100% of the project value - we can just add the missing part to the final year
3. ???

**Comment by matmaxgeds** [comment]
is linked to #546

**Comment by raashidahmad** [comment]
@matmaxgeds Is this confirmed that we will not allow decimal points for financial values? I am intending to start work on it.

**Comment by matmaxgeds** [comment]
@raashidahmad confirmed, I think this will make everything easier and the users do not need them.

RE 2 - I am talking about not throwing an error if there is a smaller than 1 error.....not in general

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the confirmation

**Comment by raashidahmad** [comment]
@matmaxgeds I came across an issue while Implementing the whole numbers, this is when you use "equally split remaining values" feature. Sometimes, the remaining amount is not fully dividable and by rounding the values it will become 1 less than the total amount. Please suggest.

**Comment by matmaxgeds** [comment]
@raashidahmad please add all the remainder decimal parts to the last year

**Comment by raashidahmad** [comment]
@matmaxgeds thanks, noted
