### ISSUE TITLE
Fixes in IATI Parser for the version 2.03

### ISSUE THREAD

**Issue by raashidahmad** [somaliaims/Somali-AIMSUI#631]
During testing some minor structural changes were found. For example, in the new version (2.03) of IATI narrative tag is not present under the title for projects, which does not parse the data well. For this reason, some fixes are required.

**Comment by matmaxgeds** [comment]
understood, let's have a proper review of this in combination with adjusting to the new datastore because we need to think of a way where similar things in the future have less chance of breaking it - I think the new datastore should help as it converts everything to 2.03 I think for us
