### ISSUE TITLE
If the same sector is added multiple times, combine the amounts

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#64]
When a sector is added for a second time, combine the amounts in the table

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
Thanks for the fix - but when it combines sectors, it triggers the unnecessary warnings again, which it shouldn't. When you do a fix, please test look to see if what happens is sensible, not just the exact fix.

**Comment by raashidahmad** [comment]
It is fixed.
