### ISSUE TITLE
Exchange rates still have problems

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#641]
@raashidahmad the latest update has caused quite some confusion to the exchange rate pages, maybe it is best if we talk with voice about this as there is a lot here

1. Under open exchange rates page, there is no way to check if the api/api key is working, please report somewhere the date of the last successful API query
2. For the open exchange rates - there is an email associated with the API key, and a password - please make a space for users to note these details on the page so that they do not lose them, including a space to note the show the current API key that is entered
3. Please give a 'test API now' button for users to confirm that it is working
2. Under the central bank page - it shows a lot of rates that are not manually entered - please only show the manually entered rates here
3. There is no place to enter the manual exchange rates - which have a full date (day, month, year) any more?
3. You need a separate page to show the annual average rates that are calculated and in use - I think you have currently put this under the central bank page - it should show currency A, currency B, the year, and the source (openexchangerates or the manually entered source name) - but does not need to show the whole list, just the ones that a user searches for using filters, like how a report works - no need to pre-load
4. It should not be possible to delete the calculated exchange rates - they are just for information

**Comment by raashidahmad** [comment]
@matmaxgeds we have agreed on some rules on this and had applied fixes. So closing this.
