### ISSUE TITLE
Remove the link to the FAQ file and add to the 'homepage links'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#642]
This was just a temporary measure, please remove this hardcoded link and add it to the 'links' via the management page

**Comment by matmaxgeds** [comment]
@raashidahmad I do not see the link now added in the 'important links' section......did you do that part?

**Comment by raashidahmad** [comment]
@matmaxgeds There are many tasks that were done during the maintenance period after expiration of the contract with the understanding that these tasks will be included in phase 3. But I think we can remove it from the work plan as it is a very small task and already done.
