### ISSUE TITLE
DEO project approval process

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#643]
- Implement DEO marker (both for when approved, or not needing approval) and for the number (DONE BY MATT)
- DEO specific report - to get the data they want in one place - unclear if needed

**Comment by mohamedgele22** [comment]
Also DEO specific report, please remove it. this will prevent donors to report.

**Comment by matmaxgeds** [comment]
@mohamedgele22 closing here then
