### ISSUE TITLE
error on unapprove

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#660]
Hi @raashidahmad I just did an 'unapprove' on a request to join a project and got the error picture below

![image](https://user-images.githubusercontent.com/432153/107631908-0d44aa80-6c66-11eb-8a7c-3a18791fed9a.png)

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for reporting the issue. I will test and fix the issue and will share it with the upcoming build.
