### ISSUE TITLE
Call the Forgot Password API to send an email to the requested user

### ISSUE THREAD

**Issue by raashidahmad** [somaliaims/Somali-AIMSUI#7]
This feature is to be implemented in order to recover password for any user who forgot the password.

1. A link must be given on the login page titled as "Forgot Password".
2. When the user clicks on this page, he/she must be directed to page asking for email. There must be a button titled as "Send Reset Link".
3. Call this api to send reset link: API (http://104.140.103.166:7000/api/User/ResetPasswordRequest)
4. You will recieve a link on email. The last part of the url contains the token. The url contains the link to reset-password page. So there must be a component named as reset-password, this component must read the token from url.
5. This page must contain two fields. New Password and Confirm Password. You must call the API (http://104.140.103.166:7000/api/User/ResetPassword) and send NewPassword and Token.
6. This token will expire after password change and user must be able to login with new password.

**Comment by kndm** [comment]
@raashidahmad Any updates on this issue? (RE: API detail)

**Comment by raashidahmad** [comment]
@kndm i am working on the APIs, will update you when it is done.

**Comment by kndm** [comment]
@raashidahmad Understood, thank you :)

**Comment by raashidahmad** [comment]
@kndm Pleasure :). API description updated.

**Comment by raashidahmad** [comment]
@matmaxgeds I have re-written this component just to be compliant with current UI and coding strategy. You may test it, call on Forgot Password on Login Page.
