### ISSUE TITLE
Do not show 'funder is required' error messages from the start

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#70]
These are unnecessary error messages, show them only if someone clicks the add funder button without filling in all the data.

**Comment by raashidahmad** [comment]
Fixed. Untill the form is submitted once, messages will not be shown.

**Comment by matmaxgeds** [comment]
also no need to have these when a funder has just been saved - they are only needed when a user tries to 'save funder' without filling all the required fields.
![screenshot from 2019-02-23 23-07-07](https://user-images.githubusercontent.com/432153/53292262-207fb680-37c0-11e9-9e32-c80524d82ba1.png)

**Comment by raashidahmad** [comment]
Fixed as desired.
