### ISSUE TITLE
Reset funder not needed?

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#77]
On data entry, under 'funders' there is a 'reset funder' button - I don't know what it does and suspect it can be deleted. At the start all the cells are blank, so nothing to reset, as you type a funder you are entering data, so nothing to reset, and when you 'save funder', it blanks all the cells, so nothing to reset. If you want to remove a funder, you can use the delete action, several times if necessary, so unless I am missing something, please remove the button.

**Comment by matmaxgeds** [comment]
I see that we have the same also for location.......whatever the solution is, it should be applied to all the similar buttons

**Comment by raashidahmad** [comment]
@matmaxgeds There are cases, when user selects data from IATI, and controls are changed. For example, for locations either select locations from AIMS or add/adjust location from IATI. When AIMS, user has to select from the list, when IATI, user has to input, which is selected by default. Sometimes user selects an option for example IATI, and user suddenly realizes he/she wants to select the location from list. In such situations, there is no way to go back. That is why to reset form to default list, it is needed. Please test it and close if if you agree.

**Comment by kndm** [comment]
@matmaxgeds Need an update when possible on whether  it was tested as per @raashidahmad recommendation so that I know if I should take over this issue.

**Comment by raashidahmad** [comment]
In some cases it is required and user has no way to go back to default state.

**Comment by matmaxgeds** [comment]
Re-opening as I think we need to discuss a better way to solve this - I suspect the answer lies in working out what to do when a user wants to use a location or an organisation etc that is in IATI but is not in the AIMS lists - and making this happen without the users knowledge - for example with organisations (and the management users can combine them later) and with locations, not allowing locations that the AIMS doesn't recognise - or using a lookup to try and translate them.

We are already solving this for manual entry - so we can probably learn from that
