### ISSUE TITLE
data entry taking dates from the 'title'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#79]
When entering a project on the first screen:

1. The dates are pre-filled - this shouldn't be the case
2. The dates get filled with the data from whichever project you are selecting to use the title from (this should not be the case - the dates need their own button - and probably multiple buttons as e.g. from IATI projects, there will be multiple date options, just like the financial data.

**Comment by raashidahmad** [comment]
@matmaxgeds currently, dates are only picked for projects from AIMS. I will work on IATI dates if they are available for every project

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
This doesn't seem to be working for me?

![Screenshot from 2019-04-23 19-59-54](https://user-images.githubusercontent.com/432153/56604550-762ae080-6602-11e9-9b6c-e1b7a5731df6.png)

**Comment by raashidahmad** [comment]
@matmaxgeds dates buttons are not shown when start and end date is not available with the project. This is the case with IATI project. Please check it with AIMS. It will definitely show the dates. You can select dates individually through buttons

**Comment by matmaxgeds** [comment]
@raashidahmad ok, so this is waiting for a solution to the IATI dates issue - leaving it open until that is fixed so that we can then test this - as the project in the screenshot has dates available, we are just not parsing them: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=XI-IATI-EC_ECHO-ECHO/-HF/BUD/2014/91015

**Comment by raashidahmad** [comment]
@matmaxgeds okay thanks for the input. Sounds good now.
