### ISSUE TITLE
Report menu tweaks

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#80]
The reports menu needs to be:

Title = 'View Reports' - this is currently correct
subtitle - currently = 'projects' - this is not needed
entry 1 - currently = 'Projects Report' - this is wrong, it is the 'Sector Report'

when we add more reports, they will be the 'Location Report'
and 'Budget Report'
and 'Project Profile'
and 'Excel Export' etc
![screenshot from 2019-02-23 23-31-06](https://user-images.githubusercontent.com/432153/53292493-74d86580-37c3-11e9-9f6a-19ce9ac6a864.png)

**Comment by raashidahmad** [comment]
Fixed. We will add more reports later.
