### ISSUE TITLE
Un-needed tab on reports pages

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#83]
See screenshot - we will use the main menu to move between different 
![screenshot from 2019-02-25 15-59-01](https://user-images.githubusercontent.com/432153/53346022-749caf00-3916-11e9-9dce-6c9ab817f66e.png)
reports so that tab system is not needded

**Comment by raashidahmad** [comment]
@matmaxgeds this tab is the part of the page theme. If i remove this tab, the page design will look inconsistent. Closing this ticket, please re-open if you do not agree.
