### ISSUE TITLE
Can see organisations management page as logged out user

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#85]
![screenshot from 2019-02-26 12-50-59](https://user-images.githubusercontent.com/432153/53410837-35796700-39c5-11e9-900f-ad228cd11c77.png)

Something is not working with the permissions as even when logged out I can see the organisations management page - please also check for all the management pages.

I suspect this would be easier if they were all under http://aims.mopied.gov.so/management/organisations - and not just top level pages, as then this could be handled for the whole class of pages, not individually.

**Comment by raashidahmad** [comment]
Fixed.

**Comment by matmaxgeds** [comment]
This appears to have broken the menu to access the management pages?

**Comment by raashidahmad** [comment]
Hi Matt,

Only management user can access management pages. Please login with manager account and test again. Also, i am working on it currently to not show it to standard users.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, sorry, I had mistakenly though my account was a management account. Looking forward to the hidden version.

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks. Working on hidden version. Will deploy with the next push.

**Comment by matmaxgeds** [comment]
@raashidahmad remember that the account management page is there and all users need that, so maybe it is easier to move that to by the logout link first

**Comment by raashidahmad** [comment]
@matmaxgeds fixed it the other way. Please test it with both accounts now.

**Comment by matmaxgeds** [comment]
@raashidahmad looks great - thanks
