### ISSUE TITLE
Create sector gives errors on first load

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#87]
I get an error message for 'sector name is required' on page load - as elsewhere, please evaluate errors on submit
![screenshot from 2019-02-28 22-04-03](https://user-images.githubusercontent.com/432153/53598395-e5f19180-3ba4-11e9-8f5a-120b54cffcd7.png)

**Comment by raashidahmad** [comment]
@matmaxgeds , @kndm Will be fixed in the next deployment. just to help kevin closing this.
