### ISSUE TITLE
Sectors management page needs to seperate sector groups

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#88]
At the moment, the sector list mixes sectors with different parents - please can we use the first page to show all the top level sector groups (any sector without a parent) and then on selecting one, then show the parent and child sectors in a tab for editing.

That was when you add a sector on the first page, you are adding a new group, when you add one on the second page, you are adding a sector within a group, and this continues, if you select a sector within a group, it opens a tab and you can then add child sectors within that parent sector - in each case the parent sector is already selected.

**Comment by raashidahmad** [comment]
Fixed. Now you see listing of sectors. For a child sector you see the parent in listing.
On edit page, you can view, add/remove children for a sector.

**Comment by matmaxgeds** [comment]
Hi - thanks for the new page, but there is quite a lot more to do before this meets the needs:

We will have several different sets of sectors e.g. the Somali NDP Sectors, the OECD DAC CRS Sectors, the Humanitarian Clusters etc. But at the moment, the 'manage sectors' page just shows all the different parent and child sectors together - but if I want to adjust the Somali NDP sectors, I don't need to be able to see at the CRS sector entries. I have attached a drawing of what we are looking for in case that makes it easier. Also, here is the hierarchy:
Sector Group
Sector
Sub-sector
Sub-sub-sector

We also need to be able to delete sectors, sub-sectors and sub-sub-sectors  - at the moment that is not available.

If a sub-sector is added for one sector, then all sectors without a sub-sector have a sub-sector titled 'default sub-sector' added, until they are filled out i.e. a user cannot add a sector, if sub-sectors are available.

Please add the OECD DAC CRS sectors - source: www.oecd.org/dac/financing-sustainable-development/development-finance-standards/DAC-CRS-PPC-2019.xls to test that this new setup works alongside the Somali NDP Sectors.
[Editing sectors v1.pdf](https://github.com/somaliaims/Somali-AIMSUI/files/3004650/Editing.sectors.v1.pdf)
