### ISSUE TITLE
When deleting sector or location ask if projects with that tag should be recoded

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#90]
When deleting a sector or location, as the user if projects coded to the sector or location being deleted should be replaced by another existing location or sector - if so, recode deleted ones to the selected replacement - same also for currencies

**Comment by raashidahmad** [comment]
Fixed. Looking for feedback.

**Comment by matmaxgeds** [comment]
:) an advanced feature - tested and working - will suggest some UI tweaks later
