### ISSUE TITLE
Reports - not all features working

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#91]
- [x] Organisations field on reports is not working
- [ ] Dates field is not drawing from available dates in the data but is hardcoded
- [x] Removing project name from search field and re-clicking 'get report' does not reset the data - it still keeps the search text as a filter - it should wipe the text search filter to then give all projects
- [x] When removing a filter, it does not remove when clicking the 'x' - you have to click 'get data' this should not be the case
- [x] When selecting a location - the chart is no longer shown, and there is no change to the table

All of this suggests that very little testing was done on the reports before they were released, please when you add features, can you test each one to make sure that it behaves as expected.

**Comment by kndm** [comment]
@matmaxgeds Working on this over the weekend (today/saturday) as this sounds quite important, can I get on when the next iteration of the system will be shown? This way I know whether I should prioritize this over the other issues right now.

**Comment by raashidahmad** [comment]
@kndm I am looking into this issue, Thanks. For this task, i have to look at the backend as well and make fixes

**Comment by kndm** [comment]
@raashidahmad Got it, I will look for issues outside of the beta launch label then that I can help out with in the meanwhile.

**Comment by raashidahmad** [comment]
@matmaxgeds I have deployed latest version of UI build. There was an exception occurring in the back-end that was making many feature not to work. Auto search on removing an organization, or sector, seems unnatural to me. Anyways, i let you see how you feel about this. Closing it, so that you get a notification. Re-open it please if you see any bug.

**Comment by matmaxgeds** [comment]
Thanks Rashid - let's discuss in Mogadsihu - I am even wondering about autosearch when adding a field.

However, keeping this open as the date field is still hardcoded - I added a project with dates from 2010 to 2014 http://104.140.103.166:7001/view-project/46 but there is no option to select those dates.

**Comment by raashidahmad** [comment]
@matmaxgeds the years are coming from database called financial years. However there is no management page visible to user from where manager can view/add etc. Will design the page soon.

**Comment by matmaxgeds** [comment]
@raashidahmad good to know - thanks - so as soon as we have a management page to select the financial year (just specify the start and end day/month within the calendar year), then the system can lookup the FYs from the data.
