### ISSUE TITLE
Select sector dropdown menu's in reports need to show only the default AIMS sectors

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#94]
At the moment, in the sector dropdowns in the reports show all sectors, however, many of these sector groups are primarily for data input and should only be shown there, on the reports page, only the primary AIMS sector group (set in the management pages) should be shown, and there needs to be a way to distinguish between the different levels e.g. under the default sector group, there are parents and children and this relationship needs to be seen on the dropdown, or maybe there need to be two dropdowns - but ideally this can be done with indentation of the child sectors

**Comment by raashidahmad** [comment]
Fixed
